import http from 'node:http';
import {randomBytes,timingSafeEqual,createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {privateStore} from './private-store.mjs';

export const FACEBOOK_SCOPE='pages_show_list,pages_read_engagement,pages_manage_posts';
export const FACEBOOK_ROUTE='official_api',FACEBOOK_ROUTE_DRIVER='facebook_pages_api',FACEBOOK_PUBLICATION_POLICY='exact_post_approval_required';
const TTL=10*60*1000,MAX_MESSAGE=63206,ROUTE_SIGNALS=['page_identity_reverified','page_published_posts_readable'];
const digest=value=>createHash('sha256').update(value).digest('hex'),stable=value=>JSON.stringify(value,Object.keys(value).sort());
const eq=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const tokenOk=v=>typeof v==='string'&&v.length>20&&v.length<16384&&!/[\s\x00-\x1f]/.test(v);
const pageName=v=>typeof v==='string'&&v.length>0&&v.length<=160&&!/[\x00\r\n]/.test(v)?v:null;
const pageId=v=>(typeof v==='string'||typeof v==='number')&&/^\d{5,30}$/.test(String(v))?String(v):null;
const linkUrl=v=>{if(v===null)return null;try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)&&!u.username&&!u.password&&!u.hash&&u.toString().length<=2048?u.toString():null;}catch{return null;}};

export const facebookPublishManifest=value=>({account:value?.account,pageId:value?.pageId,destination:value?.destination,nativeFormat:value?.nativeFormat,message:value?.message,link:value?.link,visibility:value?.visibility,scheduledAt:value?.scheduledAt,derivatives:value?.derivatives});
export const facebookPublishHash=value=>digest(stable(facebookPublishManifest(value)));
export const facebookIdempotencyKey=value=>digest('facebook.publish\0'+facebookPublishHash(value));
async function safeJson(r){const chunks=[];let size=0;for await(const c of r.body){size+=c.length;if(size>1024*1024)throw new Error('response_too_large');chunks.push(Buffer.from(c));}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
async function readBody(req,limit=131072){let raw='';for await(const c of req){raw+=c;if(Buffer.byteLength(raw)>limit)throw new Error('request_too_large');}return JSON.parse(raw||'{}');}
function validManifest(body,record,now){
 const expected=['account','approvalReceiptHash','derivatives','destination','idempotencyKey','link','message','nativeFormat','pageId','scheduledAt','visibility'];
 const scheduled=body?.scheduledAt===null?true:(typeof body?.scheduledAt==='string'&&!Number.isNaN(Date.parse(body.scheduledAt))&&Date.parse(body.scheduledAt)>=now()+10*60*1000&&Date.parse(body.scheduledAt)<=now()+75*24*60*60*1000);
 return body&&Object.keys(body).sort().join(',')===expected.join(',')&&body.account===record.pageName&&body.pageId===record.pageId&&body.destination==='page_feed'&&body.nativeFormat==='facebook.page_post'&&typeof body.message==='string'&&body.message.length>0&&body.message.length<=MAX_MESSAGE&&!/[\x00]/.test(body.message)&&linkUrl(body.link)===body.link&&body.visibility==='public'&&scheduled&&Array.isArray(body.derivatives)&&body.derivatives.length===0&&/^[a-f0-9]{64}$/.test(body.approvalReceiptHash||'')&&/^[a-f0-9]{64}$/.test(body.idempotencyKey||'')&&eq(body.approvalReceiptHash,facebookPublishHash(body))&&eq(body.idempotencyKey,facebookIdempotencyKey(body));
}

export async function createFacebookBroker({port,studioPort,root,capability,clientId,clientSecret,configurationId,publicBaseUrl=null,fetchApi=fetch,now=Date.now}){
 if(!Number.isInteger(port)||port<1024||port>65535||!Number.isInteger(studioPort)||studioPort<1024||studioPort>65535||port===studioPort||typeof capability!=='string'||capability.length<40)throw new Error('invalid_configuration');
 const keychain=account=>{try{return execFileSync('/usr/bin/security',['find-generic-password','-s','James Au Studio Facebook OAuth','-a',account,'-w'],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:10000}).replace(/\n$/,'');}catch{return null;}};
 if(!(typeof clientId==='string'&&/^\d{5,30}$/.test(clientId)))clientId=keychain('client-id');
 if(!(typeof clientSecret==='string'&&clientSecret.length>=16))clientSecret=keychain('client-secret');
 let publicBase=null;if(publicBaseUrl!==null){try{const c=new URL(publicBaseUrl);if(c.protocol!=='https:'||c.username||c.password||!['','/'].includes(c.pathname)||c.search||c.hash)throw new Error();publicBase=c.origin;}catch{throw new Error('invalid_public_callback');}}
 const callbackUri=publicBase?publicBase+'/callback':'http://127.0.0.1:'+port+'/callback';
 const configured=typeof clientId==='string'&&/^\d{5,30}$/.test(clientId)&&typeof clientSecret==='string'&&clientSecret.length>=16&&/^\d{5,30}$/.test(configurationId||'');
 const store=await privateStore(root),control=store('facebook-control'),tokens=store('facebook-tokens'),attempts=store('facebook-publish-attempts');
 let pending=await control.get('pending'),record=await control.get('identity'),routeRecord=await control.get('route'),verifiedThisRun=false,publishing=false;
 if(pending?.phase==='verifying'){pending={...pending,phase:'connection_unresolved'};await control.set('pending',pending);}
 const generation=()=>record?digest(stable({expiresAt:record.expiresAt,pageId:record.pageId,scope:record.scope,userId:record.userId})):null;
 const identityCurrent=()=>configured&&pending?.phase!=='connection_unresolved'&&verifiedThisRun&&record&&Date.parse(record.expiresAt)>now();
 const routeCurrent=()=>identityCurrent()&&routeRecord?.state==='publish_ready'&&routeRecord?.authGeneration===generation();
 const status=()=>({provider:'facebook',available:configured,state:pending?.phase==='connection_unresolved'?'connection_unresolved':record?(identityCurrent()?'connected_identity':'verification_required'):(configured&&pending&&pending.expires>now()?pending.phase:(configured?'not_connected':'configuration_required')),userName:record?.userName||null,userId:record?.userId||null,pageName:record?.pageName||pending?.pageName||null,pageId:record?.pageId||pending?.pageId||null,tasks:record?.tasks||[],scope:FACEBOOK_SCOPE,configurationId:configurationId||null,route:FACEBOOK_ROUTE,routeDriver:FACEBOOK_ROUTE_DRIVER,verifiedAt:record?.verifiedAt||null,expiresAt:record?.expiresAt||null,identitySignals:identityCurrent()?['facebook_user_id','facebook_page_id','facebook_page_name','page_tasks']:[],routeState:routeCurrent()?'publish_ready':'not_tested',routeTestId:routeCurrent()?routeRecord.routeTestId:null,routeTestedAt:routeCurrent()?routeRecord.testedAt:null,routeTestSignals:routeCurrent()?ROUTE_SIGNALS:[],publicationPolicy:FACEBOOK_PUBLICATION_POLICY,publishReady:routeCurrent(),publishing});
 const headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'"},json=(res,code,body)=>{res.writeHead(code,{...headers,'Content-Type':'application/json'});res.end(JSON.stringify(body));},redirect=(res,url,cookie)=>{res.writeHead(303,{...headers,Location:url,...(cookie?{'Set-Cookie':cookie}:{})});res.end();};
 const persist=async v=>{pending=v;await control.set('pending',v);};
 const api=async(url,options={})=>{const response=await fetchApi(url,{redirect:'error',signal:AbortSignal.timeout(30000),...options}),value=await safeJson(response);if(!response.ok){const error=new Error('facebook_api_failed'),graph=value?.error;error.providerStatus=response.status;error.providerCode=Number.isInteger(graph?.code)?graph.code:null;error.providerSubcode=Number.isInteger(graph?.error_subcode)?graph.error_subcode:null;throw error;}return value;};
 const savedToken=async()=>{const saved=await tokens.get('page');if(!saved?.pageAccessToken||Date.parse(saved.expiresAt)<=now())throw new Error('reauthorization_required');return saved;};
 const pageIdentity=async(pageAccessToken,expected)=>{const u=new URL('https://graph.facebook.com/v26.0/'+expected.pageId);u.searchParams.set('fields','id,name');u.searchParams.set('access_token',pageAccessToken);const value=await api(u);if(pageId(value?.id)!==expected.pageId||pageName(value?.name)!==expected.pageName)throw new Error('identity_mismatch');return value;};
 const verifySaved=async()=>{if(!record)throw new Error('identity_not_connected');const saved=await savedToken();await pageIdentity(saved.pageAccessToken,record);record={...record,verifiedAt:new Date(now()).toISOString()};await control.set('identity',record);verifiedThisRun=true;return saved;};
 const evidence=async(accessToken,id)=>{const u=new URL('https://graph.facebook.com/v26.0/'+id);u.searchParams.set('fields','id,message,permalink_url,created_time,is_published,scheduled_publish_time,attachments{url,target}');u.searchParams.set('access_token',accessToken);return api(u);};
 const attachmentUrl=value=>{const direct=linkUrl(value);if(!direct)return null;const parsed=new URL(direct);if(parsed.hostname==='l.facebook.com'&&parsed.pathname==='/l.php')return linkUrl(parsed.searchParams.get('u'));return direct;};
 const linkAttached=(value,expected)=>{const data=value?.attachments?.data;return Array.isArray(data)&&data.some(item=>attachmentUrl(item?.target?.url||item?.url)===expected);};
 const messageMatches=(actual,manifest)=>{if(actual===manifest.message)return true;if(typeof actual!=='string'||!manifest.link)return false;const first=manifest.message.indexOf(manifest.link);return first>=0&&manifest.message.indexOf(manifest.link,first+manifest.link.length)<0&&actual===manifest.message.slice(0,first)+manifest.message.slice(first+manifest.link.length);};
 const verifyPost=(value,manifest)=>{const id=typeof value?.id==='string'?value.id:null,url=typeof value?.permalink_url==='string'?value.permalink_url:null,scheduled=manifest.scheduledAt!==null;if(!id||!messageMatches(value.message,manifest)||(manifest.link!==null&&!linkAttached(value,manifest.link))||(scheduled?value.is_published!==false:!/^https:\/\/(www\.)?facebook\.com\//.test(url||'')))throw new Error('publication_unverified');if(scheduled&&Math.abs(Number(value.scheduled_publish_time)*1000-Date.parse(manifest.scheduledAt))>1000)throw new Error('publication_unverified');return {postId:id,url:scheduled?null:url,pageId:record.pageId,pageName:record.pageName,message:value.message,scheduledAt:manifest.scheduledAt,state:scheduled?'scheduled':'published'};};
 const server=http.createServer(async(req,res)=>{try{
  if(req.headers.host!=='127.0.0.1:'+port){json(res,403,{error:'host_not_allowed'});return;}const url=new URL(req.url,'http://127.0.0.1:'+port);
  if(url.pathname==='/callback'&&req.method==='GET'){const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('studio_facebook_nonce='))?.slice(22),allowed=new Set(['code','state','error','error_reason','error_description']);if(!pending||pending.phase!=='private_handoff'||pending.expires<=now()||!cookie||!eq(digest(cookie),pending.browserHash)||[...url.searchParams.keys()].some(k=>!allowed.has(k)||url.searchParams.getAll(k).length!==1)){json(res,400,{error:'callback_not_expected'});return;}const selected=pending;await persist({...selected,phase:'verifying',ticketHash:null,browserHash:null});let started=false;try{if(url.searchParams.get('error')||!eq(url.searchParams.get('state'),selected.flow))throw new Error();started=true;const tokenUrl=new URL('https://graph.facebook.com/v26.0/oauth/access_token');tokenUrl.searchParams.set('client_id',clientId);tokenUrl.searchParams.set('client_secret',clientSecret);tokenUrl.searchParams.set('redirect_uri',callbackUri);tokenUrl.searchParams.set('code',url.searchParams.get('code')||'');const token=await api(tokenUrl);if(!tokenOk(token?.access_token))throw new Error();const userUrl=new URL('https://graph.facebook.com/v26.0/me');userUrl.searchParams.set('fields','id,name');userUrl.searchParams.set('access_token',token.access_token);const user=await api(userUrl),pagesUrl=new URL('https://graph.facebook.com/v26.0/me/accounts');pagesUrl.searchParams.set('fields','id,name,access_token,tasks');pagesUrl.searchParams.set('access_token',token.access_token);const pages=await api(pagesUrl),matches=(Array.isArray(pages?.data)?pages.data:[]).filter(p=>pageId(p.id)===selected.pageId&&pageName(p.name)===selected.pageName&&tokenOk(p.access_token));if(matches.length!==1||!matches[0].tasks?.includes('CREATE_CONTENT'))throw new Error();const p=matches[0],expiresIn=Number.isFinite(token.expires_in)&&token.expires_in>0?token.expires_in:60*24*60*60,expiresAt=new Date(now()+Math.min(expiresIn,60*24*60*60)*1000).toISOString();record={userName:pageName(user.name),userId:pageId(user.id),pageName:p.name,pageId:String(p.id),tasks:p.tasks.sort(),scope:FACEBOOK_SCOPE,verifiedAt:new Date(now()).toISOString(),expiresAt};await tokens.set('page',{pageAccessToken:p.access_token,expiresAt,scope:FACEBOOK_SCOPE});await control.set('identity',record);routeRecord=null;await control.del('route');verifiedThisRun=true;await persist({...selected,phase:'complete',ticketHash:null,browserHash:null});}catch{verifiedThisRun=false;await persist({...selected,phase:started?'connection_unresolved':'connection_failed',ticketHash:null,browserHash:null});}redirect(res,'http://127.0.0.1:'+studioPort+'/connection-return','studio_facebook_nonce=; HttpOnly; SameSite=Lax; Path=/callback; Max-Age=0');return;}
  if(url.pathname.startsWith('/begin/')&&req.method==='GET'){const ticket=url.pathname.slice(7);if(!pending||pending.phase!=='awaiting_private_signin'||pending.expires<=now()||!eq(digest(ticket),pending.ticketHash)){json(res,410,{error:'signin_expired'});return;}const nonce=randomBytes(32).toString('hex'),authorize=new URL('https://www.facebook.com/v26.0/dialog/oauth');for(const [k,v] of Object.entries({client_id:clientId,redirect_uri:callbackUri,response_type:'code',display:'page',scope:FACEBOOK_SCOPE,state:pending.flow}))authorize.searchParams.set(k,v);await persist({...pending,phase:'private_handoff',ticketHash:null,browserHash:digest(nonce)});redirect(res,authorize.toString(),'studio_facebook_nonce='+nonce+'; HttpOnly; SameSite=Lax; Path=/callback; Max-Age=600'+(publicBase?'; Secure':''));return;}
  if(!eq(req.headers['x-studio-broker'],capability)){json(res,403,{error:'broker_access_denied'});return;}
  if(url.pathname==='/status'&&req.method==='GET'){json(res,200,status());return;}
  if(url.pathname==='/verify'&&req.method==='POST'){if(pending?.phase==='connection_unresolved'){json(res,409,{error:'reconciliation_required'});return;}verifiedThisRun=false;try{await verifySaved();}catch{}json(res,200,status());return;}
  if(url.pathname==='/route-test'&&req.method==='POST'){const body=await readBody(req),expected={account:record?.pageName,pageId:record?.pageId,destination:'page_feed',nativeFormat:'facebook.page_post',route:FACEBOOK_ROUTE,routeDriver:FACEBOOK_ROUTE_DRIVER};if(stable(body)!==stable(expected)){json(res,422,{error:'invalid_route_test_manifest'});return;}verifiedThisRun=false;const saved=await verifySaved(),posts=new URL('https://graph.facebook.com/v26.0/'+record.pageId+'/published_posts');posts.searchParams.set('fields','id');posts.searchParams.set('limit','1');posts.searchParams.set('access_token',saved.pageAccessToken);try{await api(posts);}catch(error){if(error?.message!=='facebook_api_failed')throw error;json(res,409,{error:'facebook_page_posts_unreadable',providerStatus:error.providerStatus??null,providerCode:error.providerCode??null,providerSubcode:error.providerSubcode??null});return;}routeRecord={state:'publish_ready',routeTestId:'facebook-'+randomBytes(20).toString('hex'),testedAt:new Date(now()).toISOString(),signals:ROUTE_SIGNALS,authGeneration:generation()};await control.set('route',routeRecord);json(res,200,status());return;}
  if(url.pathname==='/publish-post'&&req.method==='POST'){const body=await readBody(req);if(!record||!validManifest(body,record,now())){json(res,422,{error:'invalid_publish_manifest'});return;}if(!routeCurrent()){json(res,409,{error:'publish_route_not_ready'});return;}const manifest=facebookPublishManifest(body),key=body.idempotencyKey,saved=await savedToken();let attempt=await attempts.get(key);if(attempt){if(attempt.payloadHash!==body.approvalReceiptHash){json(res,409,{error:'idempotency_conflict'});return;}if(attempt.state==='verified'){json(res,200,{...attempt.result,replayed:true});return;}if(attempt.postId){try{const result=verifyPost(await evidence(saved.pageAccessToken,attempt.postId),manifest),verifiedAt=new Date(now()).toISOString();attempt={...attempt,state:'verified',result,verifiedAt};await attempts.set(key,attempt);json(res,200,{...result,verifiedAt,replayed:true});return;}catch{}}json(res,409,{error:'facebook_publish_unresolved'});return;}publishing=true;attempt={state:'reserved',payloadHash:body.approvalReceiptHash,startedAt:new Date(now()).toISOString(),postId:null};await attempts.set(key,attempt);try{const form=new URLSearchParams({message:manifest.message,access_token:saved.pageAccessToken});if(manifest.link)form.set('link',manifest.link);if(manifest.scheduledAt){form.set('published','false');form.set('scheduled_publish_time',String(Math.floor(Date.parse(manifest.scheduledAt)/1000)));}const created=await api('https://graph.facebook.com/v26.0/'+record.pageId+'/feed',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form}),postId=typeof created?.id==='string'?created.id:null;if(!postId)throw new Error();attempt={...attempt,state:'submitted',postId};await attempts.set(key,attempt);const result=verifyPost(await evidence(saved.pageAccessToken,postId),manifest),verifiedAt=new Date(now()).toISOString();attempt={...attempt,state:'verified',result,verifiedAt};await attempts.set(key,attempt);json(res,200,{...result,verifiedAt,replayed:false});}catch{attempt={...attempt,state:attempt.postId?'submitted':'uncertain'};await attempts.set(key,attempt);json(res,409,{error:'facebook_publish_unresolved'});}finally{publishing=false;}return;}
  if(url.pathname==='/prepare'&&req.method==='POST'){if(!configured){json(res,503,{error:'configuration_required'});return;}const body=await readBody(req,2048);if(Object.keys(body).sort().join(',')!=='pageId,pageName,scope'||body.scope!==FACEBOOK_SCOPE||!pageId(body.pageId)||!pageName(body.pageName)){json(res,422,{error:'invalid_identity'});return;}if(record){json(res,409,{error:'account_already_connected'});return;}const flow=randomBytes(32).toString('hex'),ticket=randomBytes(32).toString('hex');await persist({pageId:String(body.pageId),pageName:body.pageName,flow,expires:now()+TTL,phase:'awaiting_private_signin',ticketHash:digest(ticket)});json(res,200,{beginPath:'/begin/'+ticket});return;}
  json(res,404,{error:'operation_unavailable'});
 }catch(error){const code=error?.message==='request_too_large'?413:500;if(!res.headersSent)json(res,code,{error:code===413?'request_too_large':'connection_operation_failed'});else res.end();}});
 return {server,status};
}
