import http from 'node:http';
import {randomBytes,timingSafeEqual,createHash} from 'node:crypto';
import {privateStore} from './private-store.mjs';

export const INSTAGRAM_SCOPE='instagram_business_basic,instagram_business_content_publish';
export const INSTAGRAM_ROUTE='official_api';
export const INSTAGRAM_ROUTE_DRIVER='instagram_api_with_instagram_login';
export const INSTAGRAM_PUBLICATION_POLICY='exact_post_approval_required';
const TTL=10*60*1000,MAX_CAPTION=2200,MAX_ALT=1000;
const ROUTE_SIGNALS=['identity_reverified','publishing_quota_read'];
const digest=value=>createHash('sha256').update(value).digest('hex');
const stable=value=>JSON.stringify(value,Object.keys(value).sort());
const eq=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const username=value=>typeof value==='string'&&/^[a-z0-9._]{1,30}$/i.test(value)?value.toLowerCase():null;
const tokenOk=value=>typeof value==='string'&&value.length>20&&value.length<16384&&!/[\s\x00-\x1f]/.test(value);
const mediaUrl=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&u.toString().length<=2048?u.toString():null;}catch{return null;}};

export const instagramPublishManifest=value=>({account:value?.account,destination:value?.destination,nativeFormat:value?.nativeFormat,mediaType:value?.mediaType,imageUrl:value?.imageUrl,caption:value?.caption,altText:value?.altText,visibility:value?.visibility,scheduledAt:value?.scheduledAt,derivatives:value?.derivatives});
export const instagramPublishHash=value=>digest(stable(instagramPublishManifest(value)));
export const instagramIdempotencyKey=value=>digest('instagram.publish\0'+instagramPublishHash(value));

async function safeJson(response){const chunks=[];let size=0;for await(const chunk of response.body){size+=chunk.length;if(size>1024*1024)throw new Error('response_too_large');chunks.push(Buffer.from(chunk));}return JSON.parse(Buffer.concat(chunks).toString('utf8'));}
async function readBody(req,limit=16384){let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>limit)throw new Error('request_too_large');}return JSON.parse(raw||'{}');}
function validManifest(body){
  const expected=['account','altText','approvalReceiptHash','caption','derivatives','destination','idempotencyKey','imageUrl','mediaType','nativeFormat','scheduledAt','visibility'];
  return body&&typeof body==='object'&&!Array.isArray(body)&&Object.keys(body).sort().join(',')===expected.join(',')
    &&body.account==='@jamesaucreates'&&body.destination==='main_profile_feed'&&body.nativeFormat==='instagram.feed_image'&&body.mediaType==='IMAGE'
    &&mediaUrl(body.imageUrl)===body.imageUrl&&typeof body.caption==='string'&&body.caption.length<=MAX_CAPTION&&!/[\x00]/.test(body.caption)
    &&typeof body.altText==='string'&&body.altText.length>0&&body.altText.length<=MAX_ALT&&!/[\x00\r\n]/.test(body.altText)
    &&body.visibility==='public'&&body.scheduledAt===null&&Array.isArray(body.derivatives)&&body.derivatives.length===0
    &&/^[a-f0-9]{64}$/.test(body.approvalReceiptHash||'')&&/^[a-f0-9]{64}$/.test(body.idempotencyKey||'')
    &&eq(body.approvalReceiptHash,instagramPublishHash(body))&&eq(body.idempotencyKey,instagramIdempotencyKey(body));
}

export async function createInstagramBroker({port,studioPort,root,capability,clientId,clientSecret,publicBaseUrl=null,fetchApi=fetch,now=Date.now}){
  if(!Number.isInteger(port)||port<1024||port>65535||!Number.isInteger(studioPort)||studioPort<1024||studioPort>65535||port===studioPort||typeof capability!=='string'||capability.length<40)throw new Error('invalid_configuration');
  let publicBase=null;if(publicBaseUrl!==null){try{const c=new URL(publicBaseUrl);if(c.protocol!=='https:'||c.username||c.password||!['','/'].includes(c.pathname)||c.search||c.hash)throw new Error();publicBase=c.origin;}catch{throw new Error('invalid_public_callback');}}
  const callbackUri=publicBase?publicBase+'/callback':'http://127.0.0.1:'+port+'/callback';
  const configured=typeof clientId==='string'&&/^\d{5,30}$/.test(clientId)&&typeof clientSecret==='string'&&clientSecret.length>=16;
  const store=await privateStore(root),control=store('instagram-control'),tokens=store('instagram-tokens'),attempts=store('instagram-publish-attempts');
  let pending=await control.get('pending'),record=await control.get('identity'),routeRecord=await control.get('route');
  if(pending&&['preparing','verifying'].includes(pending.phase)){pending={...pending,phase:'connection_unresolved'};await control.set('pending',pending);}
  let verifiedThisRun=false,verificationInProgress=false,publishing=false;
  const generation=()=>record?digest(stable({expiresAt:record.expiresAt,scope:record.scope,userId:record.userId,username:record.username})):null;
  const identityCurrent=()=>configured&&pending?.phase!=='connection_unresolved'&&verifiedThisRun&&record&&Date.parse(record.expiresAt)>now();
  const routeCurrent=()=>identityCurrent()&&routeRecord?.state==='publish_ready'&&routeRecord?.authGeneration===generation();
  const status=()=>({provider:'instagram',available:configured,state:pending?.phase==='connection_unresolved'?'connection_unresolved':record?(identityCurrent()?'connected_identity':'verification_required'):(configured&&pending&&pending.expires>now()?pending.phase:(configured?'not_connected':'configuration_required')),username:record?.username||pending?.username||null,userId:record?.userId||null,accountType:record?.accountType||null,scope:INSTAGRAM_SCOPE,route:INSTAGRAM_ROUTE,routeDriver:INSTAGRAM_ROUTE_DRIVER,verifiedAt:record?.verifiedAt||null,expiresAt:record?.expiresAt||null,identitySignals:identityCurrent()?['instagram_username','instagram_professional_user_id','instagram_account_type']:[],routeState:routeCurrent()?'publish_ready':'not_tested',routeTestId:routeCurrent()?routeRecord.routeTestId:null,routeTestedAt:routeCurrent()?routeRecord.testedAt:null,routeTestSignals:routeCurrent()?ROUTE_SIGNALS:[],publicationPolicy:INSTAGRAM_PUBLICATION_POLICY,publishReady:routeCurrent(),publishing});
  const headers={'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'"};
  const json=(res,code,body)=>{res.writeHead(code,{...headers,'Content-Type':'application/json'});res.end(JSON.stringify(body));};
  const redirect=(res,url,cookie)=>{res.writeHead(303,{...headers,Location:url,...(cookie?{'Set-Cookie':cookie}:{})});res.end();};
  const persist=async value=>{pending=value;await control.set('pending',value);};
  const api=async(url,options={})=>{const response=await fetchApi(url,{redirect:'error',signal:AbortSignal.timeout(30000),...options}),value=await safeJson(response);if(!response.ok)throw new Error('instagram_api_failed');return value;};
  const identity=async(accessToken,expected)=>{
    const profileUrl=new URL('https://graph.instagram.com/v26.0/me');
    profileUrl.searchParams.set('fields','user_id,username,account_type');
    profileUrl.searchParams.set('access_token',accessToken);
    const profile=await api(profileUrl),item=Array.isArray(profile.data)?profile.data[0]:profile;
    const actual=username(item?.username),id=item?.user_id??item?.id,type=item?.account_type;
    const accountType=type==='MEDIA_CREATOR'?'Media_Creator':type==='BUSINESS'?'Business':type;
    if(actual!==expected.username)throw new Error('identity_username_mismatch');
    if(!id)throw new Error('identity_id_missing');
    if(!['Business','Media_Creator'].includes(accountType)){const error=new Error('identity_account_type_invalid');error.observedType=typeof type==='string'&&/^[A-Za-z_]{1,32}$/.test(type)?type:'missing_or_invalid';throw error;}
    // Instagram's token-exchange user_id and Graph profile user_id can use different ID namespaces.
    // On reconnect, bind to the already verified Graph profile ID instead.
    if(expected.verifiedAt&&expected.userId&&String(id)!==expected.userId)
      throw new Error('identity_id_mismatch');
    return {username:actual,userId:String(id),accountType,scope:INSTAGRAM_SCOPE,verifiedAt:new Date(now()).toISOString()};
  };
  const exchangeCode=async code=>{const form=new FormData();for(const [k,v] of Object.entries({client_id:clientId,client_secret:clientSecret,grant_type:'authorization_code',redirect_uri:callbackUri,code}))form.append(k,v);const token=await api('https://api.instagram.com/oauth/access_token',{method:'POST',body:form});if(!tokenOk(token?.access_token)||!(token?.user_id||token?.data?.[0]?.user_id))throw new Error('invalid_short_token');return token;};
  const exchangeLong=async shortToken=>{const u=new URL('https://graph.instagram.com/access_token');u.searchParams.set('grant_type','ig_exchange_token');u.searchParams.set('client_secret',clientSecret);u.searchParams.set('access_token',shortToken);const token=await api(u);if(!tokenOk(token?.access_token)||!Number.isFinite(token?.expires_in)||token.expires_in<=0||token.expires_in>90*24*60*60)throw new Error('invalid_long_token');return token;};
  const savedToken=async()=>{const saved=await tokens.get('identity');if(!saved?.accessToken||Date.parse(saved.expiresAt)<=now())throw new Error('reauthorization_required');return saved;};
  const verifySaved=async()=>{if(!record)throw new Error('identity_not_connected');const saved=await savedToken(),next=await identity(saved.accessToken,record);next.expiresAt=saved.expiresAt;await control.set('identity',next);record=next;verifiedThisRun=true;return saved;};
  const quota=async accessToken=>{const u=new URL('https://graph.instagram.com/v26.0/'+record.userId+'/content_publishing_limit');u.searchParams.set('fields','quota_usage,config');u.searchParams.set('access_token',accessToken);const value=await api(u),row=value?.data?.[0]??value,usage=row?.quota_usage,total=row?.config?.quota_total,duration=row?.config?.quota_duration;if(!Number.isInteger(usage)||usage<0||!Number.isInteger(total)||total<1||usage>total||!Number.isInteger(duration)||duration<1)throw new Error('publishing_quota_unavailable');return {usage,total,duration};};
  const evidence=async(accessToken,id)=>{const u=new URL('https://graph.instagram.com/v26.0/'+id);u.searchParams.set('fields','id,caption,media_type,media_product_type,permalink,username,timestamp');u.searchParams.set('access_token',accessToken);return api(u);};
  const verifyMedia=(value,manifest)=>{const id=typeof value?.id==='string'?value.id:null,url=typeof value?.permalink==='string'?value.permalink:null,timestamp=typeof value?.timestamp==='string'&&!Number.isNaN(Date.parse(value.timestamp))?value.timestamp:null;if(!id||(value.caption||'')!==manifest.caption||value.media_type!=='IMAGE'||!['FEED',''].includes(value.media_product_type||'')||username(value.username)!==record.username||!timestamp||!/^https:\/\/(www\.)?instagram\.com\//.test(url||''))throw new Error('publication_unverified');return {mediaId:id,url,username:record.username,caption:value.caption||'',mediaType:'IMAGE',timestamp};};
  const server=http.createServer(async(req,res)=>{try{
    if(req.headers.host!=='127.0.0.1:'+port){json(res,403,{error:'host_not_allowed'});return;}const url=new URL(req.url,'http://127.0.0.1:'+port);
    if(url.pathname==='/callback'&&req.method==='GET'){const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith('studio_instagram_nonce='))?.slice(23),allowed=new Set(['code','state','error','error_reason','error_description']);if(!pending||pending.phase!=='private_handoff'||pending.expires<=now()||!cookie||!eq(digest(cookie),pending.browserHash)||[...url.searchParams.keys()].some(k=>!allowed.has(k)||url.searchParams.getAll(k).length!==1)||url.search.length>16384){json(res,400,{error:'callback_not_expected'});return;}const selected=pending;await persist({...selected,phase:'verifying',ticketHash:null,browserHash:null});let started=false,stage='authorization';try{if(url.searchParams.get('error')||!eq(url.searchParams.get('state'),selected.flow))throw new Error('authorization_failed');started=true;stage='short_token';const short=await exchangeCode(url.searchParams.get('code')||'');stage='long_token';const long=await exchangeLong(short.access_token);stage='identity';const next=await identity(long.access_token,{...selected,userId:String(short.user_id??short.data?.[0]?.user_id)});next.expiresAt=new Date(now()+long.expires_in*1000).toISOString();stage='vault';await tokens.set('identity',{accessToken:long.access_token,expiresAt:next.expiresAt,scope:INSTAGRAM_SCOPE});await control.set('identity',next);record=next;routeRecord=null;await control.del('route');verifiedThisRun=true;await persist({...selected,phase:'complete',ticketHash:null,browserHash:null});}catch(error){verifiedThisRun=false;const failureCode=['authorization_failed','invalid_short_token','invalid_long_token','instagram_api_failed','identity_username_mismatch','identity_id_missing','identity_id_mismatch','identity_account_type_invalid'].includes(error?.message)?error.message:'operation_failed';await persist({...selected,phase:started?'connection_unresolved':'connection_failed',ticketHash:null,browserHash:null,failureStage:stage,failureCode,failureAccountType:error?.observedType??null});}redirect(res,'http://127.0.0.1:'+studioPort+'/connection-return','studio_instagram_nonce=; HttpOnly; SameSite=Lax; Path=/callback; Max-Age=0');return;}
    if(url.pathname.startsWith('/begin/')&&req.method==='GET'){const ticket=url.pathname.slice(7);if(!pending||pending.phase!=='awaiting_private_signin'||pending.expires<=now()||!eq(digest(ticket),pending.ticketHash)){json(res,410,{error:'signin_expired'});return;}const nonce=randomBytes(32).toString('hex'),authorize=new URL('https://www.instagram.com/oauth/authorize');for(const [k,v] of Object.entries({client_id:clientId,redirect_uri:callbackUri,response_type:'code',scope:INSTAGRAM_SCOPE,state:pending.flow}))authorize.searchParams.set(k,v);await persist({...pending,phase:'private_handoff',ticketHash:null,browserHash:digest(nonce)});redirect(res,authorize.toString(),'studio_instagram_nonce='+nonce+'; HttpOnly; SameSite=Lax; Path=/callback; Max-Age=600'+(publicBase?'; Secure':''));return;}
    if(!eq(req.headers['x-studio-broker'],capability)){json(res,403,{error:'broker_access_denied'});return;}
    if(url.pathname==='/status'&&req.method==='GET'){json(res,200,status());return;}
    if(url.pathname==='/verify'&&req.method==='POST'){if(pending?.phase==='connection_unresolved'){json(res,409,{error:'reconciliation_required'});return;}if(!configured){json(res,503,{error:'configuration_required'});return;}if(!record){json(res,409,{error:'identity_not_connected'});return;}if(verificationInProgress){json(res,409,{error:'verification_in_progress'});return;}verificationInProgress=true;verifiedThisRun=false;try{await verifySaved();}catch{verifiedThisRun=false;}finally{verificationInProgress=false;}json(res,200,status());return;}
    if(url.pathname==='/route-test'&&req.method==='POST'){const body=await readBody(req),expected={account:'@jamesaucreates',destination:'main_profile_feed',nativeFormat:'instagram.feed_image',mediaType:'IMAGE',route:INSTAGRAM_ROUTE,routeDriver:INSTAGRAM_ROUTE_DRIVER};if(stable(body)!==stable(expected)){json(res,422,{error:'invalid_route_test_manifest'});return;}verifiedThisRun=false;const saved=await verifySaved(),quotaInfo=await quota(saved.accessToken);routeRecord={state:'publish_ready',routeTestId:'instagram-'+randomBytes(20).toString('hex'),testedAt:new Date(now()).toISOString(),signals:ROUTE_SIGNALS,authGeneration:generation(),quota:quotaInfo};await control.set('route',routeRecord);json(res,200,status());return;}
    if(url.pathname==='/publish-image'&&req.method==='POST'){const body=await readBody(req);if(!validManifest(body)){json(res,422,{error:'invalid_publish_manifest'});return;}if(!routeCurrent()){json(res,409,{error:'publish_route_not_ready'});return;}const manifest=instagramPublishManifest(body),key=body.idempotencyKey,saved=await savedToken();let attempt=await attempts.get(key);if(attempt){if(attempt.payloadHash!==body.approvalReceiptHash){json(res,409,{error:'idempotency_conflict'});return;}if(attempt.state==='verified'){json(res,200,{...attempt.result,replayed:true});return;}if(attempt.mediaId){try{const result=verifyMedia(await evidence(saved.accessToken,attempt.mediaId),manifest),verifiedAt=new Date(now()).toISOString();attempt={...attempt,state:'verified',result,verifiedAt};await attempts.set(key,attempt);json(res,200,{...result,verifiedAt,replayed:true});return;}catch{}}json(res,409,{error:'instagram_publish_unresolved'});return;}publishing=true;attempt={state:'reserved',payloadHash:body.approvalReceiptHash,startedAtMs:now(),startedAt:new Date(now()).toISOString(),containerId:null,mediaId:null};await attempts.set(key,attempt);try{const form=new URLSearchParams({image_url:manifest.imageUrl,caption:manifest.caption,alt_text:manifest.altText,access_token:saved.accessToken}),created=await api('https://graph.instagram.com/v26.0/'+record.userId+'/media',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form}),containerId=typeof created?.id==='string'?created.id:null;if(!containerId)throw new Error();attempt={...attempt,state:'container_created',containerId};await attempts.set(key,attempt);let ready=false;for(let i=0;i<12;i++){const u=new URL('https://graph.instagram.com/v26.0/'+containerId);u.searchParams.set('fields','status_code,status');u.searchParams.set('access_token',saved.accessToken);const check=await api(u);if(check.status_code==='FINISHED'){ready=true;break;}if(['ERROR','EXPIRED'].includes(check.status_code))throw new Error();await new Promise(resolve=>setTimeout(resolve,Math.min(5000,500*(i+1))));}if(!ready)throw new Error();const published=await api('https://graph.instagram.com/v26.0/'+record.userId+'/media_publish',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({creation_id:containerId,access_token:saved.accessToken})}),mediaId=typeof published?.id==='string'?published.id:null;if(!mediaId)throw new Error();attempt={...attempt,state:'submitted',mediaId};await attempts.set(key,attempt);const result=verifyMedia(await evidence(saved.accessToken,mediaId),manifest),verifiedAt=new Date(now()).toISOString();attempt={...attempt,state:'verified',result,verifiedAt};await attempts.set(key,attempt);json(res,200,{...result,verifiedAt,replayed:false});}catch{attempt={...attempt,state:attempt.mediaId?'submitted':'uncertain'};await attempts.set(key,attempt);json(res,409,{error:'instagram_publish_unresolved'});}finally{publishing=false;}return;}
    if(url.pathname==='/prepare'&&req.method==='POST'){if(pending?.phase==='connection_unresolved'){json(res,409,{error:'reconciliation_required'});return;}if(!configured){json(res,503,{error:'configuration_required'});return;}const body=await readBody(req,2048);if(!body||Object.keys(body).sort().join(',')!=='scope,username'||body.scope!==INSTAGRAM_SCOPE){json(res,422,{error:'invalid_request'});return;}const expected=username(body.username);if(expected!=='jamesaucreates'){json(res,422,{error:'invalid_identity'});return;}if(record){json(res,409,{error:'account_already_connected'});return;}if(pending&&pending.expires>now()&&!['connection_failed','interrupted','complete'].includes(pending.phase)){json(res,409,{error:'signin_already_pending'});return;}const flow=randomBytes(32).toString('hex'),ticket=randomBytes(32).toString('hex');await persist({username:expected,flow,expires:now()+TTL,phase:'awaiting_private_signin',ticketHash:digest(ticket)});json(res,200,{beginPath:'/begin/'+ticket});return;}
    json(res,404,{error:'operation_unavailable'});
  }catch(error){const code=error?.message==='request_too_large'?413:500;if(!res.headersSent)json(res,code,{error:code===413?'request_too_large':'connection_operation_failed'});else res.end();}});
  return {server,status};
}
