import http from 'node:http';
import {createHash,randomBytes,timingSafeEqual} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {privateStore} from './private-store.mjs';

export const LINKEDIN_SCOPE='openid profile email w_member_social';
export const LINKEDIN_REDIRECT_URI='http://127.0.0.1:4321/callback';
const TTL=10*60*1000;
const digest=v=>createHash('sha256').update(v).digest('hex');
const eq=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
const opaque=v=>typeof v==='string'&&v.length>0&&v.length<=16384&&!/[\s\x00-\x1f]/.test(v);
const email=v=>typeof v==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)?v.toLowerCase():null;
const exactScope=v=>typeof v==='string'&&(()=>{const a=v.trim().split(/[,\s]+/).filter(Boolean),e=LINKEDIN_SCOPE.split(' ');return a.length===e.length&&e.every(x=>a.includes(x));})();
const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer'});res.end(JSON.stringify(value));};
const redirect=(res,to,cookie)=>{res.writeHead(303,{Location:to,'Cache-Control':'no-store','Referrer-Policy':'no-referrer',...(cookie?{'Set-Cookie':cookie}:{})});res.end();};
const getCookie=(header,name)=>typeof header==='string'?header.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)??null:null;
const safeJson=async response=>{const text=await response.text();if(text.length>1024*1024)throw new Error('response_too_large');return JSON.parse(text);};
const canonical=value=>JSON.stringify(value,Object.keys(value).sort());
const receiptHash=value=>'sha256:'+createHash('sha256').update(canonical(value)).digest('hex');

export async function createLinkedInBroker({port,studioPort,root,capability,clientId,clientSecret,fetchApi=fetch,now=Date.now,allowEphemeralPort=false}){
 if((port!==4321&&!(allowEphemeralPort===true&&port===0))||studioPort!==4310||typeof capability!=='string'||capability.length<40)throw new Error('invalid_configuration');
 const keychain=account=>{try{return execFileSync('/usr/bin/security',['find-generic-password','-s','James Au Studio LinkedIn OAuth','-a',account,'-w'],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:5000}).replace(/\n$/,'');}catch{return null;}};
 if(!opaque(clientId))clientId=keychain('client-id');
 if(!opaque(clientSecret))clientSecret=keychain('client-secret');
 const configured=opaque(clientId)&&opaque(clientSecret),store=await privateStore(root),control=store('linkedin-control'),tokens=store('linkedin-tokens');
 let record=await control.get('identity'),pending=await control.get('pending'),checking=false;
 const scheduled=store('linkedin-scheduled');
 const routeTests=store('linkedin-publications');
 const verifiedRouteTest=await routeTests.get('linkedin-route-test-2026-09-14-v1');
 if(record&&verifiedRouteTest?.state==='published'&&record.publishReady!==true){record={...record,publishReady:true};await control.set('identity',record);}
 const persist=async v=>{pending=v;await control.set('pending',v);};
 const expired=()=>!record||Date.parse(record.expiresAt)<=now();
 const futureDate=value=>{const parsed=typeof value==='string'?Date.parse(value):NaN;return Number.isFinite(parsed)&&parsed>now()+60*1000?new Date(parsed).toISOString():null;};
 const base=()=>({provider:'linkedin',available:!!configured||!!record,state:'configuration_required',email:null,subject:null,name:null,profileUrl:null,scope:LINKEDIN_SCOPE,route:'official_api',routeDriver:'linkedin_oauth2_posts_api',sessionState:'not_established',verifiedAt:null,expiresAt:null,identitySignals:[],publicationPolicy:'exact_post_approval_required',publishReady:false,publishing:false,schedulingAvailable:false});
 const status=()=>!configured?base():pending?.phase&&pending.phase!=='complete'?{...base(),state:pending.phase}:record?{...base(),...record,state:expired()?'needs_reauthorization':'connected_identity',schedulingAvailable:!expired()&&record.publishReady===true}:base();
 const tokenRequest=async body=>{const response=await fetchApi('https://www.linkedin.com/oauth/v2/accessToken',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Cache-Control':'no-store'},body:new URLSearchParams(body)});if(!response.ok)throw new Error('token_exchange_failed');const token=await safeJson(response);if(!opaque(token?.access_token)||String(token.token_type).toLowerCase()!=='bearer'||!Number.isInteger(token.expires_in)||token.expires_in<=0)throw new Error('invalid_token');if(token.scope&&!exactScope(token.scope))throw new Error('scope_mismatch');return token;};
 const identity=async(accessToken,expectedEmail)=>{const response=await fetchApi('https://api.linkedin.com/v2/userinfo',{headers:{Authorization:`Bearer ${accessToken}`,'Cache-Control':'no-store'}});if(!response.ok)throw new Error('identity_failed');const data=await safeJson(response),actual=email(data?.email),subject=opaque(data?.sub)?data.sub:null,name=typeof data?.name==='string'&&data.name.length<=160?data.name:null;if(!actual||actual!==expectedEmail||data.email_verified!==true||!subject||!name)throw new Error('identity_mismatch');return {email:actual,subject,name,profileUrl:'https://www.linkedin.com/in/james-au-305b3b436/',scope:LINKEDIN_SCOPE,route:'official_api',routeDriver:'linkedin_oauth2_posts_api',sessionState:'oauth_token_active',verifiedAt:new Date(now()).toISOString(),expiresAt:null,identitySignals:['oidc_verified_email_and_subject','signed_in_profile_name_and_canonical_url'],publicationPolicy:'exact_post_approval_required',publishReady:false,publishing:false};};
 const save=async(token,expectedEmail)=>{const next=await identity(token.access_token,expectedEmail);next.expiresAt=new Date(now()+token.expires_in*1000).toISOString();await tokens.set('identity',{accessToken:token.access_token,expiresAt:next.expiresAt,scope:LINKEDIN_SCOPE});await control.set('identity',next);record=next;};
 const loadJobs=async()=>{const value=await scheduled.get('jobs');return Array.isArray(value)?value:[];};
 const saveJobs=jobs=>scheduled.set('jobs',jobs);
 const submitText=async text=>{const saved=await tokens.get('identity');if(!saved||!opaque(saved.accessToken)||!record||expired())throw new Error('identity_not_connected');const response=await fetchApi('https://api.linkedin.com/rest/posts',{method:'POST',headers:{Authorization:`Bearer ${saved.accessToken}`,'Content-Type':'application/json','Linkedin-Version':'202509','X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify({author:`urn:li:person:${record.subject}`,commentary:text,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false})});if(!response.ok)throw new Error('publish_failed');const postId=response.headers.get('x-restli-id');if(!opaque(postId)||!/^urn:li:(share|ugcPost):[0-9]+$/.test(postId))throw new Error('missing_post_id');return {postId,url:`https://www.linkedin.com/feed/update/${postId}/`,verifiedAt:new Date(now()).toISOString()};};
 const runDue=async()=>{if(!record||expired())return;const jobs=await loadJobs(),due=jobs.find(job=>job?.state==='scheduled'&&Date.parse(job.scheduledAt)<=now());if(!due)return;due.state='submitting';await saveJobs(jobs);try{const result=await submitText(due.text);Object.assign(due,{...result,state:'delivery_unverified'});}catch{due.state='unresolved';}await saveJobs(jobs);};
 const timer=setInterval(()=>{void runDue().catch(()=>{});},15000);timer.unref?.();
 const server=http.createServer(async(req,res)=>{try{const address=server.address(),activePort=typeof address==='object'&&address?address.port:port;if(![`127.0.0.1:${activePort}`,`localhost:${activePort}`].includes(req.headers.host)){json(res,403,{error:'invalid_host'});return;}const url=new URL(req.url,`http://127.0.0.1:${activePort}`);
  if(url.pathname==='/callback'&&req.method==='GET'){const allowed=new Set(['state','code','error','error_description']);if(!pending||pending.phase!=='private_handoff'||pending.expires<=now()||[...url.searchParams.keys()].some(k=>!allowed.has(k)||url.searchParams.getAll(k).length!==1)){json(res,400,{error:'callback_not_expected'});return;}const selected=pending;await persist({...selected,phase:'verifying',ticketHash:null,browserHash:null});let started=false;try{const code=url.searchParams.get('code');if(url.searchParams.get('error')||!eq(url.searchParams.get('state'),selected.flow)||!opaque(code))throw new Error();started=true;const token=await tokenRequest({grant_type:'authorization_code',code,redirect_uri:LINKEDIN_REDIRECT_URI,client_id:clientId,client_secret:clientSecret});await save(token,selected.email);await persist({...selected,phase:'complete',ticketHash:null,browserHash:null});}catch{await persist({...selected,phase:started?'connection_unresolved':'connection_failed',ticketHash:null,browserHash:null});}redirect(res,`http://127.0.0.1:${studioPort}/connection-return`);return;}
  if(url.pathname.startsWith('/begin/')&&req.method==='GET'){const ticket=url.pathname.slice(7);if(!pending||pending.phase!=='awaiting_private_signin'||pending.expires<=now()||!eq(digest(ticket),pending.ticketHash)){json(res,410,{error:'signin_expired'});return;}const authorize=new URL('https://www.linkedin.com/oauth/v2/authorization');for(const [k,v] of Object.entries({response_type:'code',client_id:clientId,redirect_uri:LINKEDIN_REDIRECT_URI,state:pending.flow,scope:LINKEDIN_SCOPE}))authorize.searchParams.set(k,v);await persist({...pending,phase:'private_handoff',ticketHash:null,browserHash:null});redirect(res,authorize.toString());return;}
  if(!eq(req.headers['x-studio-broker'],capability)){json(res,403,{error:'broker_access_denied'});return;}
  if(url.pathname==='/status'&&req.method==='GET'){json(res,200,status());return;}
  if(url.pathname==='/scheduled'&&req.method==='GET'){json(res,200,{jobs:await loadJobs()});return;}
  if(url.pathname==='/prepare'&&req.method==='POST'){if(!configured){json(res,503,{error:'configuration_required'});return;}let raw='';for await(const c of req){raw+=c;if(raw.length>2048){json(res,413,{error:'request_too_large'});return;}}let body;try{body=JSON.parse(raw);}catch{json(res,422,{error:'invalid_request'});return;}const expected=email(body?.email);if(!expected||expected!=='jamesaucreates@gmail.com'||body.scope!==LINKEDIN_SCOPE||Object.keys(body).sort().join(',')!=='email,scope'){json(res,422,{error:'invalid_identity'});return;}if(record&&!expired()){json(res,409,{error:'account_already_connected'});return;}const flow=randomBytes(32).toString('hex'),ticket=randomBytes(32).toString('hex');await persist({email:expected,flow,expires:now()+TTL,phase:'awaiting_private_signin',ticketHash:digest(ticket)});json(res,200,{beginPath:`/begin/${ticket}`});return;}
  if(url.pathname==='/verify'&&req.method==='POST'){if(!record){json(res,409,{error:'identity_not_connected'});return;}if(checking){json(res,409,{error:'verification_in_progress'});return;}checking=true;try{const saved=await tokens.get('identity');if(!saved||expired())throw new Error();const next=await identity(saved.accessToken,record.email);next.expiresAt=saved.expiresAt;await control.set('identity',next);record=next;}catch{}finally{checking=false;}json(res,200,status());return;}
  if(url.pathname==='/schedule-preview'&&req.method==='POST'){if(!record||expired()){json(res,409,{error:'identity_not_connected'});return;}let raw='';for await(const c of req){raw+=c;if(raw.length>4096){json(res,413,{error:'request_too_large'});return;}}let body;try{body=JSON.parse(raw);}catch{json(res,422,{error:'invalid_request'});return;}const scheduledAt=futureDate(body?.scheduledAt),text=typeof body?.text==='string'?body.text.trim():'';if(Object.keys(body||{}).sort().join(',')!=='scheduledAt,text'||!scheduledAt||!text||text.length>3000){json(res,422,{error:'invalid_schedule'});return;}const manifest={account:'James Au',destination:'https://www.linkedin.com/in/james-au-305b3b436/',text,visibility:'PUBLIC',scheduledAt,media:[],derivatives:[]};json(res,200,{manifest,approvalReceiptHash:receiptHash(manifest)});return;}
  if(url.pathname==='/schedule-text'&&req.method==='POST'){if(!record||expired()){json(res,409,{error:'identity_not_connected'});return;}let raw='';for await(const c of req){raw+=c;if(raw.length>8192){json(res,413,{error:'request_too_large'});return;}}let body;try{body=JSON.parse(raw);}catch{json(res,422,{error:'invalid_request'});return;}const scheduledAt=futureDate(body?.scheduledAt),text=typeof body?.text==='string'?body.text.trim():'';if(!body||Object.keys(body).sort().join(',')!=='approvalReceiptHash,idempotencyKey,publicationConsent,scheduledAt,text'||!scheduledAt||!text||text.length>3000||!opaque(body.idempotencyKey)||body.publicationConsent!==true){json(res,422,{error:'invalid_schedule'});return;}const manifest={account:'James Au',destination:'https://www.linkedin.com/in/james-au-305b3b436/',text,visibility:'PUBLIC',scheduledAt,media:[],derivatives:[]};if(body.approvalReceiptHash!==receiptHash(manifest)){json(res,422,{error:'exact_schedule_approval_required'});return;}const jobs=await loadJobs(),prior=jobs.find(job=>job.idempotencyKey===body.idempotencyKey);if(prior){json(res,200,{...prior,replayed:true});return;}const job={idempotencyKey:body.idempotencyKey,state:'scheduled',text,scheduledAt,approvalReceiptHash:body.approvalReceiptHash,createdAt:new Date(now()).toISOString(),postId:null,url:null,verifiedAt:null};jobs.push(job);await saveJobs(jobs);json(res,200,{...job,replayed:false});return;}
  if(url.pathname==='/publish-text'&&req.method==='POST'){if(!record||expired()){json(res,409,{error:'identity_not_connected'});return;}let raw='';for await(const c of req){raw+=c;if(raw.length>4096){json(res,413,{error:'request_too_large'});return;}}let body;try{body=JSON.parse(raw);}catch{json(res,422,{error:'invalid_request'});return;}const approvedText='Testing the LinkedIn connection for James Au Studio. This post was reviewed and sent through my local approval workflow.',approvedHash='sha256:8a311cb35fe270fc880e24b3fa6319c48f338b39711e3a12e5b0c436cbbc67df';if(!body||body.text!==approvedText||body.approvalReceiptHash!==approvedHash||body.publicationConsent!==true||!opaque(body.idempotencyKey)||Object.keys(body).sort().join(',')!=='approvalReceiptHash,idempotencyKey,publicationConsent,text'){json(res,422,{error:'exact_publish_approval_required'});return;}const publications=store('linkedin-publications'),prior=await publications.get(body.idempotencyKey);if(prior?.state==='published'){record={...record,publishReady:true};await control.set('identity',record);json(res,200,{...prior,replayed:true});return;}if(prior){json(res,409,{error:'publication_unresolved'});return;}await publications.set(body.idempotencyKey,{state:'submitting',approvalReceiptHash:approvedHash});const saved=await tokens.get('identity');try{const response=await fetchApi('https://api.linkedin.com/rest/posts',{method:'POST',headers:{Authorization:`Bearer ${saved.accessToken}`,'Content-Type':'application/json','Linkedin-Version':'202509','X-Restli-Protocol-Version':'2.0.0'},body:JSON.stringify({author:`urn:li:person:${record.subject}`,commentary:approvedText,visibility:'PUBLIC',distribution:{feedDistribution:'MAIN_FEED',targetEntities:[],thirdPartyDistributionChannels:[]},lifecycleState:'PUBLISHED',isReshareDisabledByAuthor:false})});if(!response.ok)throw new Error('publish_failed');const postId=response.headers.get('x-restli-id');if(!opaque(postId)||!/^urn:li:(share|ugcPost):[0-9]+$/.test(postId))throw new Error('missing_post_id');const result={state:'published',postId,url:`https://www.linkedin.com/feed/update/${postId}/`,text:approvedText,account:'James Au',verifiedAt:new Date(now()).toISOString(),approvalReceiptHash:approvedHash};await publications.set(body.idempotencyKey,result);record={...record,publishReady:true};await control.set('identity',record);json(res,200,{...result,replayed:false});}catch{await publications.set(body.idempotencyKey,{state:'unresolved',approvalReceiptHash:approvedHash});json(res,502,{error:'publication_unresolved'});}return;}
  json(res,404,{error:'operation_unavailable'});
 }catch{if(!res.headersSent)json(res,500,{error:'connection_operation_failed'});else res.end();}});server.on('close',()=>clearInterval(timer));return {server,status};
}
