import {useState, type ReactNode} from 'react';
import type {AlphaState, GraphNode, Profile, Snapshot, Template} from './types';
import './you.css';
import {Artwork,Plan} from './Phase2';

const SECTIONS=['Overview','Voice & Knowledge','Skills & Learning','Usage & Plan','Account & Privacy'];
const evidence:Record<string,string>={user_confirmed:'Confirmed by you',observed_in_approved_example:'Supported by an approved example',agent_proposed_needs_confirmation:'Agent proposal · needs review',conflicting:'Conflicting · needs review',unknown:'Unknown · optional'};
const privacy:Record<string,string>={public:'May inform public drafts',private:'Private interaction guidance',local_only:'Locked · this device only',workspace_only:'Workspace context only',excluded:'Excluded'};
type Props={state:AlphaState;profile?:Profile;templates:Template[];busy:boolean;act:(a:string,p?:Record<string,unknown>)=>Promise<Snapshot|undefined>;review:(fieldId?:string)=>void;openSkills:()=>void;exportProfile:()=>Promise<void>;account:ReactNode};

function download(name:string,body:string,type:string){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export default function YouProfile({state,profile,templates,busy,act,review,openSkills,exportProfile,account}:Props){
  const [section,setSection]=useState('Overview');
  const [asList,setAsList]=useState(false);
  const [selected,setSelected]=useState<GraphNode|null>(null);
  const [identity,setIdentity]=useState(state.you?.identitySentence||'');
  const [editingIdentity,setEditingIdentity]=useState(false);
  const [compare,setCompare]=useState(String(state.speaker.activeRevision||1));
  const v=state.profileVisuals;
  const revision=state.speaker.activeRevision;
  const compared=state.speaker.revisions.find(r=>String(r.revision)===compare);
  const mode={personal:'Personal Brand',niche:'Role Specific',business:'Business',hybrid:'Hybrid'}[state.brandHub.mode||'personal'];
  function choose(id:string){setSection(id);setSelected(null);}
  function selectNode(node:GraphNode){setSelected(node);requestAnimationFrame(()=>document.getElementById('node-detail-title')?.focus({preventScroll:false}));}
  const groupedList=<div className="constellation-list">{v?.groups.map(g=><section key={g.id}><h3>{g.label}</h3>{g.nodes.length?<ul>{g.nodes.map(n=><li key={n.id}><button className="profile-list-node" data-profile-node={n.id} onClick={()=>selectNode(n)}><strong>{n.short_description}</strong><span>{evidence[n.evidence_state]||n.evidence_state} · {privacy[n.privacy_state]} · {n.source_ids.length} source reference{n.source_ids.length===1?'':'s'}</span></button></li>)}</ul>:<p className="helper">Not supplied · optional · no trait inferred</p>}</section>)}</div>;
  const details=selected&&<aside className="node-detail" aria-label="Selected profile statement"><div className="eyebrow">YOUR APPROVED STATEMENT</div><h3 id="node-detail-title" tabIndex={-1}>{selected.label}</h3><p className="exact-statement">{selected.short_description}</p><dl><dt>Evidence</dt><dd>{evidence[selected.evidence_state]||selected.evidence_state}</dd><dt>Privacy</dt><dd>{privacy[selected.privacy_state]}</dd><dt>Source references</dt><dd>{selected.source_ids.join(', ')||'No source reference supplied'}</dd><dt>Profile version</dt><dd>Revision {selected.profile_revision_id}</dd></dl><button className="button secondary" onClick={()=>review(selected.id)}>Review or edit this field →</button><p className="helper">Approve, edit, reject, keep unknown, or exclude this value in the field review step. The active revision changes only after your review.</p><button className="text-button" onClick={()=>setSelected(null)}>Close statement</button></aside>;
  return <div className="you-page"><header className="section-heading you-heading"><div><div className="eyebrow">YOUR VOICE. YOUR CHOICES.</div><h1 id="main-title" tabIndex={-1}>You</h1></div><p className="lede">A living picture of what you’ve chosen to share.</p></header>
    <div className="you-tabs" role="tablist" aria-label="Your profile sections">{SECTIONS.map((name,i)=><button key={name} id={`you-tab-${i}`} role="tab" aria-selected={section===name} aria-controls="you-panel" tabIndex={section===name?0:-1} onClick={()=>choose(name)} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?4:(i+(e.key==='ArrowRight'?1:-1)+5)%5;choose(SECTIONS[next]);document.getElementById(`you-tab-${next}`)?.focus();}}}>{name}</button>)}</div>
    <details className="you-jump"><summary>Jump to a profile section</summary><nav aria-label="Profile section links">{SECTIONS.map(name=><a key={name} href="#you-panel" onClick={()=>choose(name)}>{name}</a>)}</nav></details>
    <section id="you-panel" role="tabpanel" aria-labelledby={`you-tab-${SECTIONS.indexOf(section)}`} tabIndex={-1}>
    {section==='Overview'&&<>
      <section className={`you-hero ${!state.phase2?.art.selected&&state.you?.artwork?.state==='removed'?'art-removed':''}`} aria-label="A visual interpretation of your voice">{v&&(state.phase2?.art.selected||state.you?.artwork?.state!=='removed')&&<img className="watercolor-wash" style={state.phase2?.art.selected?{objectPosition:`${(state.phase2.art.selected.focal?.[0]??.5)*100}% ${(state.phase2.art.selected.focal?.[1]??.5)*100}%`}:undefined} src={state.phase2?.art.selected?`data:${state.phase2.art.selected.mime};base64,${state.phase2.art.selected.data}`:`data:image/svg+xml;charset=utf-8,${encodeURIComponent(v.artworkSvg)}`} alt="" aria-hidden="true"/>}<div className="hero-scrim"><div className="eyebrow">INSPIRED BY CHOICES YOU APPROVED</div><h2>{state.speaker.label}</h2>{editingIdentity?<form onSubmit={e=>{e.preventDefault();void act('you_identity',{value:identity}).then(r=>{if(r)setEditingIdentity(false);});}}><label className="field">Your identity sentence<textarea maxLength={240} rows={2} value={identity} onChange={e=>setIdentity(e.target.value)}/></label><button className="button" disabled={busy}>Save identity sentence</button></form>:<><p className="identity-sentence">{state.you?.identitySentence||'Your point of view, still taking shape.'}</p><button className="text-button" onClick={()=>setEditingIdentity(true)}>Edit identity sentence</button></>}<p className="hero-meta">{mode} · {revision?`Profile revision ${revision}`:'Profile not yet approved'} · {v?.approvedAt?new Date(v.approvedAt).toLocaleDateString():'No approval date'}</p><div className="button-row"><button className="button" onClick={()=>review()}>Edit what PostRiff knows ↗</button><button className="button secondary" disabled={busy} onClick={()=>void act('you_art_refresh')}>Refresh local wash</button></div></div><span className="art-caption">Local procedural watercolor · no image model</span></section>
      <p className="art-helper">This artwork is an interpretation, not a personality test. You can see what shaped it, change those choices, or remove it. This alpha’s wash is a decorative fallback, independent of your private profile.</p>
      <details className="art-brief"><summary>Inspect ArtBrief & artwork controls</summary><h3>What may shape a future artwork?</h3><p>Only selected, approved public fields can contribute allowlisted abstract words. Names, private fields, quotations, source text and account details stay out. No prompt is sent anywhere.</p>{v?.artEligibleFields.length?v.artEligibleFields.map(f=><label className="scope-check" key={f.id}><input type="checkbox" disabled={busy} checked={state.you?.artFieldIds.includes(f.id)||false} onChange={e=>void act('you_art_scope',{fieldIds:e.target.checked?[...(state.you?.artFieldIds||[]),f.id]:(state.you?.artFieldIds||[]).filter(id=>id!==f.id)})}/>Include approved {f.label}</label>):<p className="helper">No image-eligible public fields selected. Your private/local fields stay private. The paper-and-watercolor fallback remains available.</p>}<pre aria-label="Privacy-safe ArtBrief">{JSON.stringify(v?.artBrief||{status:'insufficient_approved_context'},null,2)}</pre><p className="helper">Current wash: {state.you?.artwork?.state||'default local fallback'} · {state.you?.artwork?.profileRevisionId?`selected at profile r${state.you.artwork.profileRevisionId}`:'no personal profile used'} · Consent to an image model: not requested. No managed images used.</p><div className="button-row"><button className="button secondary" disabled={!v||state.you?.artwork?.state==='removed'} onClick={()=>v&&download('postriff-local-watercolor.svg',v.artworkSvg,'image/svg+xml')}>Download local wash</button><button className="text-button danger" disabled={busy} onClick={()=>void act('you_art_remove')}>Remove artwork</button></div></details>
      {state.phase2&&<Artwork state={state} busy={busy} act={act}/>}
      <div className="profile-status-grid"><div><span>Ready to use</span><strong>{v?.nodes.length?'Approved information available':'Start with a few answers'}</strong></div><div><span>Needs your review</span><strong>{v?.needsReview||0} pending suggestions</strong></div><div><span>Still open</span><strong>{v?.unknown||0} optional fields</strong></div><div><span>Private by default</span><strong>This workspace stays local</strong></div></div>
      <div className="constellation-heading"><div><div className="eyebrow">CONNECTED BY YOUR APPROVAL</div><h2>Voice Constellation</h2><p>Your active speaker and the context you’ve approved.</p></div><button className="button secondary" aria-pressed={asList} onClick={()=>setAsList(!asList)}>{asList?'View as constellation':'View as list'}</button></div>
      {asList?groupedList:<div className="constellation-map" aria-label="Approved profile constellation"><svg viewBox="0 0 900 600" preserveAspectRatio="none" aria-hidden="true">{[[150,100],[450,100],[750,100],[150,300],[750,300],[150,500],[450,500],[750,500]].map(([x,y],i)=><path key={i} d={`M450 300 Q${450+(x-450)*.5} ${y} ${x} ${y}`}/>)}</svg><div className="constellation-center"><span aria-hidden="true">✳</span><strong>{v?.center.label||state.speaker.label}</strong><small>Active speaker · r{revision||'—'}</small></div>{v?.groups.map((g,i)=><div className={`constellation-cluster cluster-${i} ${g.nodes.length?'confirmed':'unknown'}`} key={g.id}><h3>{g.label}</h3>{g.nodes.length?g.nodes.map(n=><button key={n.id} data-profile-node={n.id} className={n.evidence_state==='observed_in_approved_example'?'example-supported':''} onClick={()=>selectNode(n)}><span>{n.short_description}</span><small>{evidence[n.evidence_state]||n.evidence_state} · {privacy[n.privacy_state]} · {n.source_ids.length} refs</small></button>):<p>Not supplied<br/><small>Unknown · optional</small></p>}</div>)}</div>}
      <p className="helper constellation-legend">Solid outline: confirmed · double outline: approved example · hollow outline: optional context. Agent proposals and conflicts stay in review and never become approved nodes automatically.</p>{details}
      <div className="you-two-column"><section><h2>What you’re working toward</h2><p>{state.brandHub.purpose||'No goal approved yet.'}</p><h3>In your own terms</h3><p>{profile?.observations.join(' · ')||'Your preferred wording will appear after review.'}</p><p className="helper">No personality, authenticity, intelligence, or completeness score.</p></section><section><h2>Recent changes</h2><ol className="voice-timeline">{state.speaker.revisions.slice(-4).reverse().map(r=><li key={r.revision}><strong>Voice r{r.revision}</strong><span>{r.reason}</span></li>)}{state.you?.events.slice(-2).reverse().map((e,i)=><li key={`art-${i}`}><strong>{e.action.replaceAll('you_','').replaceAll('_',' ')}</strong><span>Local change · profile r{e.profileRevision}</span></li>)}</ol></section></div>
    </>}
    {section==='Voice & Knowledge'&&<><h2>What PostRiff knows, with your approval</h2><p>Structured records are the source of truth. Review a field to change its use or privacy.</p>{groupedList}{details}<h2>What PostRiff will never assume</h2><ul>{profile?.unknowns.map((u,i)=><li key={i}>{u}</li>)}</ul><p>No health, identity, life experience, credential or optional self-description is inferred. Unknown and excluded values do not become facts.</p><div className="button-row"><button className="button" onClick={()=>review()}>Review suggestions and unknowns →</button><button className="button secondary" disabled={busy||!profile?.fields} onClick={()=>void exportProfile()}>Export Personal Voice Package</button></div></>}
    {section==='Skills & Learning'&&<><h2>All released PostRiff skills included</h2><p>Every plan and trial shares the same neutral templates. Your overrides belong to this workspace.</p><div className="you-skills">{templates.map(t=><article key={t.id}><h3>{t.name}</h3><p>{t.description}</p><small>Template v{t.version} · private configuration · {t.dependencies.join(', ')||'no external dependency'}</small><p className="helper">Reads approved profile and source references. {state.skillInstances.find(i=>i.templateId===t.id)?.overrides&&JSON.stringify(state.skillInstances.find(i=>i.templateId===t.id)?.overrides)} · no template conflict reported.</p></article>)}</div><button className="button secondary" onClick={openSkills}>Configure my skill instances →</button><h2>Learning decisions</h2>{state.preferences.length?<ul>{state.preferences.map(p=><li key={p.id}>{p.label} <strong>{p.status}</strong>{['remembered','post-only','rejected'].includes(p.status)&&<button className="text-button" disabled={busy} onClick={()=>void act('preference',{preferenceId:p.id,decision:'undo'})}>Undo decision</button>}{p.status==='remembered'&&<button className="text-button danger" disabled={busy} onClick={()=>void act('preference',{preferenceId:p.id,decision:'delete'})}>Delete remembered preference</button>}</li>)}</ul>:<p>No preferences proposed yet.</p>}<h2>Compare approved voice revisions</h2><label className="field narrow">Earlier voice revision<select value={compare} onChange={e=>setCompare(e.target.value)}>{state.speaker.revisions.map(r=><option key={r.revision} value={r.revision}>Revision {r.revision} · {r.reason}</option>)}</select></label><div className="you-two-column"><section><h3>Selected revision {compare}</h3><p>{compared?.profile.observations.join(' · ')}</p><p>{compared?.profile.preferences.length||0} remembered preferences</p></section><section><h3>Current revision {revision}</h3><p>{profile?.observations.join(' · ')}</p><p>{profile?.preferences.length||0} remembered preferences</p></section></div><button className="button secondary" disabled={busy||Number(compare)===revision} onClick={()=>void act('you_restore_voice',{revision:Number(compare)})}>Restore as a new voice revision</button><p className="helper">History is retained. Existing drafts require review after restoring a profile.</p></>}
    {section==='Usage & Plan'&&state.phase2&&<Plan state={state} busy={busy} act={act}/>}
    {section==='Usage & Plan'&&!state.phase2&&<><span className="tag">Fixture / local state · no billing</span><h2>A clear view of what runs here.</h2><p>All released PostRiff skills included. No subscription, trial, renewal, paid allowance, or overage is active.</p><div className="usage-grid">{[['Managed writing','0 requests','Not enabled · no included allowance'],['Managed images','0 generations','Not enabled · local wash only'],['Local storage',`${v?.storageBytes.toLocaleString()||0} bytes`,'Current workspace JSON · cloud allowance unavailable'],['External-agent runs','0 executed','Prepared requests are not executed jobs'],['Local fixture runs',`${state.runs.length} records`,'No model credits consumed'],['Workspace & membership','1 workspace · 1 owner','Local preview · commercial limits unavailable']].map(([label,value,detail])=><section key={label}><span>{label}</span><strong>{value}</strong><p>{detail}</p></section>)}</div><p>Managed spending cap: no paid execution allowed. Failed fixture jobs incur no charge; refunds and plan changes are not applicable.</p><button className="button secondary" disabled>Billing unavailable in this alpha</button></>}
    {section==='Account & Privacy'&&<>{account}<section className="settings-section"><h2>Profile artwork</h2><p>Local procedural asset only. Image-provider consent has not been requested. No private profile has been sent to an image model.</p><button className="button secondary" onClick={()=>choose('Overview')}>Inspect the local ArtBrief →</button></section></>}
    </section></div>;
}
