import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import net from 'node:net';
import {createPinterestBroker,PINTEREST_SCOPE} from '../pinterest-broker.mjs';

const identity={username:'jamesaucreates',scope:PINTEREST_SCOPE};
const freePort=()=>new Promise((resolve,reject)=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const {port}=server.address();server.close(error=>error?reject(error):resolve(port));});});
async function fixture(t,options={}){
 const root=await fs.mkdtemp(path.join(process.cwd(),'.pinterest-broker-')),port=4317,studioPort=await freePort(),capability='a'.repeat(64),calls=[];let clock=Date.now();
 const token={access_token:'pina-synthetic-access',refresh_token:'pinr-synthetic-refresh',token_type:'bearer',expires_in:3600,scope:PINTEREST_SCOPE,...options.token};
 const user={id:'fixture-account-id',username:identity.username,account_type:'BUSINESS',...options.user};
 const fetchApi=async(url,init={})=>{calls.push({url:String(url),method:init.method||'GET',headers:init.headers,body:init.body});if(options.fail)throw new Error('SYNTHETIC_PRIVATE_ERROR');return Response.json(String(url).includes('/oauth/token')?token:user);};
 const config={root,port,studioPort,capability,clientId:options.configured===false?null:'fixture-client',clientSecret:options.configured===false?null:'x'.repeat(20),fetchApi,now:()=>clock};
 const broker=await createPinterestBroker(config);await new Promise(resolve=>broker.server.listen(port,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>broker.server.close(resolve)));t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const request=(p,o={})=>fetch(`http://127.0.0.1:${port}${p}`,{...o,redirect:'manual',headers:{'X-Studio-Broker':capability,...o.headers}});
 return {root,broker,request,calls,token,user,config,advance:ms=>{clock+=ms;}};
}
async function begin(f){const prepared=await f.request('/prepare',{method:'POST',body:JSON.stringify(identity)});assert.equal(prepared.status,200);const beginPath=(await prepared.json()).beginPath;const redirect=await f.request(beginPath);assert.equal(redirect.status,303);const auth=new URL(redirect.headers.get('location'));return {beginPath,auth,cookie:redirect.headers.get('set-cookie').split(';')[0],callback:`/callback?state=${auth.searchParams.get('state')}&code=SYNTHETIC`};}
async function connect(f){const b=await begin(f);await f.request(b.callback,{headers:{Cookie:b.cookie}});return b;}

test('missing configuration fails closed',async t=>{const f=await fixture(t,{configured:false});assert.equal(f.broker.status().state,'configuration_required');assert.equal((await f.request('/prepare',{method:'POST',body:JSON.stringify(identity)})).status,503);assert.equal(f.calls.length,0);});
test('browser identity evidence records no OAuth credentials or publishing route',async t=>{const f=await fixture(t,{configured:false}),body={username:'jamesaucreates',identitySignals:['business_hub_name_and_handle','public_profile_name_and_handle']};const result=await f.request('/browser-connect',{method:'POST',body:JSON.stringify(body)});assert.equal(result.status,200);assert.equal((await result.json()).state,'connected_browser_identity');assert.equal(f.broker.status().routeDriver,'controlled_browser');assert.equal(f.broker.status().scope,'controlled_browser_session');assert.equal(f.calls.length,0);for(const path of ['/publish','/boards','/ads','/billing','/tokens'])assert.equal((await f.request(path,{method:'POST'})).status,404);});
test('exact account connects with only approved scopes and encrypted tokens',async t=>{const f=await fixture(t),b=await connect(f);assert.equal(f.broker.status().state,'connected_identity');assert.equal(f.broker.status().username,identity.username);assert.equal(f.broker.status().publishReady,false);assert.equal(b.auth.origin,'https://www.pinterest.com');assert.equal(b.auth.searchParams.get('scope'),PINTEREST_SCOPE);assert.equal(b.auth.searchParams.get('redirect_uri'),'http://127.0.0.1:4317/callback');assert.equal(f.calls.length,2);for(const name of await fs.readdir(f.root)){const bytes=await fs.readFile(path.join(f.root,name));assert.equal(bytes.includes(Buffer.from('pinr-synthetic-refresh')),false);}assert.equal(JSON.stringify(f.broker.status()).includes('synthetic-access'),false);});
for(const token of [{scope:PINTEREST_SCOPE+',ads:write'},{scope:'user_accounts:read,boards:read,pins:read'},{access_token:undefined},{refresh_token:undefined},{token_type:'invalid'}])test('malformed or expanded token fails closed '+JSON.stringify(token),async t=>{const f=await fixture(t,{token});await connect(f);assert.equal(f.broker.status().state,'connection_unresolved');assert.equal(f.broker.status().publishReady,false);});
for(const user of [{username:'otheraccount'},{id:undefined}])test('substituted account fails closed '+JSON.stringify(user),async t=>{const f=await fixture(t,{user});await connect(f);assert.equal(f.broker.status().state,'connection_unresolved');assert.equal(f.broker.status().accountId,null);});
test('callback requires a nonce, exact state, and can only be used once',async t=>{const f=await fixture(t),b=await begin(f);assert.equal((await f.request(b.callback)).status,400);assert.equal(f.calls.length,0);await f.request(b.callback,{headers:{Cookie:b.cookie}});assert.equal((await f.request(b.callback,{headers:{Cookie:b.cookie}})).status,400);assert.equal(f.calls.length,2);});
test('denied consent and unknown callback parameters never exchange a token',async t=>{const f=await fixture(t),b=await begin(f);assert.equal((await f.request(`/callback?state=${b.auth.searchParams.get('state')}&error=access_denied`,{headers:{Cookie:b.cookie}})).status,303);assert.equal(f.calls.length,0);const c=await begin(f);assert.equal((await f.request(c.callback+'&unexpected=value',{headers:{Cookie:c.cookie}})).status,400);assert.equal(f.calls.length,0);});
test('restart requires independent identity verification and has no write routes',async t=>{const f=await fixture(t);await connect(f);const restarted=await createPinterestBroker(f.config);assert.equal(restarted.status().state,'verification_required');assert.equal((await f.request('/publish',{method:'POST'})).status,404);assert.equal((await f.request('/boards',{method:'POST'})).status,404);assert.equal((await f.request('/pins/delete',{method:'POST'})).status,404);assert.equal((await f.request('/tokens',{method:'GET'})).status,404);});
