import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import http from 'node:http';
import {createHash} from 'node:crypto';
import {createTikTokBroker,TIKTOK_SCOPE} from '../tiktok-broker.mjs';
const identity={username:'fixture.james',scope:TIKTOK_SCOPE};
async function freePort(){const s=net.createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
async function fixture(t,options={}){
 const root=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'tiktok-broker-test-')));
 t.after(()=>fs.rm(root,{recursive:true,force:true}));
 const port=await freePort(),capability='a'.repeat(64),calls=[];let clock=Date.now();
 const token={access_token:'SYNTHETIC-ACCESS',refresh_token:'SYNTHETIC-REFRESH',open_id:'fixture-subject',token_type:'Bearer',expires_in:3600,scope:TIKTOK_SCOPE,...options.token};
 const user={open_id:'fixture-subject',username:identity.username,display_name:'Fixture James',...options.user};
 const fetchApi=async(url,init)=>{calls.push({url:String(url),method:init.method||'GET',body:init.body});if(options.fail)throw new Error('SYNTHETIC-PRIVATE-ERROR');return Response.json(String(url).includes('/oauth/token/')?token:{data:{user},error:{code:'ok'}});};
 const config={root,port,studioPort:4310,capability,clientKey:options.configured===false?null:'fixture-client',clientSecret:options.configured===false?null:'x'.repeat(20),fetchApi,now:()=>clock};
 const broker=await createTikTokBroker(config);await new Promise(r=>broker.server.listen(port,'127.0.0.1',r));t.after(()=>new Promise(r=>broker.server.close(r)));
 const request=(p,o={})=>fetch(`http://127.0.0.1:${port}${p}`,{...o,redirect:'manual',headers:{'X-Studio-Broker':capability,...o.headers}});
 return {root,port,broker,request,calls,token,user,config,advance:ms=>{clock+=ms;}};
}
async function begin(f){const p=await f.request('/prepare',{method:'POST',body:JSON.stringify(identity)});assert.equal(p.status,200);const prepared=await p.json();const r=await f.request(prepared.beginPath);assert.equal(r.status,303);const auth=new URL(r.headers.get('location'));return {callback:'/callback?state='+auth.searchParams.get('state')+'&code=SYNTHETIC',cookie:r.headers.get('set-cookie').split(';')[0],auth,beginPath:prepared.beginPath};}
async function connect(f){const b=await begin(f);await f.request(b.callback,{headers:{Cookie:b.cookie}});return b;}
test('unconfigured broker makes no external requests',async t=>{const f=await fixture(t,{configured:false});assert.equal(f.broker.status().state,'configuration_required');assert.equal((await f.request('/prepare',{method:'POST',body:JSON.stringify(identity)})).status,503);assert.equal(f.calls.length,0);});
test('exact identity, Desktop PKCE and encrypted persistence',async t=>{const f=await fixture(t),b=await connect(f);assert.equal(f.broker.status().state,'connected_identity');assert.equal(f.broker.status().username,identity.username);assert.equal(f.broker.status().publishReady,false);assert.deepEqual(f.broker.status().identitySignals,['oauth_subject','independent_user_info_username']);assert.equal(b.auth.origin,'https://www.tiktok.com');assert.equal(b.auth.searchParams.get('scope'),TIKTOK_SCOPE);assert.equal(b.auth.searchParams.get('code_challenge_method'),'S256');const verifier=f.calls[0].body.get('code_verifier');assert.match(verifier,/^[A-Za-z0-9._~-]{43,128}$/);assert.equal(b.auth.searchParams.get('code_challenge'),createHash('sha256').update(verifier).digest('hex'));assert.equal(f.calls[0].body.get('redirect_uri'),b.auth.searchParams.get('redirect_uri'));assert.equal(f.calls.length,2);for(const name of await fs.readdir(f.root)){const bytes=await fs.readFile(path.join(f.root,name));assert.equal(bytes.includes(Buffer.from('SYNTHETIC-REFRESH')),false);assert.equal((await fs.stat(path.join(f.root,name))).mode&0o077,0);}assert.equal(JSON.stringify(f.broker.status()).includes('SYNTHETIC'),false);});
for(const token of [{scope:TIKTOK_SCOPE+',video.publish'},{scope:'user.info.basic'},{scope:TIKTOK_SCOPE+',user.info.basic'},{access_token:undefined},{open_id:undefined},{expires_in:-1},{token_type:'Invalid'}])test('reject malformed token or scope '+JSON.stringify(token),async t=>{const f=await fixture(t,{token});await connect(f);assert.equal(f.broker.status().state,'connection_unresolved');assert.equal(f.broker.status().publishReady,false);assert.equal(f.calls.length,1);});
for(const user of [{username:'other.account'},{open_id:'other-subject'}])test('reject account substitution '+JSON.stringify(user),async t=>{const f=await fixture(t,{user});await connect(f);assert.equal(f.broker.status().state,'connection_unresolved');assert.equal(f.broker.status().openId,null);});
test('cookie, state and single-use callbacks',async t=>{const f=await fixture(t),b=await begin(f);assert.equal((await f.request(b.callback)).status,400);assert.equal(f.calls.length,0);assert.equal((await f.request(b.beginPath)).status,410);await f.request(b.callback,{headers:{Cookie:b.cookie}});assert.equal(f.broker.status().state,'connected_identity');assert.equal((await f.request(b.callback,{headers:{Cookie:b.cookie}})).status,400);assert.equal(f.calls.length,2);});
test('wrong state and denied consent never exchange a code',async t=>{const f=await fixture(t),b=await begin(f);await f.request('/callback?state=wrong&error=access_denied',{headers:{Cookie:b.cookie}});assert.equal(f.calls.length,0);assert.equal(f.broker.status().state,'connection_failed');});
test('callback rejects duplicated and unknown parameters before exchange',async t=>{const f=await fixture(t),b=await begin(f);for(const extra of ['&code=duplicate','&unexpected=value'])assert.equal((await f.request(b.callback+extra,{headers:{Cookie:b.cookie}})).status,400);assert.equal(f.calls.length,0);});
test('expiry is enforced',async t=>{const f=await fixture(t),b=await begin(f);f.advance(600001);assert.equal((await f.request(b.callback,{headers:{Cookie:b.cookie}})).status,400);assert.equal(f.calls.length,0);});
test('restart and expiry require fresh read-only verification',async t=>{const f=await fixture(t);await connect(f);const restarted=await createTikTokBroker(f.config);assert.equal(restarted.status().state,'verification_required');f.advance(3600001);assert.equal(f.broker.status().state,'verification_required');const r=await f.request('/verify',{method:'POST',body:'{}'});assert.equal((await r.json()).state,'connected_identity');assert.equal(f.calls.at(-2).body.get('grant_type'),'refresh_token');assert.equal(f.calls.filter(c=>c.url.includes('/token/')).length,2);});
test('ambiguous exchange cannot be repeated after timeout or restart',async t=>{const f=await fixture(t,{fail:true});await connect(f);f.advance(600001);assert.equal((await f.request('/prepare',{method:'POST',body:JSON.stringify(identity)})).status,409);assert.equal((await f.request('/verify',{method:'POST',body:'{}'})).status,409);const restarted=await createTikTokBroker(f.config);assert.equal(restarted.status().state,'connection_unresolved');assert.equal(f.calls.length,1);assert.equal(JSON.stringify(f.broker.status()).includes('PRIVATE'),false);});
test('concurrent prepare allows only one flow',async t=>{const f=await fixture(t);const rs=await Promise.all([f.request('/prepare',{method:'POST',body:JSON.stringify(identity)}),f.request('/prepare',{method:'POST',body:JSON.stringify(identity)})]);assert.deepEqual(rs.map(r=>r.status).sort(),[200,409]);});
test('unauthorized controls, bad host, public write and secret surfaces unavailable',async t=>{const f=await fixture(t);assert.equal((await f.request('/status',{headers:{'X-Studio-Broker':''}})).status,403);assert.equal(await new Promise((resolve,reject)=>{const req=http.request({hostname:'127.0.0.1',port:f.port,path:'/status',headers:{Host:'evil.example','X-Studio-Broker':'a'.repeat(64)}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();}),403);for(const p of ['/publish','/upload','/tokens'])assert.equal((await f.request(p,{method:'POST'})).status,404);assert.equal(f.calls.length,0);});
