import assert from 'node:assert/strict';
import { QueryClient, QueryObserver } from '@tanstack/react-query';
import { releaseCachedMedia } from '../src/lib/api/media.ts';
const client = new QueryClient();
const revoked = [];
const stop = releaseCachedMedia(client.getQueryCache(), url => revoked.push(url));
const key = ['media', 'synthetic-workspace', 'asset'];
client.setQueryData(key, 'blob:first');
const first = new QueryObserver(client, {queryKey:key, enabled:false});
const second = new QueryObserver(client, {queryKey:key, enabled:false});
const offFirst = first.subscribe(() => {});
const offSecond = second.subscribe(() => {});
offFirst();
assert.deepEqual(revoked, [], 'one thumbnail unmount must not revoke a shared URL');
client.setQueryData(key, 'blob:replacement');
await new Promise(resolve => setTimeout(resolve, 5));
assert.deepEqual(revoked, ['blob:first']);
assert.equal(second.getCurrentResult().data, 'blob:replacement');
offSecond();
client.removeQueries({queryKey:key});
await new Promise(resolve => setTimeout(resolve, 5));
assert.deepEqual(revoked, ['blob:first', 'blob:replacement']);
stop(); client.clear();
console.log('Media cache lifetime assertions passed');
