const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const read=(...p)=>fs.readFileSync(path.join(__dirname,'..','src',...p),'utf8');
test('Universal Library client exposes normalized file routes',()=>{const c=read('lib','api','client.ts');for(const s of ['beginLibraryFile','commitLibraryFile','libraryFileUrl','deleteLibraryFile','library: (w: string']) assert.ok(c.includes(s),s);});
test('Library upload uses signed storage then server commit',()=>{const v=read('features','library','library-view.tsx');assert.match(v,/beginLibraryFile/);assert.match(v,/putSignedUpload/);assert.match(v,/commitLibraryFile/);assert.match(v,/50 \* 1024 \* 1024/);});
test('MP4 and MOV use the video path without misrouting audio WebM',()=>{const v=read('features','library','library-view.tsx');assert.match(v,/VIDEO_UPLOAD_MIMES = new Set\(\['video\/mp4', 'video\/quicktime'\]\)/);assert.match(v,/VIDEO_UPLOAD_EXTENSIONS = new Set\(\['mp4', 'mov', 'm4v'\]\)/);assert.match(v,/VIDEO_UPLOAD_MIMES\.has\(file\.type\.toLowerCase\(\)\) \|\| VIDEO_UPLOAD_EXTENSIONS\.has\(extension\)/);});
test('documents, audio and generic files are real Library kinds',()=>{const k=read('lib','media','asset-kinds.ts');assert.match(k,/'document'/);assert.match(k,/'audio'/);assert.match(k,/'file'/);const u=read('features','library','use-library.ts');assert.match(u,/api\.library/);assert.match(u,/LibraryKindFilter = 'all' \| 'image' \| 'video' \| 'audio' \| 'document' \| 'file'/);});
test('document detail reads extracted text and opens original by signed URL',()=>{const d=read('features','library','asset-detail.tsx');assert.match(d,/DocumentText/);assert.match(d,/libraryFile\(workspaceId, asset\.id\)/);assert.match(d,/libraryFileUrl/);});
test('every non-image Library kind has a visual thumbnail in gallery, list and detail',()=>{const t=read('features','library','asset-thumbnail.tsx');for(const s of ['AssetFileThumbnail','PdfFirstPage','AudioCover','DocumentCover','GenericFileCover','First page PDF thumbnail','page=1&view=Fit'])assert.ok(t.includes(s),s);for(const f of ['asset-card.tsx','asset-list-row.tsx','asset-detail.tsx'])assert.match(read('features','library',f),/AssetFileThumbnail/);});
test('document thumbnails show first-page content and distinguish text and office formats',()=>{const t=read('features','library','asset-thumbnail.tsx');for(const s of ['asset.extractedText','asset.aiSummary','MARKDOWN','FIRST PAGE','PDF · FIRST PAGE'])assert.ok(t.includes(s),s);for(const s of ['TEXT PREVIEW','SHEET PREVIEW','SLIDE PREVIEW'])assert.ok(!t.includes(s),s);});
