'use client';
import {useEffect,useMemo,useReducer,useRef,useState,type KeyboardEvent} from 'react';
import Link from 'next/link';
import {controlApi as api} from './control-api';
import {initialQueryState,queryReducer} from '../../query-state.mjs';
import type {BoundQuery,QueryResult,Run} from '../../query-state.mjs';

type Source={source_id:string;state:string;watermark:string|null;reason_code:string;provenance?:string;age_seconds?:number|null};
type Readiness={qualifiedSources:number;sourcesConsidered:number;businessHealth:string;reason:string};
type Delivery=Record<string,unknown>;
type Snapshot={id:string;exactSha:string;provenance:string;observedAt:string;qualification:{qualification:string;requiredCount:number;observedRequiredCount:number;releaseAccepted:boolean}};
type Receipt={id:string;normalized_query:BoundQuery;calculated_at:string;execution_state:string;source_versions:Record<string,unknown>;coverage:Record<string,unknown>;query_digest:string;metric_versions:Record<string,unknown>;result_rows:QueryResult['rows']};
const readable=(value:string)=>value.replaceAll('_',' ');
const date=(value:string)=>new Date(value).toISOString().slice(0,10);
function Period({query}:{query:BoundQuery}){return <p className="small query-context">Observation window: {query.interval.start} ≤ observed time &lt; {query.interval.end} · {query.interval.timeZone}<br/>Suite: {query.filters[0]?.values.join(', ')||'All required suites'} · comparison: {query.comparison} · limit: {query.limit}</p>;}
export function DataTrust({sources}:{sources:Source[]}){return <details className="panel data-trust"><summary>Data trust · {sources.filter(s=>s.state==='measured').length} current qualified source(s)</summary><p>Source readiness describes access, freshness and coverage. Business telemetry remains unqualified.</p><div className="source-health">{sources.map(source=><div className="source-row" key={source.source_id}><div><strong>{readable(source.source_id)}</strong><p className="small muted">{readable(source.reason_code)}<br/>Observed: {source.watermark||'Unavailable'} · {readable(source.provenance||'unqualified')}</p></div><span className="badge">{source.state}</span></div>)}</div></details>;}
export function FounderHome({readiness,sources,delivery}:{readiness:Readiness;sources:Source[];delivery:Delivery}){return <>
  <section className="panel home-primary"><p className="eyebrow">One investigation, with evidence</p><h2>GitHub Checks</h2><p>Inspect the required workflow manifest for one exact commit, then open its evidence and ask Rafii to explain the selected receipt.</p><Link className="primary-link" href="/control/engineering">Investigate GitHub Checks →</Link><p className="small muted">Manual metadata snapshots · read-only · no automatic polling</p></section>
  <section className="panel"><h2>Evidence readiness</h2><div className="readiness"><div><strong>{readiness.qualifiedSources} / {readiness.sourcesConsidered}</strong><p>Current qualified sources</p></div><div><strong>Unavailable</strong><p>Business health</p></div></div><p>{readiness.reason}</p></section>
  <DataTrust sources={sources}/><details className="panel"><summary>Delivery identities</summary><p>Local source, captured CI evidence and hosted runtime are independent identities.</p><dl>{Object.entries(delivery).map(([key,value])=><div className="identity" key={key}><dt>{readable(key)}</dt><dd>{value==null?'Unverified':typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl></details>
</>;}
export function ChecksJourney({csrf}:{csrf:string}){
  const [snapshots,setSnapshots]=useState<Snapshot[]>([]),[snapshotId,setSnapshotId]=useState(''),[loadError,setLoadError]=useState(''),[loading,setLoading]=useState(true);
  const [suite,setSuite]=useState(''),[start,setStart]=useState(()=>date(new Date(Date.now()-28*86400000).toISOString())),[end,setEnd]=useState(()=>date(new Date(Date.now()+86400000).toISOString()));
  const [state,dispatch]=useReducer(queryReducer,initialQueryState),[receipt,setReceipt]=useState<Receipt|null>(null),[drawerError,setDrawerError]=useState(''),[explaining,setExplaining]=useState(false);
  const revision=useRef(0),selected=useRef<string|null>(null),selection=useRef(0),queryAbort=useRef<AbortController|null>(null),drawerAbort=useRef<AbortController|null>(null),explainAbort=useRef<AbortController|null>(null),dialog=useRef<HTMLDialogElement>(null);
  const query=useMemo<BoundQuery>(()=>({metricIds:['check_failures'],interval:{start:start+'T00:00:00Z',end:end+'T00:00:00Z',timeZone:'UTC'},groupBy:['suite','failure_class'],filters:suite?[{dimension:'suite',operator:'eq',values:[suite]}]:[],comparison:'none',limit:100}),[start,end,suite]);
  function invalidate(){revision.current++;selected.current=null;queryAbort.current?.abort();drawerAbort.current?.abort();explainAbort.current?.abort();setExplaining(false);setReceipt(null);setDrawerError('');dispatch({type:'changed'});}
  async function load(){setLoading(true);setLoadError('');try{const result=await api<{data:{snapshots:Snapshot[]}}>('/engineering/checks');setSnapshots(result.data.snapshots);if(result.data.snapshots.length&&!snapshotId){invalidate();setSnapshotId((result.data.snapshots.find(s=>s.provenance==='admitted_operational')||result.data.snapshots[0]).id);}}catch(error){setLoadError(error instanceof Error?error.message:'Source metadata unavailable.');}finally{setLoading(false);}}
  useEffect(()=>{void load();return()=>{queryAbort.current?.abort();drawerAbort.current?.abort();explainAbort.current?.abort();};},[]); // One explicit page load; no polling.
  useEffect(()=>{if(state.selectedReceipt){dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();}},[state.selectedReceipt]);
  function trapFocus(event:KeyboardEvent<HTMLDialogElement>){
    if(event.key!=='Tab')return;
    const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,summary,[tabindex="0"]')).filter(node=>node.getClientRects().length>0);
    const first=controls[0],last=controls[controls.length-1];
    if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}
    else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
  }
  function close(){selection.current++;selected.current=null;drawerAbort.current?.abort();explainAbort.current?.abort();setExplaining(false);dispatch({type:'close'});}
  async function inspect(){const rev=++revision.current,controller=new AbortController();queryAbort.current?.abort();queryAbort.current=controller;dispatch({type:'start',revision:rev,query,snapshotId});const timer=setTimeout(()=>controller.abort(),14000);
    try{const result=await api<QueryResult>('/engineering/checks/query',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({snapshotId,query})});dispatch({type:'success',revision:rev,query,snapshotId,result});}
    catch(error){dispatch({type:'failed',revision:rev,error:controller.signal.aborted?'Read interrupted or deadline reached. Retry this query.':error instanceof Error?error.message:'Read unavailable.'});}finally{clearTimeout(timer);}}
  async function open(){if(!state.lastGood)return;const ref=state.lastGood.result.queryReceiptId,rev=revision.current,pick=++selection.current,controller=new AbortController();selected.current=ref;drawerAbort.current?.abort();drawerAbort.current=controller;setReceipt(null);setDrawerError('');dispatch({type:'select',receiptId:ref});const timer=setTimeout(()=>controller.abort(),14000);
    try{const result=await api<{data:{receipt:Receipt}}>('/metrics/receipts/'+ref,{signal:controller.signal});if(result.data.receipt.id!==ref)throw new Error('Receipt lineage did not match the selected evidence.');if(rev===revision.current&&pick===selection.current&&selected.current===ref)setReceipt(result.data.receipt);}
    catch(error){if(rev===revision.current&&pick===selection.current&&selected.current===ref)setDrawerError(error instanceof Error?error.message:'Receipt unavailable.');}finally{clearTimeout(timer);}}
  async function explain(){if(!receipt||receipt.id!==selected.current)return;const ref=receipt.id,rev=revision.current,pick=++selection.current,controller=new AbortController();explainAbort.current?.abort();explainAbort.current=controller;setExplaining(true);setDrawerError('');const timer=setTimeout(()=>controller.abort(),14000);
    try{const requestId=crypto.randomUUID();const accepted=await api<{statusPath:string}>('/copilot/turns',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':requestId},body:JSON.stringify({requestId,conversationId:crypto.randomUUID(),message:'Explain selected receipt',contextEvidenceIds:[ref],modality:'text'})});const result=await api<{data:{run:Run}}>(accepted.statusPath.replace('/api/control/v2',''),{signal:controller.signal});if(pick===selection.current)dispatch({type:'explanation',revision:rev,receiptId:ref,run:result.data.run});}
    catch(error){if(rev===revision.current&&pick===selection.current&&selected.current===ref)setDrawerError(error instanceof Error?error.message:'Explanation unavailable.');}finally{clearTimeout(timer);if(rev===revision.current&&pick===selection.current&&selected.current===ref)setExplaining(false);}}
  const previous=state.lastGood?.revision!==state.revision,active=snapshots.find(s=>s.id===snapshotId);
  return <><Link href="/control/command">← Founder Home</Link><section className="panel"><h2>GitHub Checks investigation</h2><p>One exact SHA and a server-held manifest of two required workflows. Their success does not establish release, merge, deployment or production acceptance.</p>
    {loading&&<p role="status">Loading manually captured metadata…</p>}{loadError&&<div role="alert"><p>{loadError}</p><button onClick={load}>Retry metadata</button></div>}
    {!loading&&!loadError&&!snapshots.length&&<p role="status">No captured check evidence. An approved operator must import a read-only metadata snapshot locally.</p>}
    {!!snapshots.length&&<form onSubmit={event=>{event.preventDefault();void inspect();}}>
      <label htmlFor="snapshot">Evidence snapshot</label><select id="snapshot" value={snapshotId} onChange={event=>{invalidate();setSnapshotId(event.target.value);}}>{snapshots.map(s=><option key={s.id} value={s.id}>{readable(s.provenance)} · {s.exactSha.slice(0,12)} · {s.observedAt}</option>)}</select>
      {active&&<p className="small break">Exact SHA: {active.exactSha.slice(0,12)}<br/>{readable(active.provenance)} · {readable(active.qualification.qualification)} · {active.qualification.observedRequiredCount}/{active.qualification.requiredCount} required workflows observed</p>}
      <div className="query-fields"><label>Start date (UTC)<input type="date" value={start} onChange={event=>{invalidate();setStart(event.target.value);}} required/></label><label>End date, exclusive (UTC)<input type="date" value={end} onChange={event=>{invalidate();setEnd(event.target.value);}} required/></label><label>Suite filter<input value={suite} maxLength={160} onChange={event=>{invalidate();setSuite(event.target.value);}} placeholder="All required suites"/></label></div>
      <Period query={query}/><button disabled={state.status==='loading'||!snapshotId}>Inspect checks</button>
    </form>}
  </section><p className="query-status" role="status" aria-live="polite">{state.status==='loading'?'Reading the selected snapshot…':state.status==='ready'?'Query complete. Evidence is ready to inspect.':state.lastGood?'Query changed. Previous evidence remains separately available.':'Choose a snapshot and inspect checks.'}</p>
    {state.error&&<div className="error" role="alert"><p>{state.error}</p>{state.attempt&&<Period query={state.attempt.query}/>}<p>The attempted query has no current result.</p></div>}
    {state.lastGood&&<section className="panel" aria-label={previous?'Previous query evidence':'Current query evidence'}><h2>{previous?'Previous query evidence':'Current query evidence'}</h2>{previous&&<p>Retained from the last successful read. It does not answer the current query.</p>}<Period query={state.lastGood.query}/><CheckValues result={state.lastGood.result}/><button onClick={open}>Open {previous?'previous':'current'} evidence</button></section>}
    <dialog ref={dialog} className="evidence-drawer" aria-labelledby="evidence-title" onKeyDown={trapFocus} onClose={close} onCancel={close}><div className="drawer-heading"><h2 id="evidence-title">Selected evidence</h2><button onClick={()=>dialog.current?.close()} autoFocus>Close evidence</button></div>{state.lastGood&&<p>{previous?'Previous query receipt explicitly selected.':'Current query receipt explicitly selected.'}</p>}
      {drawerError&&<p role="alert">{drawerError}</p>}{!receipt&&!drawerError&&<p role="status">Loading selected receipt…</p>}
      {receipt&&<><Period query={receipt.normalized_query}/><p>Calculated: {receipt.calculated_at}<br/>Execution: {readable(receipt.execution_state)}</p><dl><dt>Source SHA</dt><dd>{String(receipt.source_versions.exactSha||'Unavailable')}</dd><dt>Observed at</dt><dd>{String(receipt.source_versions.observedAt||'Unavailable')}</dd><dt>Read age at calculation</dt><dd>{receipt.source_versions.ageSeconds==null?'Unavailable':String(receipt.source_versions.ageSeconds)+' seconds'}</dd><dt>Coverage</dt><dd>{receipt.coverage.complete?'Complete required manifest observation':'Incomplete'} · {String(receipt.coverage.observed??'Unknown')}/{String(receipt.coverage.required??'Unknown')} required workflows</dd><dt>Qualification</dt><dd>{readable(String(receipt.coverage.qualification||'unavailable'))}</dd><dt>Release acceptance</dt><dd>Unverified</dd><dt>Definition</dt><dd>check_failures v{String(receipt.metric_versions.check_failures)} · engineering job · count</dd></dl><p>Quality and freshness belong to this calculated snapshot. Re-query to assess current source readiness.</p><details><summary>Technical receipt and lineage</summary><dl><dt>Receipt ID</dt><dd data-testid="selected-receipt">{receipt.id}</dd><dt>Query digest</dt><dd>{receipt.query_digest}</dd><dt>Source versions</dt><dd>{JSON.stringify(receipt.source_versions)}</dd><dt>Coverage contract</dt><dd>{JSON.stringify(receipt.coverage)}</dd></dl></details><button onClick={explain} disabled={explaining}>{explaining?'Explaining selected receipt…':'Explain selected receipt'}</button></>}
      <div aria-live="polite" role="status">{state.explanation&&<section aria-label="Selected receipt explanation"><h3>Rafii · deterministic explanation</h3><p>{state.explanation.answerText}</p><p className="small">Grounded in selected receipt: {state.explanation.queryReceiptIds?.join(', ')}</p></section>}</div>
    </dialog></>;
}
function CheckValues({result}:{result:QueryResult}){const measured=result.rows.filter(row=>row.dataState==='measured'&&row.value!==null),max=Math.max(1,...measured.map(row=>row.value!));return <>
  <p>{readable(result.executionState)} · {result.dataState} · calculated {result.asOf}<br/>Read observation age at calculation: {result.sourceVersions.ageSeconds==null?'Unavailable':String(result.sourceVersions.ageSeconds)+' seconds'}</p>
  <figure><figcaption>Check failure counts · current measured observations only</figcaption>{measured.length?<div className="check-chart" data-testid="check-chart" aria-hidden="true">{measured.map((row,i)=><div className="check-bar" key={i}><span>{row.dimensions?.suite||'Required workflow'}</span><div className="bar-track"><div className="bar-fill" style={{width:(row.value!/max*100)+'%'}}/></div><strong>{row.value} {row.value===0?'· zero failures':''}</strong></div>)}</div>:<p>No current measured values to plot. Inspect quality in the table.</p>}</figure>
  <div className="table-scroll" tabIndex={0} role="region" aria-label="Check values and quality"><table><caption>Check values and quality · same query receipt</caption><thead><tr><th scope="col">Required workflow</th><th scope="col">Failures</th><th scope="col">Outcome</th><th scope="col">Quality</th></tr></thead><tbody>{result.rows.map((row,i)=><tr key={i}><th scope="row">{row.dimensions?.suite||'No matching required workflow'}</th><td>{row.value===null?'Unavailable':row.value===0?'0 · zero failures':row.value}</td><td>{readable(row.outcome||row.reason||'unavailable')}</td><td>{row.dataState}</td></tr>)}</tbody></table></div>
  <p className="small muted">Unknown, skipped, partial and infrastructure failures remain unavailable. Historical stale values appear only in the table. No population-wide or release conclusion is implied.</p>
</>;}
