'use client';
import { useState } from 'react';
import Link from 'next/link';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip } from 'recharts';

type Cell={id:string;title:string;value:number|null;unit:string;grain:string;definitionVersion:number;dataState:string;sourceWatermark:string|null;sampleCount:number|null;reason:string};
type Source={source_id:string;state:string;watermark:string|null;checked_at:string|null;reason_code:string};
type Definition={id:string;title:string;definition:string;version:number;unit:string;grain:string;allowed_dimensions:string[];currency_policy:string;status:string;limitations:string};
type Dashboard={id:string;workbench:string;question:string;metric_ids:string[]};
type SafeRow=Record<string,string|number|boolean|null>;
type Data={metrics?:Cell[];sources?:Source[];users?:SafeRow[];workspaces?:SafeRow[];evidence?:SafeRow[];events?:SafeRow[];dashboards?:Dashboard[];definitions?:Definition[];recommendations?:unknown[];user?:SafeRow;memberships?:SafeRow[];run?:Run};
type Envelope<T=Data>={requestId:string;environment:string;asOf:string;dataState:string;receiptIds:string[];data:T};
type Session={assurance:string;capabilities:string[];csrfToken:string};
type Run={answerText?:string;warnings?:{code:string;message:string}[];queryReceiptIds?:string[];mode?:string};
type QueryResult={queryReceiptId:string;dataState:string;asOf:string;rows:{metricId:string;value:number|null;dataState:string;definitionVersion:number;unit:string;grain:string;sampleCount:number|null}[];warnings:string[]};
const nav=[['command','Command'],['customers','Customers'],['revenue','Revenue'],['product','Product'],['infrastructure','AI & Infrastructure'],['engineering','Engineering'],['support','Trust & Support'],['settings','Settings']];
const subtitles:Record<string,string>={command:'Evidence first. See what is known, what needs investigation, and which sources need attention.',customers:'Safe account metadata and workspace context. Private customer content requires a scoped support grant.',workspaces:'Canonical membership and subscription metadata, without opening private workspace content.',revenue:'Recurring value, cash collections, credits, and costs retain their distinct definitions.',product:'Activation means a validated first-value outcome. Cohort maturity and coverage come before conclusions.',infrastructure:'Provider cost, quality, and system health retain source coverage and reconciliation limits.',engineering:'Track evidence from suspected to production verified. A code change alone never proves a fix.',support:'Support and security investigations respect consent, scope, and retention.',settings:'Operator access, source health, policy versions, and the content-free admin audit trail.',founder:'Read-only founder intelligence, with bounded tools and explicit evidence.'};
async function api<T>(path:string,options:RequestInit={}):Promise<T> {
  const response=await fetch('/api/control/v2'+path,{...options,cache:'no-store',credentials:'same-origin'});
  if (!response.ok) {
    if (response.status===401) {window.location.assign('/sign-in');throw new Error('Founder session expired. Sign in again.');}
    throw new Error(response.status===403?'This operator does not have permission for this view.':'This source is unavailable. Retry after its health is restored.');
  }
  return response.json() as Promise<T>;
}
export default function Control({section}:{section:string}) {
  const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,staleTime:0,gcTime:0,refetchOnWindowFocus:true}}}));
  return <QueryClientProvider client={client}><Workbench section={section} client={client}/></QueryClientProvider>;
}
function Workbench({section,client}:{section:string;client:QueryClient}) {
  const [selectedUser,setSelectedUser]=useState(''),[logoutError,setLogoutError]=useState('');
  const session=useQuery({queryKey:['founder','session'],queryFn:()=>api<Envelope<Session>>('/session')});
  const route={command:'/overview',customers:'/users',workspaces:'/workspaces',engineering:'/engineering',settings:'/audit',founder:'/sources/health'}[section] || '/dashboards';
  const result=useQuery({queryKey:['founder',section],queryFn:()=>api<Envelope>(route),enabled:!!session.data});
  const sources=useQuery({queryKey:['founder','sources'],queryFn:()=>api<Envelope>('/sources/health'),enabled:!!session.data});
  const user=useQuery({queryKey:['founder','user',selectedUser],queryFn:()=>api<Envelope>('/users/'+selectedUser),enabled:!!selectedUser&&!!session.data});
  async function logout(){try{await api('/session/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data!.data.csrfToken},body:'{}'});client.clear();window.location.assign('/sign-in');}catch{setLogoutError('Sign-out could not be confirmed. Retry.');}}
  const title=nav.find(item=>item[0]===section)?.[1] || (section==='workspaces'?'Workspaces':'Founder Rafii');
  return <div className="layout"><aside className="sidebar"><Link href="/control/command" className="brand">Rafii <span className="muted">Control</span></Link><p className="small muted">Founder operations</p><nav aria-label="Control workbenches">{nav.map(([id,label])=><Link key={id} href={'/control/'+id} aria-current={section===id?'page':undefined}>{label}</Link>)}</nav><hr/><p><Link href="/control/founder">Founder Rafii</Link></p><p className="small muted">Read-only / Phase 1</p></aside>
    <main id="main" tabIndex={-1} className="workspace"><div className="topbar"><div className="row"><span className="badge">{result.data?.environment || session.data?.environment || 'Checking environment'}</span><span className="small">AAL2 required · separate founder session</span></div><button onClick={logout} disabled={!session.data}>Sign out</button></div>
      <div className="heading"><p className="eyebrow">Founder workspace</p><h1>{title}</h1><p>{subtitles[section]}</p></div>
      {logoutError&&<p role="alert">{logoutError}</p>}
      {(session.error||result.error)&&<p className="error" role="alert">{(session.error||result.error)?.message}</p>}
      {(!session.data||result.isPending)&&!result.error&&!session.error&&<p role="status">Verifying founder access and loading evidence…</p>}
      {result.data&&<><p className="small muted">As of {new Date(result.data.asOf).toLocaleString()} · {result.data.dataState} · current source coverage shown below</p>
        {section==='command'&&<><div className="grid">{result.data.data.metrics?.map(cell=><Metric key={cell.id} cell={cell} csrf={session.data!.data.csrfToken}/>)}</div><section className="panel"><h2>Investigation queue</h2><p>Automatic detectors are disabled while baseline, source coverage, and threshold policies are qualified.</p><Link href="/control/founder">Investigate with Founder Rafii →</Link></section></>}
        {section==='customers'&&<><div className="row"><Link href="/control/workspaces">Browse Workspaces →</Link></div><section className="panel"><Table title="Users · safe metadata (up to 200)" rows={result.data.data.users||[]} columns={['user_id','deleted','workspace_count','last_seen_at']} select={row=>setSelectedUser(String(row.user_id))}/></section>{selectedUser&&<section className="panel" aria-label="User 360"><h2>User 360</h2>{user.error?<p role="alert">{user.error.message}</p>:user.data?<><Table title="Account metadata" rows={user.data.data.user?[user.data.data.user]:[]} columns={['user_id','deleted','workspace_count','last_seen_at']}/><Table title="Memberships" rows={user.data.data.memberships||[]} columns={['workspace_id','role','status']}/><p>Private customer content: suppressed. A scoped support grant is required.</p><p>Financial, suspension, deletion, and impersonation actions are disabled.</p></>:<p role="status">Loading safe account context…</p>}<button onClick={()=>setSelectedUser('')}>Close User 360</button></section>}</>}
        {section==='workspaces'&&<section className="panel"><Table title="Workspaces · safe metadata (up to 200)" rows={result.data.data.workspaces||[]} columns={['id','created_at','member_count','subscription_status','plan','terms_version']}/></section>}
        {section==='engineering'&&<><section className="panel"><h2>Engineering evidence</h2><p>Suspected → reproduced → candidate fix → checks passed → merged → deployed → production verified</p><p className="muted">Required checks must pass for the exact candidate SHA. Skipped checks and infrastructure failures do not prove a product fix.</p><Table title="Errors, logs, deployments, and code checks" rows={result.data.data.evidence||[]} columns={['kind','provider','external_id','exact_sha','state','conclusion','failure_class','attested','observed_at']}/></section><p>Code-check dispatch, patch creation, and deployment controls require later qualification and approval.</p></>}
        {section==='settings'&&<><section className="panel"><h2>Access & policies</h2><p>Read access follows the current server-held operator record. Capability removal and auth epoch changes take effect on the next request.</p><p>30-minute idle timeout · 8-hour absolute timeout · sensitive step-up proof expires after 5 minutes.</p><p>Metric definitions and scheduled investigators remain proposed and disabled.</p></section><section className="panel"><Table title="Admin audit · latest 200 events" rows={result.data.data.events||[]} columns={['occurred_at','actor','action','result','request_id']}/></section></>}
        {['revenue','product','infrastructure','support'].includes(section)&&<Definitions section={section} data={result.data.data} csrf={session.data!.data.csrfToken}/>}
        {section==='founder'&&<Founder csrf={session.data!.data.csrfToken}/>}
      </>}
      {sources.data&&<section className="panel"><h2>Source health</h2><p className="muted small">Provider connection, freshness, and qualification are separate from source code being present.</p><div className="source-health">{sources.data.data.sources?.map(source=><div className="source-row" key={source.source_id}><div><strong>{source.source_id}</strong><div className="small muted">{source.reason_code.replaceAll('_',' ')} · watermark: {source.watermark||'unavailable'}</div></div><span className="badge">{source.state}</span></div>)}</div></section>}
    </main></div>;
}
function Table({title,rows,columns,select}:{title:string;rows:SafeRow[];columns:string[];select?:(row:SafeRow)=>void}) {
  return <div className="table-scroll"><table><caption>{title}</caption><thead><tr>{columns.map(name=><th key={name} scope="col">{name.replaceAll('_',' ')}</th>)}{select&&<th scope="col">Investigate</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(name=><td key={name}>{row[name]===null?'Unavailable':typeof row[name]==='boolean'?(row[name]?'Yes':'No'):String(row[name]??'Unavailable')}</td>)}{select&&<td><button onClick={()=>select(row)} aria-label={'Open User 360 for '+row.user_id}>User 360</button></td>}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No qualified records are available in this view.</p>}</div>;
}
function Metric({cell,csrf}:{cell:Cell;csrf:string}) {
  return <article className="card"><h2>{cell.title}</h2><p className="metric">{cell.value===null?'Unavailable':cell.value.toLocaleString()}</p><span className="badge">{cell.dataState}</span><p className="small muted">{cell.unit} · definition v{cell.definitionVersion}</p><details className="definition"><summary>Definition & evidence</summary><dl><dt>Grain</dt><dd>{cell.grain}</dd><dt>Watermark</dt><dd>{cell.sourceWatermark||'Unavailable'}</dd><dt>Eligible samples</dt><dd>{cell.sampleCount??'Unavailable'}</dd><dt>Reason</dt><dd>{cell.reason.replaceAll('_',' ')}</dd></dl><MetricQuery id={cell.id} currency={cell.unit==='currency_minor'} csrf={csrf}/></details></article>;
}
function MetricQuery({id,currency,csrf}:{id:string;currency:boolean;csrf:string}) {
  const [result,setResult]=useState<QueryResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function query(){setBusy(true);setError('');try{const end=new Date(),start=new Date(end.getTime()-28*86400000);setResult(await api<QueryResult>('/metrics/query',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({metricIds:[id],interval:{start:start.toISOString(),end:end.toISOString(),timeZone:'UTC'},groupBy:currency?['currency']:[],filters:[],comparison:'none',limit:100})}));}catch(failure){setError(failure instanceof Error?failure.message:'Query failed.');}finally{setBusy(false);}}
  return <><button onClick={query} disabled={busy}>{busy?'Querying…':'Inspect last 28 days'}</button>{error&&<p role="alert">{error}</p>}{result&&<div role="status"><p className="small">Receipt: {result.queryReceiptId}</p><p>{result.warnings.join(' ')}</p><MetricChart result={result}/></div>}</>;
}
function MetricChart({result}:{result:QueryResult}) {
  const points=result.rows.filter(row=>row.value!==null);
  return <figure><figcaption>{result.dataState} · as of {result.asOf}. {points.length?'Values from qualified query evidence.':'No qualified values to plot.'}</figcaption>{points.length>0&&<div className="chart" aria-hidden="true"><ResponsiveContainer><LineChart data={points}><XAxis dataKey="metricId"/><YAxis/><Tooltip/><Line dataKey="value" stroke="#111" isAnimationActive={false}/></LineChart></ResponsiveContainer></div>}<Table title="Metric values and quality" rows={result.rows as unknown as SafeRow[]} columns={['metricId','value','unit','grain','definitionVersion','dataState','sampleCount']}/></figure>;
}
function Definitions({section,data,csrf}:{section:string;data:Data;csrf:string}) {
  const domains:Record<string,string[]>={revenue:['Revenue'],product:['Product'],infrastructure:['AI','Reliability'],support:['Support']};
  const dashboards=data.dashboards?.filter(d=>(domains[section]||[section]).includes(d.workbench))||[];
  const ids=new Set(dashboards.flatMap(d=>d.metric_ids));
  return <><p>Definitions are versioned proposals. Values remain unavailable until the business policy and source are qualified.</p><div className="grid">{data.definitions?.filter(def=>ids.has(def.id)).map(def=><article className="card" key={def.id}><h2>{def.title}</h2><p className="metric">Unavailable</p><p className="small muted">{def.unit} · v{def.version} · {def.grain}</p><details><summary>Definition and limitations</summary><p>{def.definition}</p><p>{def.limitations}</p><MetricQuery id={def.id} currency={def.currency_policy==='native_currency_separate'} csrf={csrf}/></details></article>)}</div>{!ids.size&&<section className="panel"><h2>Investigation access</h2><p>Support grants, ticket content, customer replies, and security actions require scoped access and separate approval. They are disabled in Phase 1.</p></section>}</>;
}
function Founder({csrf}:{csrf:string}) {
  const [message,setMessage]=useState(''),[answer,setAnswer]=useState<Run|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function inspect(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const requestId=crypto.randomUUID();const accepted=await api<{statusPath:string}>('/copilot/turns',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':requestId},body:JSON.stringify({requestId,conversationId:crypto.randomUUID(),message,contextEvidenceIds:[],modality:'text'})});const receipt=await fetch(accepted.statusPath,{cache:'no-store'});if(!receipt.ok)throw new Error('Investigation evidence could not be read.');const run=await receipt.json() as Envelope;setAnswer(run.data.run||null);setMessage('');}catch(failure){setError(failure instanceof Error?failure.message:'Investigation failed.');}finally{setBusy(false);}}
  return <section className="panel"><h2>Founder Rafii</h2><p className="muted">Deterministic read-only mode. Model generation and scheduled investigations need a separately approved budget and data policy.</p><form onSubmit={inspect}><label htmlFor="question">Business question</label><textarea id="question" maxLength={16000} value={message} onChange={event=>setMessage(event.target.value)} required/><button type="submit" disabled={busy}>{busy?'Inspecting…':'Inspect evidence'}</button></form>{error&&<p role="alert">{error}</p>}{answer&&<div role="status"><h3>Evidence & limitations</h3><p>{answer.answerText}</p>{answer.queryReceiptIds?.map(id=><p className="small" key={id}>Query receipt: {id}</p>)}{answer.warnings?.map(w=><p className="muted" key={w.code}>{w.message}</p>)}</div>}<p className="small muted">No refund, ban, deletion, deployment, migration, code write, or external message can be executed here.</p></section>;
}
