'use client';
import { useState,useRef,useEffect } from 'react';
import Link from 'next/link';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';
import {controlApi as api} from './control-api';
import {FounderHome,ChecksJourney} from './checks-journey';

type Cell={id:string;title:string;value:number|null;unit:string;grain:string;definitionVersion:number;dataState:string;sourceWatermark:string|null;sampleCount:number|null;reason:string};
type Source={source_id:string;state:string;watermark:string|null;checked_at:string|null;reason_code:string};
type Definition={id:string;title:string;definition:string;version:number;unit:string;grain:string;allowed_dimensions:string[];currency_policy:string;status:string;limitations:string};
type Dashboard={id:string;workbench:string;question:string;metric_ids:string[]};
type SafeRow=Record<string,string|number|boolean|null>;
type Data={evidenceReadiness?:{qualifiedSources:number;sourcesConsidered:number;businessHealth:string;reason:string};delivery?:Record<string,unknown>;metrics?:Cell[];sources?:Source[];users?:SafeRow[];workspaces?:SafeRow[];evidence?:SafeRow[];events?:SafeRow[];dashboards?:Dashboard[];definitions?:Definition[];recommendations?:unknown[];user?:SafeRow;memberships?:SafeRow[];run?:Run};
type Envelope<T=Data>={requestId:string;environment:string;asOf:string;dataState:string;receiptIds:string[];data:T};
type Session={assurance:string;capabilities:string[];csrfToken:string};
type Run={answerText?:string;warnings?:{code:string;message:string}[];queryReceiptIds?:string[];mode?:string};
type QueryResult={queryReceiptId:string;dataState:string;asOf:string;rows:{metricId:string;value:number|null;dataState:string;definitionVersion:number;unit:string;grain:string;sampleCount:number|null;dimensions?:Record<string,string>;sourceWatermark?:string;sourceReceiptIds?:string[];reason?:string}[];warnings:string[];executionState:string};
const nav=[['command','Founder Home'],['customers','Customers'],['billing','Billing & credits'],['product','Product'],['infrastructure','AI & Infrastructure'],['engineering','GitHub Checks'],['support','Trust & Support'],['settings','Connections']];
const subtitles:Record<string,string>={command:'Evidence first. See what is known, what needs investigation, and which sources need attention.',customers:'Safe account metadata and workspace context. Private customer content requires a scoped support grant.',workspaces:'Canonical membership and subscription metadata, without opening private workspace content.',revenue:'Recurring value, cash collections, credits, and costs retain their distinct definitions.',product:'Activation means a validated first-value outcome. Cohort maturity and coverage come before conclusions.',infrastructure:'Provider cost, quality, and system health retain source coverage and reconciliation limits.',engineering:'Track evidence from suspected to production verified. A code change alone never proves a fix.',support:'Support and security investigations respect consent, scope, and retention.',settings:'Operator access, source health, policy versions, and the content-free admin audit trail.',founder:'Read-only founder intelligence, with bounded tools and explicit evidence.'};

export default function Control({section}:{section:string}) {
  const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,staleTime:0,gcTime:0,refetchOnWindowFocus:true}}}));
  return <QueryClientProvider client={client}><Workbench section={section} client={client}/></QueryClientProvider>;
}
function Workbench({section,client}:{section:string;client:QueryClient}) {
  const [selectedUser,setSelectedUser]=useState(''),[logoutError,setLogoutError]=useState('');
  const session=useQuery({queryKey:['founder','session'],queryFn:()=>api<Envelope<Session>>('/session')});
  const route={command:'/overview',customers:'/users',workspaces:'/workspaces',engineering:'/engineering',settings:'/audit',founder:'/sources/health'}[section] || '/dashboards';
  const result=useQuery({queryKey:['founder',section],queryFn:()=>api<Envelope>(route),enabled:!!session.data});
  const sources=useQuery({queryKey:['founder','sources'],queryFn:()=>api<Envelope>('/sources/health'),enabled:!!session.data});
  const user=useQuery({queryKey:['founder','user',selectedUser],queryFn:()=>api<Envelope>('/users/'+selectedUser),enabled:!!selectedUser&&!!session.data});
  async function logout(){try{await api('/session/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data!.data.csrfToken},body:'{}'});client.clear();window.location.assign('/sign-in');}catch{setLogoutError('Sign-out could not be confirmed. Retry.');}}
  const title=nav.find(item=>item[0]===section)?.[1] || (section==='workspaces'?'Workspaces':'Founder Rafii');
  return <div className="layout"><aside className="sidebar"><Link href="/control/command" className="brand">Rafii <span className="muted">Control</span></Link><p className="small muted">Founder operations</p><nav className="desktop-nav" aria-label="Control workbenches">{nav.map(([id,label])=><Link key={id} href={'/control/'+id} aria-current={section===id?'page':undefined}>{label}</Link>)}</nav><details className="menu"><summary>Navigation · {title}</summary><nav aria-label="Mobile workbenches">{nav.map(([id,label])=><Link key={id} href={'/control/'+id} aria-current={section===id?'page':undefined}>{label}</Link>)}</nav></details><hr/><p><Link href="/control/founder">Founder Rafii</Link></p><p className="small muted">Read-only / Phase 1</p></aside>
    <main id="main" tabIndex={-1} className="workspace"><div className="topbar"><div className="row"><span className="badge">{result.data?.environment || session.data?.environment || 'Checking environment'}</span><span className="small">AAL2 required · separate founder session</span></div><button onClick={logout} disabled={!session.data}>Sign out</button></div>
      <div className="heading"><p className="eyebrow">Founder workspace</p><h1>{title}</h1><p>{subtitles[section]}</p></div>
      {logoutError&&<p role="alert">{logoutError}</p>}
      {(session.error||result.error)&&<p className="error" role="alert">{(session.error||result.error)?.message}</p>}
      {(!session.data||result.isPending)&&!result.error&&!session.error&&<p role="status">Verifying founder access and loading evidence…</p>}
      {result.data&&<><p className="small muted">As of {new Date(result.data.asOf).toLocaleString()} · {result.data.dataState} · source qualification shown below</p>
        {section==='command'&&result.data.data.evidenceReadiness&&<FounderHome readiness={result.data.data.evidenceReadiness} sources={result.data.data.sources||[]} delivery={result.data.data.delivery||{}}/>}
        {section==='customers'&&<><div className="row"><Link href="/control/workspaces">Browse Workspaces →</Link></div><section className="panel"><Table title="Users · safe metadata (up to 200)" rows={result.data.data.users||[]} columns={['user_id','deleted','workspace_count','last_seen_at']} select={row=>setSelectedUser(String(row.user_id))}/></section>{selectedUser&&<section className="panel" aria-label="User 360"><h2>User 360</h2>{user.error?<p role="alert">{user.error.message}</p>:user.data?<><Table title="Account metadata" rows={user.data.data.user?[user.data.data.user]:[]} columns={['user_id','deleted','workspace_count','last_seen_at']}/><Table title="Memberships" rows={user.data.data.memberships||[]} columns={['workspace_id','role','status']}/><p>Private customer content: suppressed. A scoped support grant is required.</p><p>Financial, suspension, deletion, and impersonation actions are disabled.</p></>:<p role="status">Loading safe account context…</p>}<button onClick={()=>setSelectedUser('')}>Close User 360</button></section>}</>}
        {section==='workspaces'&&<section className="panel"><Table title="Workspaces · safe metadata (up to 200)" rows={result.data.data.workspaces||[]} columns={['id','created_at','member_count','subscription_status','plan','terms_version']}/></section>}
        {section==='engineering'&&<ChecksJourney csrf={session.data!.data.csrfToken}/>}
        {section==='settings'&&<><section className="panel"><h2>Access & policies</h2><p>Read access follows the current server-held operator record. Capability removal and auth epoch changes take effect on the next request.</p><p>30-minute idle timeout · 8-hour absolute timeout · sensitive step-up proof expires after 5 minutes.</p><p>Metric definitions and scheduled investigators remain proposed and disabled.</p></section><section className="panel"><Table title="Admin audit · latest 200 events" rows={result.data.data.events||[]} columns={['occurred_at','actor','action','result','error_code','request_id']}/></section></>}
        {['revenue','product','infrastructure','support'].includes(section)&&<Definitions section={section} data={result.data.data} csrf={session.data!.data.csrfToken}/>}
        {section==='founder'&&<Founder csrf={session.data!.data.csrfToken}/>}
      </>}
      {sources.data&&section!=='command'&&<details className="panel"><summary>Data trust</summary><p className="muted small">Provider connection, freshness, and qualification are separate from source code being present.</p><div className="source-health">{sources.data.data.sources?.map(source=><div className="source-row" key={source.source_id}><div><strong>{source.source_id}</strong><div className="small muted">{source.reason_code.replaceAll('_',' ')} · watermark: {source.watermark||'unavailable'}</div></div><span className="badge">{source.state}</span></div>)}</div></details>}
    </main></div>;
}
function Table({title,rows,columns,select}:{title:string;rows:SafeRow[];columns:string[];select?:(row:SafeRow)=>void}) {
  return <div className={columns.length>7?"table-scroll metric-evidence":"table-scroll"} tabIndex={0} role="region" aria-label={title}><table><caption>{title}</caption><thead><tr>{columns.map(name=><th key={name} scope="col">{name.replaceAll('_',' ')}</th>)}{select&&<th scope="col">Investigate</th>}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(name=><td key={name}>{row[name]===null?'Unavailable':typeof row[name]==='boolean'?(row[name]?'Yes':'No'):String(row[name]??'Unavailable')}</td>)}{select&&<td><button onClick={()=>select(row)} aria-label={'Open User 360 for '+row.user_id}>User 360</button></td>}</tr>)}</tbody></table>{!rows.length&&<p className="empty">No qualified records are available in this view.</p>}</div>;
}
function MetricQuery({id,currency,csrf}:{id:string;currency:boolean;csrf:string}) {
  const [result,setResult]=useState<QueryResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[suite,setSuite]=useState(''),[answer,setAnswer]=useState<Run|null>(null);
  const epoch=useRef(0);useEffect(()=>{epoch.current++;setResult(null);setAnswer(null);setError('');setBusy(false);},[suite]);
  async function query(){const rev=++epoch.current;setResult(null);setBusy(true);setError('');setAnswer(null);try{const end=new Date(),start=new Date(end.getTime()-28*86400000);const fetched=await api<QueryResult>('/metrics/query',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({metricIds:[id],interval:{start:start.toISOString(),end:end.toISOString(),timeZone:'UTC'},groupBy:currency?['currency']:id==='check_failures'?['suite','failure_class']:[],filters:suite?[{dimension:'suite',operator:'eq',values:[suite]}]:[],comparison:'none',limit:100})});if(rev===epoch.current)setResult(fetched);}catch(failure){if(rev===epoch.current)setError(failure instanceof Error?failure.message:'Query failed.');}finally{if(rev===epoch.current)setBusy(false);}}
  async function explain(){if(!result)return;const rev=epoch.current;setBusy(true);setError('');try{const requestId=crypto.randomUUID();const accepted=await api<{statusPath:string}>('/copilot/turns',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':requestId},body:JSON.stringify({requestId,conversationId:crypto.randomUUID(),message:'Explain check failures using this receipt',contextEvidenceIds:[result.queryReceiptId],modality:'text'})});const evidence=await fetch(accepted.statusPath,{cache:'no-store'});if(!evidence.ok)throw new Error('Investigation evidence could not be read.');const answer=((await evidence.json()) as Envelope).data.run||null;if(rev===epoch.current)setAnswer(answer);}catch(failure){setError(failure instanceof Error?failure.message:'Investigation failed.');}finally{setBusy(false);}}
  return <>{id==='check_failures'&&<label>Suite filter<input value={suite} maxLength={160} onChange={event=>setSuite(event.target.value)} placeholder="All suites"/></label>}<button onClick={query} disabled={busy}>{busy?'Querying…':'Inspect last 28 days'}</button>{error&&<p role="alert">{error}</p>}{result&&<div role="status"><p className="small">Receipt: {result.queryReceiptId}</p><p>{result.warnings.join(' ')}</p><MetricChart result={result}/><Receipt id={result.queryReceiptId}/><button onClick={explain} disabled={busy}>Explain this evidence</button>{answer&&<section aria-label="Grounded query explanation"><h3>Grounded query explanation</h3><p>{answer.answerText}</p>{answer.queryReceiptIds?.map(id=><p key={id} className="small">Grounded receipt: {id}</p>)}</section>}</div>}</>;
}
function Receipt({id}:{id:string}) {
  const [receipt,setReceipt]=useState<Record<string,unknown>|null>(null),[error,setError]=useState('');
  async function inspect(){try{const result=await api<Envelope<{receipt:Record<string,unknown>}>>('/metrics/receipts/'+id);setReceipt(result.data.receipt);}catch(failure){setError(failure instanceof Error?failure.message:'Receipt unavailable.');}}
  return <details onToggle={event=>{if(event.currentTarget.open&&!receipt)void inspect();}}><summary>Receipt details</summary>{error&&<p role="alert">{error}</p>}{receipt&&<dl><dt>Query digest</dt><dd>{String(receipt.query_digest)}</dd><dt>Definition versions</dt><dd>{JSON.stringify(receipt.metric_versions)}</dd><dt>Execution</dt><dd>{String(receipt.execution_state)}</dd><dt>Source watermarks</dt><dd>{JSON.stringify(receipt.source_watermarks)}</dd><dt>Row count</dt><dd>{String(receipt.row_count)}</dd></dl>}</details>;
}
function MetricChart({result}:{result:QueryResult}) {
  const rows=result.rows.map(row=>({...row,seriesKey:Object.values(row.dimensions||{}).join(' / ')||row.metricId,dimensions:JSON.stringify(row.dimensions||{}),sourceReceiptIds:(row.sourceReceiptIds||[]).join(', ')}));
  // Incomplete and stale observations stay visible in the table; only current measured values plot.
  const points=rows.filter(row=>row.value!==null&&row.dataState==='measured');
  return <figure><figcaption>{result.executionState==='local_synthetic'?'Synthetic local source receipts. ':''}{result.dataState} · as of {result.asOf}. {points.length?'Values from query evidence. Stale and partial observations remain in the table.':'No qualified values to plot.'}</figcaption>{points.length>0&&<div className="chart" data-testid="metric-chart" aria-hidden="true"><ResponsiveContainer><BarChart data={points} accessibilityLayer={false}><XAxis dataKey="seriesKey"/><YAxis/><Tooltip/><Bar dataKey="value" fill="#111" isAnimationActive={false}/></BarChart></ResponsiveContainer></div>}<Table title="Metric values and quality" rows={rows as unknown as SafeRow[]} columns={['metricId','dimensions','value','unit','grain','definitionVersion','dataState','sampleCount','sourceWatermark','sourceReceiptIds']}/></figure>;
}
function Definitions({section,data,csrf}:{section:string;data:Data;csrf:string}) {
  const domains:Record<string,string[]>={revenue:['Revenue'],product:['Product'],infrastructure:['AI','Reliability'],support:['Support']};
  const dashboards=data.dashboards?.filter(d=>(domains[section]||[section]).includes(d.workbench))||[];
  const ids=new Set(dashboards.flatMap(d=>d.metric_ids));
  return <><p>Definitions are versioned proposals. Values remain unavailable until the business policy and source are qualified.</p><div className="grid">{data.definitions?.filter(def=>ids.has(def.id)).map(def=><article className="card" key={def.id}><h2>{def.title}</h2><p className="metric">Unavailable</p><p className="small muted">{def.unit} · v{def.version} · {def.grain}</p><details><summary>Definition and limitations</summary><p>{def.definition}</p><p>{def.limitations}</p><MetricQuery id={def.id} currency={def.currency_policy==='native_currency_separate'} csrf={csrf}/></details></article>)}</div>{!ids.size&&<section className="panel"><h2>Investigation access</h2><p>Support grants, ticket content, customer replies, and security actions require scoped access and separate approval. They are disabled in Phase 1.</p></section>}</>;
}
function Founder({csrf}:{csrf:string}) {
  const [message,setMessage]=useState(''),[answer,setAnswer]=useState<Run|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function inspect(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const requestId=crypto.randomUUID();const accepted=await api<{statusPath:string}>('/copilot/turns',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':requestId},body:JSON.stringify({requestId,conversationId:crypto.randomUUID(),message,contextEvidenceIds:[],modality:'text'})});const receipt=await fetch(accepted.statusPath,{cache:'no-store'});if(!receipt.ok)throw new Error('Investigation evidence could not be read.');const run=await receipt.json() as Envelope;setAnswer(run.data.run||null);setMessage('');}catch(failure){setError(failure instanceof Error?failure.message:'Investigation failed.');}finally{setBusy(false);}}
  return <section className="panel"><h2>Founder Rafii</h2><p className="muted">Deterministic read-only mode. Model generation and scheduled investigations need a separately approved budget and data policy.</p><form onSubmit={inspect}><label htmlFor="question">Business question</label><textarea id="question" maxLength={16000} value={message} onChange={event=>setMessage(event.target.value)} required/><button type="submit" disabled={busy}>{busy?'Inspecting…':'Inspect evidence'}</button></form>{error&&<p role="alert">{error}</p>}{answer&&<div role="status"><h3>Evidence & limitations</h3><p>{answer.answerText}</p>{answer.queryReceiptIds?.map(id=><p className="small" key={id}>Query receipt: {id}</p>)}{answer.warnings?.map(w=><p className="muted" key={w.code}>{w.message}</p>)}</div>}<p className="small muted">No refund, ban, deletion, deployment, migration, code write, or external message can be executed here.</p></section>;
}
