'use client';
import { useRef, useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { IncidentSurface, SandboxRecords, LinkedRecords, FounderAgentPanel } from './founder-intelligence-ui';
import { Icon, PreviewCharts, CommandPalette } from './founder-preview-ui';
import { scenarios, scenarioKey, type WorkspaceData, type ListData, type Envelope, type Session, type Row } from './founder-preview-contracts';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { controlError } from '../../errors.mjs';

type Mode='live'|'demo';
const navigation=[['command','Home'],['customers','Customers'],['workspaces','Workspaces'],['billing','Billing & credits'],['support','Support'],['product','Product'],['settings','Connections']];
const headings:Record<string,[string,string]>={command:['Your founder workspace','A clear view of the business, what needs attention, and your next step.'],customers:['Customers','Find an account and follow its workspace, billing and activity.'],workspaces:['Workspaces','See who is using Rafii and the plan supporting each workspace.'],billing:['Billing & credits','Review subscriptions, stored payments and usage.'],support:['Support','Follow requests from the customer to their workspace.'],product:['Product','Understand workspace activity from recorded usage.'],settings:['Connections','Manage readiness in one place. Required connections must be verified before release.'],advanced:['Advanced','Evidence, delivery checks and audit tools when you need them.']};
async function request<T>(path:string,options:RequestInit={}):Promise<Envelope<T>>{
 const response=await fetch('/api/control/v2'+path,{...options,credentials:'same-origin',cache:'no-store'});
 if(!response.ok){const body=await response.json().catch(()=>({code:''}));if(response.status===401)window.location.assign('/sign-in');throw new Error(path.startsWith('/workspace')&&response.status===503?(body.code==='WORKSPACE_CONFIGURATION_REQUIRED'?'Required database setup is incomplete. Live access must be qualified before records can be shown.':body.code==='WORKSPACE_ACCESS_REQUIRED'?'The database connection cannot read the required records. Review secure access configuration and retry.':'Rafii records could not be read. Retry the connection; Live values have not been substituted.'):controlError(response.status,body.code));}
 return response.json();
}
function href(section:string,mode:Mode,record?:string){return '/control/'+section+'?mode='+mode+(record?'&record='+encodeURIComponent(record):'');}
function label(row:Row){return String(row.name||row.title||row.plan||row.label||(row.dimension?state(row.dimension):'Unnamed record'));}
function money(amount:unknown,currency:unknown){return typeof amount==='number'||typeof amount==='string'?new Intl.NumberFormat('en',{style:'currency',currency:String(currency||'USD')}).format(Number(amount)/100):'Terms not approved';}
const detailLabels:Record<string,string>={ownerId:'Owner reference',workspaceId:'Workspace reference',memberCount:'Members',amountMinor:'Amount',actualUsdMicro:'Recorded cost (USD)',costState:'Cost status',termsStatus:'Price approval',createdAt:'Created',renewsAt:'Renewal date',at:'Recorded'};
function recordedCost(value:unknown){const amount=Number(value);return Number.isFinite(amount)?new Intl.NumberFormat('en',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:6}).format(amount/1000000):'Not recorded';}
function when(value:unknown){return typeof value==='string'?new Date(value).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}):'Not recorded';}
function state(value:unknown){return String(value||'Not recorded').replaceAll('_',' ');}
export default function FounderWorkspace({section,mode,record,initialPlan="all"}:{section:string;mode:Mode;record?:string;initialPlan?:string}){
 const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,staleTime:0,gcTime:0}}}));
 return <QueryClientProvider client={client}><Workspace key={mode} section={section} mode={mode} record={record} initialPlan={initialPlan}/></QueryClientProvider>;
}
function Workspace({section,mode,record,initialPlan}:{section:string;mode:Mode;record?:string;initialPlan:string}){
 const router=useRouter();
 const [plan,setPlan]=useState(initialPlan),[cycle,setCycle]=useState('all'),[sort,setSort]=useState('name'),[direction,setDirection]=useState('asc'),[commandOpen,setCommandOpen]=useState(false),[agentOpen,setAgentOpen]=useState(false),[agentPrompt,setAgentPrompt]=useState(''),[agentEntity,setAgentEntity]=useState<Row|null>(null),[homeTab,setHomeTab]=useState('overview'),[showIds,setShowIds]=useState(true),[selectedIds,setSelectedIds]=useState<string[]>([]);
 useEffect(()=>{function onKey(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setCommandOpen(v=>!v);}}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[]);
 const [search,setSearch]=useState(''),[settledSearch,setSettledSearch]=useState(''),[page,setPage]=useState(1),[filter,setFilter]=useState('all'),[tab,setTab]=useState(record?.startsWith('invoice-')?'invoices':record?.startsWith('payment-')?'payments':'subscriptions'),[selected,setSelected]=useState<Row|null>(null),[notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>setSettledSearch(search),200);return()=>clearTimeout(timer);},[search]);
 const pending=useRef<{signature:string;body:Record<string,unknown>}|null>(null),dialog=useRef<HTMLDialogElement>(null),openedRecord=useRef('');
 const session=useQuery({queryKey:['session'],queryFn:()=>request<Session>('/session')});
 const result=useQuery({queryKey:['workspace',mode],enabled:!!session.data,queryFn:async({signal})=>{const r=await request<WorkspaceData>('/workspace/'+mode,{signal});if(r.data.mode!==mode||!Array.isArray(r.data.customers)||!Array.isArray(r.data.workspaces))throw new Error('Workspace response could not be verified. Reload or check Connections.');return r;}});
 const data=!session.error&&!result.error?result.data?.data:undefined;
 const isList=['customers','workspaces','billing','support','product'].includes(section);
 const collectionName=section==='customers'?'customers':section==='workspaces'?'workspaces':section==='support'?'tickets':section==='product'?'usage':tab;
 const listReady=!!data&&isList&&!(section==='billing'&&tab==='payments'&&data.paymentState==='not_configured');
 const listing=useQuery({queryKey:['records',mode,collectionName,settledSearch,filter,page,record||'',plan,cycle,sort,direction,data?.revision],enabled:listReady,queryFn:async({signal})=>{const r=await request<ListData>('/workspace/'+mode+'/query',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data!.data.csrfToken},signal,body:JSON.stringify({collection:collectionName,search:settledSearch,status:filter,page,recordId:record||'',...(mode==='demo'?{plan,billingCycle:cycle,sort,direction}:{})})});if(r.data.mode!==mode||!Array.isArray(r.data.rows)||!Array.isArray(r.data.workspaces)||typeof r.data.total!=='number')throw new Error('Record response could not be verified. Retry the search.');return r;}});
 const list=!listing.error&&listReady&&search===settledSearch?listing.data?.data:undefined;
 useEffect(()=>{setSelectedIds([]);},[mode,filter,plan,cycle,settledSearch,page]);
 const detailQuery=useQuery({queryKey:['detail',mode,collectionName,selected?.id,data?.revision],enabled:!!selected&&!!session.data&&!!data,queryFn:({signal})=>request<ListData>('/workspace/'+mode+'/query',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data!.data.csrfToken},signal,body:JSON.stringify({collection:collectionName,search:'',status:'all',page:1,recordId:selected!.id})})});
 const linked=detailQuery.data?.data.linkedRecords;
 function ask(text:string){setAgentEntity(selected);dialog.current?.close();setAgentPrompt(text);setAgentOpen(true);}
 const title=headings[section]||headings.command;
 function open(row:Row){window.history.pushState(null,'',href(section,mode,row.id));setSelected(row);setName(String(row.name||''));setActionError('');pending.current=null;dialog.current?.showModal();}
 useEffect(()=>{if(record&&list&&openedRecord.current!==mode+record){const row=list.rows.find(r=>r.id===record);if(row){openedRecord.current=mode+record;setSelected(row);setName(String(row.name||''));dialog.current?.showModal();}}},[record,list,mode]);
 useEffect(()=>{if(!record){openedRecord.current='';dialog.current?.close();}},[record]);
 useEffect(()=>{
  function back(){const id=new URLSearchParams(window.location.search).get('record');if(!id){dialog.current?.close();openedRecord.current='';return;}const row=list?.rows.find(r=>r.id===id);if(row){setSelected(row);setName(String(row.name||''));if(!dialog.current?.open)dialog.current?.showModal();}else router.refresh();}
  window.addEventListener('popstate',back);return()=>window.removeEventListener('popstate',back);
 },[list,router]);
 async function mutate(action:string,targetId:string,value='',keepOpen=false){
  if(!data||!session.data||busy)return;setBusy(true);setNotice('');setActionError('');
  const isRename=mode==='live'&&action==='rename_workspace';
  const payload=isRename?{workspaceId:targetId,name:value,revision:selected?.revision}:{action,targetId,value,revision:data.revision};
  const signature=JSON.stringify(payload);
  if(pending.current?.signature!==signature)pending.current={signature,body:{...payload,requestId:crypto.randomUUID()}};
  try{const saved=await request<Record<string,unknown>>(isRename?'/workspace/live/rename':'/workspace/demo/action',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.data.csrfToken},body:JSON.stringify(pending.current.body)});if(isRename?(saved.data.workspaceId!==targetId||saved.data.name!==value.trim()||typeof saved.data.revision!=='number'):(saved.data.mode!=='demo'||typeof saved.data.revision!=='number'||saved.data.revision<=data.revision))throw new Error('The save response could not be verified. Retry the same action.');pending.current=null;if(!keepOpen){dialog.current?.close();setSelected(null);}await result.refetch();if(listReady)await listing.refetch();setNotice(mode==='demo'?'Sandbox saved. No real emails, calls or account changes.':'Workspace name saved in Rafii.');return true;}
  catch(e){setActionError(e instanceof Error?e.message:'Save could not be confirmed. Retry the same action.');return false;}
  finally{setBusy(false);}
 }
 async function logout(){if(!session.data)return;setBusy(true);try{await request('/session/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.data.csrfToken},body:'{}'});window.location.assign('/sign-in');}catch{setActionError('Sign-out could not be confirmed. Retry.');setBusy(false);}}
 const workspaceName=(id:unknown)=>String((list?.workspaces.find(w=>w.id===id)||data?.workspaces.find(w=>w.id===id))?.name||'Unnamed workspace');
 const needs=data?.workspaces.filter(w=>['past_due','grace'].includes(String(w.status)))||[];
 const billingReviews=data?.summary.billingReviews??needs.length;
 const collection=list?.rows||[];
 const links=<><p className="nav-group">Workspace</p>{navigation.map(([id,text])=><Link key={id} href={href(id,mode)} aria-current={section===id?'page':undefined}><Icon name={id==='command'?'home':id}/><span>{text}</span>{id==='customers'&&data?.summary.customers?<small>{data.summary.customers.toLocaleString()}</small>:null}</Link>)}<Link href={href('advanced',mode)} aria-current={section==='advanced'?'page':undefined}><Icon name="advanced"/>Advanced</Link></>;
 return <div className={'fc layout'+(agentOpen?' agent-is-open':'')}><aside className="sidebar"><Link className="brand" href={href('command',mode)}>rafii<span>Founder Control</span></Link><nav className="desktop-nav" aria-label="Founder navigation">{links}</nav><details className="fc-mobile-nav"><summary>Menu · {section==='command'?'Home':title[0]}</summary><nav aria-label="Mobile founder navigation">{links}</nav></details><div className="sidebar-footer"><div className="founder-profile"><span className="avatar">J</span><div><strong>Founder workspace</strong><small>{mode==='demo'?'Demo · isolated data':'Verified founder access'}</small></div></div></div></aside>
 <main id="main" className="workspace" tabIndex={-1}><header className="topbar"><div className="header-context"><span className="breadcrumb">Workspace <span>/</span> <strong>{section==='command'?'Home':title[0]}</strong></span><button className="quiet search-trigger" onClick={()=>setCommandOpen(true)}><Icon name="search"/><span>Search pages & customers…</span><kbd>⌘ K</kbd></button></div><div className="header-actions"><span className="environment-badge">{session.data?.environment||'Checking environment'}</span><div className="mode-switch" aria-label="Workspace mode"><Link href={href(section,'live')} aria-current={mode==='live'?'page':undefined}>Live</Link><Link href={href(section,'demo')} aria-current={mode==='demo'?'page':undefined}>Demo</Link></div><button className="ask-button" onClick={()=>{setAgentEntity(null);setAgentOpen(true);}}><Icon name="spark"/>Ask Rafii</button><button className="quiet icon-action" onClick={logout} disabled={busy||!session.data} aria-label="Sign out"><Icon name="logout"/></button></div></header>
 {mode==='demo'&&<div className="demo-banner"><div className="demo-caption"><span className="badge demo-badge">Demo</span><div><strong>10,000 fictional subscribers. One connected story.</strong><p>Sandbox data & delivery · no real accounts, emails or calls</p></div></div><div className="scenario-controls"><label htmlFor="scenario">Scenario</label><select id="scenario" value={scenarioKey(data)} disabled={busy||!data} onChange={e=>{setSelected(null);setAgentEntity(null);dialog.current?.close();void mutate('set_scenario','scenario',e.target.value,true);}}>{scenarios.map(([id,text])=><option key={id} value={id}>{text}</option>)}</select><button className="quiet" onClick={()=>mutate('reset','all')} disabled={busy||!data}>Reset Demo</button></div></div>}
 <div className="heading"><p className="eyebrow">{mode==='demo'?'Explore Rafii':'Founder Control'}</p><h1>{section==='command'?'Your business, at a glance.':title[0]}</h1><p>{title[1]}</p></div>
 {notice&&<p role="status" className="success">{notice}</p>}{actionError&&!selected&&<p role="alert" className="error">{actionError}</p>}
 {(session.error||result.error)&&<section className="error" role="alert"><h2>Workspace could not be loaded</h2><p>{(session.error||result.error)?.message}</p><p>Live records are unavailable until this connection succeeds.</p><button onClick={()=>session.error?session.refetch():result.refetch()}>Retry connection</button></section>}
 {!data&&!session.error&&!result.error&&<div className="loading" role="status">{session.data?'Loading workspace records…':'Verifying your founder session…'}</div>}
 {data&&<>
 {data.receipt?.dataState==='stale'&&<section className="connection-note stale-warning" role="status"><h2>Source data is stale</h2><p>Last good snapshot: {new Date(String(data.receipt.lastGoodAsOf||data.receipt.asOf)).toLocaleString()}. These values are preserved evidence, not a measured business decline.</p><Link href={href('settings',mode)}>Review source readiness →</Link></section>}
 {section==='command'&&<><div className="tabs home-tabs" role="group" aria-label="Home view">{[['overview','Overview'],['followups','Follow-ups'],['reports','Reports']].map(([id,text])=><button className="quiet" key={id} aria-pressed={homeTab===id} onClick={()=>setHomeTab(id)}>{text}</button>)}</div>
 {homeTab==='overview'&&<><section className="today-brief"><span className="brief-icon"><Icon name="spark" size={22}/></span><div><p className="eyebrow">Today's brief · {mode==='demo'?'Demo evidence':'Live records'}</p><h2>{scenarioKey(data)==='normal'?'A steady day. Your next opportunity is in the details.':scenarioKey(data)==='recovery'?'Service recovered. Keep the follow-through visible.':'An issue needs your attention.'}</h2><p>{scenarioKey(data)==='normal'?`${data.summary.customers.toLocaleString()} fictional customers across Rafii's paid plans. Review the mix, explore an account, or ask Rafii what the numbers mean.`:'Review the incident, affected accounts and notification timeline below. All scenario effects stay in this sandbox.'}</p></div><button className="quiet" onClick={()=>ask('Give me a founder brief for this scenario: what changed, who is affected and what should I do next?')}>Ask about today <Icon name="arrow"/></button></section>
 <div className="grid metric-grid">{[['Paid subscribers',Number(data.summary.currentPaidSubscriptions??data.summary.activeSubscriptions),'customers','customers'],['Monthly recurring revenue',typeof data.summary.mrrMinor==='number'?money(data.summary.mrrMinor,'USD'):'Source not qualified','billing','billing'],['Support backlog',data.summary.openRequests,'support','support'],['Credit usage',typeof data.summary.creditsUsed==='number'?Number(data.summary.creditsUsed).toLocaleString():'Source not qualified','product','product']].map(([text,value,to,icon])=><Link className="card metric-link" key={String(text)} href={href(String(to),mode)}><span>{text}<Icon name={String(icon)}/></span><strong>{typeof value==='number'?value.toLocaleString():String(value)}</strong><span className="small muted">{mode==='demo'?'Simulated · dataset total':'Live · qualified source'} <span>↗</span></span></Link>)}</div>
 {mode==='demo'&&<PreviewCharts data={data} ask={ask} onPlan={id=>router.push(href('customers',mode)+'&plan='+encodeURIComponent(id))}/>}
 <IncidentSurface data={data} ask={ask} mutate={mutate} busy={busy}/>
 <div className="home-columns"><section className="panel"><div className="panel-heading"><div><h2>Needs attention</h2><p className="small muted">The next decisions, with their context</p></div><Link href={href('support',mode)}>View support →</Link></div>{needs.slice(0,3).map(w=><Link className="attention-row" key={w.id} href={href('workspaces',mode,w.id)}><span><strong>{label(w)}</strong><small>Review billing status</small></span><span className="badge warning">{state(w.status)}</span></Link>)}{data.tickets.filter(t=>['open','requested'].includes(String(t.status))).slice(0,Math.max(0,5-needs.length)).map(t=><Link className="attention-row" key={t.id} href={href('support',mode,t.id)}><span><strong>{label(t)}</strong><small>{workspaceName(t.workspaceId)}</small></span><span>→</span></Link>)}{!billingReviews&&!data.summary.openRequests&&<p className="empty">No outstanding requests or past-due subscriptions.</p>}</section><section className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p className="small muted">A traceable record of your sandbox</p></div><span className="badge">{mode}</span></div>{data.activity.slice(0,5).map(r=><div className="activity-row" key={r.id}><span>{state(r.label)}</span><small>{when(r.at)}</small></div>)}{!data.activity.length&&<p className="empty">No Founder Control actions have been recorded.</p>}</section></div>
 <p className="small muted dataset-footnote">{mode==='demo'?'Source-backed v2 plan catalog · proposed prices · production activation unverified. Fictional operations, monthly billing only.':`Records refreshed ${new Date(result.data!.asOf).toLocaleString()}. Revenue definitions must be approved separately.`} · Revision {data.revision}</p></>}
 {homeTab!=='overview'&&<SandboxRecords data={data} kind={homeTab} mutate={mutate} busy={busy} ask={ask}/>}
 </>}
 {['customers','workspaces','billing','support','product'].includes(section)&&<>
 {section==='billing'&&<div className="tabs" role="group" aria-label="Billing view">{(mode==='demo'?['subscriptions','invoices','payments','usage']:['subscriptions','payments','usage']).map(t=><button className="quiet" key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setSearch('');setSettledSearch('');setFilter('all');setPage(1);}}>{t==='subscriptions'?'Subscriptions':t==='invoices'?'Invoices':t==='payments'?'Payments':'Credit & usage activity'}</button>)}</div>}
 {section==='billing'&&tab==='payments'&&data.paymentState==='not_configured'&&<div className="connection-note"><h2>Payment receipts are not connected</h2><p>The payment records connection needs setup. No payments have been counted yet.</p><Link href={href('settings',mode)}>Review Connections →</Link></div>}
 {section==='support'&&mode==='live'&&<p className="connection-note">Showing account requests. Customer conversations and replies need the approved support connection.</p>}
 {section==='billing'&&tab==='usage'&&mode==='live'&&<p className="connection-note">Showing recorded usage. Available credits cannot be shown until the credit terms and balance calculation are approved.</p>}
 <section className="panel records"><div className="table-options"><span>{selectedIds.length?`${selectedIds.length} selected · this page only`:"All results are searched on the server"}</span><label><input type="checkbox" checked={showIds} onChange={e=>setShowIds(e.target.checked)}/> Show identifiers</label></div>{record&&<p><Link href={href(section,mode)}>View all {section} →</Link></p>}<div className="toolbar"><label>Search {section==='billing'?tab:section}<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search names, email or record IDs"/></label>{!['product'].includes(section)&&<label>Status<select aria-label="Status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All statuses</option>{(list?.statuses||[]).map(s=><option key={s} value={s}>{state(s)}</option>)}</select></label>}{mode==='demo'&&<><label>Plan<select aria-label="Plan" value={plan} onChange={e=>{setPlan(e.target.value);setPage(1);}}><option value="all">All paid plans</option>{data.catalog?.plans?.filter(p=>Number(p.monthlyPriceCents||p.monthlyPriceMinor||p.amountMinor)>0).map(p=><option key={p.id} value={p.id}>{String(p.name||p.plan||p.id)}</option>)}</select></label><label>Billing cycle<select aria-label="Billing cycle" value={cycle} onChange={e=>{setCycle(e.target.value);setPage(1);}}><option value="all">All cycles</option><option value="monthly">Monthly</option></select></label><label>Sort<select aria-label="Sort records" value={sort+':'+direction} onChange={e=>{const [s,d]=e.target.value.split(':');setSort(s);setDirection(d);setPage(1);}}><option value="name:asc">Name A–Z</option><option value="name:desc">Name Z–A</option><option value="id:asc">Record ID</option><option value="createdAt:desc">Newest first</option></select></label></>}<span className="small muted">{list?`${collection.length} of ${list.total.toLocaleString()} records`:'Loading records…'}</span></div>
 {listing.error&&<div className="error" role="alert"><h2>Records could not be loaded</h2><p>{listing.error.message}</p><button onClick={()=>listing.refetch()}>Retry search</button></div>}{listReady&&!list&&!listing.error&&<p role="status">Searching records…</p>}
 {list&&<><div className="table-scroll" role="region" tabIndex={0} aria-label={title[0]+' records'}><table><caption className="sr-only">{title[0]} · {mode==='demo'?'fictional sample data':'Live records'}</caption><thead><tr><th scope="col"><input type="checkbox" aria-label="Select this page" checked={collection.length>0&&selectedIds.length===collection.length} onChange={e=>setSelectedIds(e.target.checked?collection.map(r=>r.id):[])}/></th><th scope="col">{section==='customers'?'Customer':section==='workspaces'?'Workspace':section==='support'?'Request':section==='product'||tab==='usage'?'Activity':'Workspace'}</th><th scope="col">{section==='customers'?'Workspaces':section==='workspaces'?'Plan':section==='support'?'Workspace':section==='product'||tab==='usage'?'Usage':'Amount'}</th><th scope="col">{section==='product'||tab==='usage'?'Cost quality':'Status'}</th><th scope="col">Details</th></tr></thead><tbody>{collection.map(r=><tr key={r.id}><td><input type="checkbox" aria-label={'Select '+label(r)} checked={selectedIds.includes(r.id)} onChange={e=>setSelectedIds(ids=>e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/></td><td><strong>{section==='billing'?workspaceName(r.workspaceId):label(r)}</strong>{showIds&&<small className="record-id">{String(r.email||r.id)}</small>}</td><td>{section==='customers'?<><span className="badge">{String(r.plan||'')}</span>{((r.workspaceIds as string[])||[]).map(id=><Link className="inline-link" key={id} href={href('workspaces',mode,id)}>{workspaceName(id)}</Link>)}</>:section==='workspaces'?String(r.plan||'No subscription'):section==='support'?workspaceName(r.workspaceId):section==='product'||tab==='usage'?`${r.quantity} ${r.unit} · ${workspaceName(r.workspaceId)}`:money(r.amountMinor,r.currency)}</td><td><span className={'badge status-'+String(r.status||r.costState)}>{state(r.status||r.costState)}</span></td><td><button className="quiet" onClick={()=>open(r)} aria-label={'Open '+label(r)}>Open →</button></td></tr>)}</tbody></table></div>{!collection.length&&<div className="empty"><h3>{search||filter!=='all'?'No matching records':'No records yet'}</h3><p>{search||filter!=='all'?'Try a different search or status.':'This connected view returned no records.'}</p>{(search||filter!=='all')&&<button className="quiet" onClick={()=>{setSearch('');setSettledSearch('');setFilter('all');setPlan('all');setCycle('all');setPage(1);}}>Clear filters</button>}</div>}<div className="pagination" aria-label="Record pages"><button className="quiet" disabled={page===1||listing.isFetching} onClick={()=>setPage(p=>p-1)}>Previous page</button><span className="small muted">Page {page} of {Math.max(1,Math.ceil(list.total/list.pageSize))}</span><button className="quiet" disabled={page*list.pageSize>=list.total||listing.isFetching} onClick={()=>setPage(p=>p+1)}>Next page</button></div></>}</section></>}
 {section==='settings'&&<section className="panel"><h2>Connection readiness</h2>{data.connections.map(c=><div className="connection-row" key={c.id}><div><h3>{c.label}{c.required?' · Required':''}</h3><p>{c.detail}</p></div><span className="badge">{['not_qualified','not_configured'].includes(c.state)?'Setup required':c.state==='metadata_only'?'Account requests only':state(c.state)}</span></div>)}<div className="connection-row"><div><h3>Founder identity · Required</h3><p>Your session passed founder authorization and second-factor verification.</p></div><span className="badge live-badge">Verified</span></div><p className="small muted">Secrets and operator enrollment use the existing secure configuration process. No integrations are enabled by visiting this page.</p><Link href="/control/audit">View access policies and audit →</Link></section>}
 {section==='advanced'&&<section className="panel"><h2>Evidence & operations</h2><p>These tools query Live engineering evidence. Demo business actions remain isolated.</p><div className="advanced-links">{[['evidence','Delivery overview'],['engineering','GitHub checks & receipts'],['founder','Founder investigation'],['audit','Access & audit'],['infrastructure','Infrastructure definitions']].map(([id,text])=><Link key={id} href={'/control/'+id}>{text} →</Link>)}</div></section>}
 </>}
 <dialog ref={dialog} className="detail-dialog" onClose={()=>{setSelected(null);setActionError('');pending.current=null;if(window.location.search.includes('record='))window.history.replaceState(null,'',href(section,mode));}}><div className="panel-heading"><h2>{selected?label(selected):'Record details'}</h2><button className="quiet" onClick={()=>dialog.current?.close()} aria-label="Close details">Close</button></div>{selected&&<><button className="quiet" onClick={()=>ask('Explain '+label(selected)+' and its linked billing, usage and support records.')}><Icon name="spark"/> Ask Rafii about this account</button><p className="small muted">{mode==='demo'?'Demo · Fictional record':'Live record'} · {selected.id}</p><dl>{Object.entries(selected).filter(([k,v])=>!['id','renameAllowed','workspaceIds','sourceId','revision','currency'].includes(k)&&v!==null&&typeof v!=='object').map(([k,v])=><div key={k}><dt>{detailLabels[k]||k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</dt><dd>{k==='amountMinor'?money(v,selected.currency):k==='actualUsdMicro'?recordedCost(v):['createdAt','renewsAt','at'].includes(k)?when(v):state(v)}</dd></div>)}</dl>{!!selected.workspaceId&&<Link className="primary-action" href={href('workspaces',mode,String(selected.workspaceId))}>Open workspace →</Link>}
 {section==='workspaces'&&!!selected.renameAllowed&&<form onSubmit={e=>{e.preventDefault();void mutate('rename_workspace',selected.id,name);}}><label htmlFor="workspace-name">Workspace name<input id="workspace-name" value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><p className="small muted">{mode==='demo'?'Changes only this sample workspace.':'Approved test workspace only. This changes the name in Rafii; restore its original name after verification.'}</p><button type="submit" disabled={busy}>{busy?'Saving…':pending.current?'Retry save':'Save name'}</button></form>}
 {mode==='demo'&&section==='support'&&<button onClick={()=>mutate(selected.status==='completed'?'reopen_ticket':'resolve_ticket',selected.id)} disabled={busy}>{selected.status==='completed'?'Reopen sample request':'Resolve sample request'}</button>}
 {mode==='demo'&&section==='billing'&&tab==='payments'&&selected.status==='pending'&&<button onClick={()=>mutate('simulate_payment',selected.id)} disabled={busy}>Simulate successful payment</button>}
 {detailQuery.isFetching&&<p role="status">Loading linked records…</p>}{detailQuery.error&&<p role="alert">Linked records could not be loaded.</p>}{linked&&<LinkedRecords linked={linked} mode={mode}/>}<div className="detail-footer"><Link href={href('customers',mode)}>Customers</Link><Link href={href('billing',mode)}>Billing</Link><Link href={href('support',mode)}>Support</Link></div>{actionError&&<p role="alert" className="error">{actionError}</p>}</>}</dialog>
 <CommandPalette open={commandOpen} close={()=>setCommandOpen(false)} mode={mode} csrf={session.data?.data.csrfToken} navigate={(destination,id)=>router.push(href(destination,mode,id))}/>
 <FounderAgentPanel open={agentOpen} close={()=>{setAgentOpen(false);setAgentPrompt('');}} data={data} mode={mode} initialPrompt={agentPrompt} mutate={mutate} busy={busy} section={section} selected={agentEntity} environment={session.data?.environment||'local'} actionError={actionError}/>
 </main></div>;
}
