'use client';
import { useRef, useState, useEffect } from 'react';
import Link from 'next/link';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { controlError } from '../../errors.mjs';

type Row=Record<string,unknown> & {id:string};
type WorkspaceData={mode:'live'|'demo';revision:number;customers:Row[];workspaces:Row[];subscriptions:Row[];payments:Row[];usage:Row[];tickets:Row[];activity:Row[];connections:{id:string;label:string;state:string;required:boolean;detail:string}[];summary:{customers:number;workspaces:number;activeSubscriptions:number;openRequests:number;billingReviews?:number};limits:{pageSize:number;truncated:boolean};paymentState:string;supportState:string;usageState:string};
type ListData={mode:'live'|'demo';rows:Row[];workspaces:Row[];total:number;page:number;pageSize:number;statuses:string[]};
type Envelope<T>={requestId:string;environment:string;asOf:string;data:T};
type Session={csrfToken:string;capabilities:string[]};
type Mode='live'|'demo';
const navigation=[['command','Home'],['customers','Customers'],['workspaces','Workspaces'],['billing','Billing & credits'],['support','Support'],['product','Product'],['settings','Connections']];
const headings:Record<string,[string,string]>={command:['Your founder workspace','A clear view of the business, what needs attention, and your next step.'],customers:['Customers','Find an account and follow its workspace, billing and activity.'],workspaces:['Workspaces','See who is using Rafii and the plan supporting each workspace.'],billing:['Billing & credits','Review subscriptions, stored payments and usage.'],support:['Support','Follow requests from the customer to their workspace.'],product:['Product','Understand workspace activity from recorded usage.'],settings:['Connections','Manage readiness in one place. Required connections must be verified before release.'],advanced:['Advanced','Evidence, delivery checks and audit tools when you need them.']};
async function request<T>(path:string,options:RequestInit={}):Promise<Envelope<T>>{
 const response=await fetch('/api/control/v2'+path,{...options,credentials:'same-origin',cache:'no-store'});
 if(!response.ok){const body=await response.json().catch(()=>({code:''}));if(response.status===401)window.location.assign('/sign-in');throw new Error(path.startsWith('/workspace')&&response.status===503?(body.code==='WORKSPACE_CONFIGURATION_REQUIRED'?'Required database setup is incomplete. Live access must be qualified before records can be shown.':body.code==='WORKSPACE_ACCESS_REQUIRED'?'The database connection cannot read the required records. Review secure access configuration and retry.':'Rafii records could not be read. Retry the connection; Live values have not been substituted.'):controlError(response.status,body.code));}
 return response.json();
}
function href(section:string,mode:Mode,record?:string){return '/control/'+section+'?mode='+mode+(record?'&record='+encodeURIComponent(record):'');}
function label(row:Row){return String(row.name||row.title||row.plan||row.label||row.dimension||'Unnamed record');}
function money(amount:unknown,currency:unknown){return typeof amount==='number'||typeof amount==='string'?new Intl.NumberFormat('en',{style:'currency',currency:String(currency||'USD')}).format(Number(amount)/100):'Terms not approved';}
function when(value:unknown){return typeof value==='string'?new Date(value).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'}):'Not recorded';}
function state(value:unknown){return String(value||'Not recorded').replaceAll('_',' ');}
export default function FounderWorkspace({section,mode,record}:{section:string;mode:Mode;record?:string}){
 const [client]=useState(()=>new QueryClient({defaultOptions:{queries:{retry:false,staleTime:0,gcTime:0}}}));
 return <QueryClientProvider client={client}><Workspace section={section} mode={mode} record={record}/></QueryClientProvider>;
}
function Workspace({section,mode,record}:{section:string;mode:Mode;record?:string}){
 const [search,setSearch]=useState(''),[settledSearch,setSettledSearch]=useState(''),[page,setPage]=useState(1),[filter,setFilter]=useState('all'),[tab,setTab]=useState('subscriptions'),[selected,setSelected]=useState<Row|null>(null),[notice,setNotice]=useState(''),[actionError,setActionError]=useState(''),[busy,setBusy]=useState(false),[name,setName]=useState('');
 useEffect(()=>{const timer=setTimeout(()=>setSettledSearch(search),200);return()=>clearTimeout(timer);},[search]);
 const pending=useRef<{signature:string;body:Record<string,unknown>}|null>(null),dialog=useRef<HTMLDialogElement>(null),openedRecord=useRef('');
 const session=useQuery({queryKey:['session'],queryFn:()=>request<Session>('/session')});
 const result=useQuery({queryKey:['workspace',mode],enabled:!!session.data,queryFn:async()=>{const r=await request<WorkspaceData>('/workspace/'+mode);if(r.data.mode!==mode||!Array.isArray(r.data.customers)||!Array.isArray(r.data.workspaces))throw new Error('Workspace response could not be verified. Reload or check Connections.');return r;}});
 const data=!session.error&&!result.error?result.data?.data:undefined;
 const isList=['customers','workspaces','billing','support','product'].includes(section);
 const collectionName=section==='customers'?'customers':section==='workspaces'?'workspaces':section==='support'?'tickets':section==='product'?'usage':tab;
 const listReady=!!data&&isList&&!(section==='billing'&&tab==='payments'&&data.paymentState==='not_configured');
 const listing=useQuery({queryKey:['records',mode,collectionName,settledSearch,filter,page,record||''],enabled:listReady,queryFn:async()=>{const r=await request<ListData>('/workspace/'+mode+'/query',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data!.data.csrfToken},body:JSON.stringify({collection:collectionName,search:settledSearch,status:filter,page,recordId:record||''})});if(r.data.mode!==mode||!Array.isArray(r.data.rows)||!Array.isArray(r.data.workspaces)||typeof r.data.total!=='number')throw new Error('Record response could not be verified. Retry the search.');return r;}});
 const list=!listing.error&&listReady&&search===settledSearch?listing.data?.data:undefined;
 const title=headings[section]||headings.command;
 function open(row:Row){setSelected(row);setName(String(row.name||''));setActionError('');pending.current=null;dialog.current?.showModal();}
 useEffect(()=>{if(record&&list&&openedRecord.current!==mode+record){const row=list.rows.find(r=>r.id===record);if(row){openedRecord.current=mode+record;setSelected(row);setName(String(row.name||''));dialog.current?.showModal();}}},[record,list,mode]);
 async function mutate(action:string,targetId:string,value=''){
  if(!data||!session.data||busy)return;setBusy(true);setNotice('');setActionError('');
  const isRename=mode==='live'&&action==='rename_workspace';
  const payload=isRename?{workspaceId:targetId,name:value,revision:selected?.revision}:{action,targetId,value,revision:data.revision};
  const signature=JSON.stringify(payload);
  if(pending.current?.signature!==signature)pending.current={signature,body:{...payload,requestId:crypto.randomUUID()}};
  try{const saved=await request<Record<string,unknown>>(isRename?'/workspace/live/rename':'/workspace/demo/action',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.data.csrfToken},body:JSON.stringify(pending.current.body)});if(isRename?(saved.data.workspaceId!==targetId||saved.data.name!==value.trim()||typeof saved.data.revision!=='number'):(saved.data.mode!=='demo'||typeof saved.data.revision!=='number'||saved.data.revision<=data.revision))throw new Error('The save response could not be verified. Retry the same action.');pending.current=null;dialog.current?.close();setSelected(null);await result.refetch();if(listReady)await listing.refetch();setNotice(mode==='demo'?'Demo updated. Only your sample data changed.':'Workspace name saved in Rafii.');}
  catch(e){setActionError(e instanceof Error?e.message:'Save could not be confirmed. Retry the same action.');}
  finally{setBusy(false);}
 }
 async function logout(){if(!session.data)return;setBusy(true);try{await request('/session/logout',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':session.data.data.csrfToken},body:'{}'});window.location.assign('/sign-in');}catch{setActionError('Sign-out could not be confirmed. Retry.');setBusy(false);}}
 const workspaceName=(id:unknown)=>String((list?.workspaces.find(w=>w.id===id)||data?.workspaces.find(w=>w.id===id))?.name||'Unnamed workspace');
 const needs=data?.workspaces.filter(w=>['past_due','grace'].includes(String(w.status)))||[];
 const billingReviews=data?.summary.billingReviews??needs.length;
 const collection=list?.rows||[];
 const links=<>{navigation.map(([id,text])=><Link key={id} href={href(id,mode)} aria-current={section===id?'page':undefined}>{text}</Link>)}<Link href={href('advanced',mode)} aria-current={section==='advanced'?'page':undefined}>Advanced</Link></>;
 return <div className="fc layout"><aside className="sidebar"><Link className="brand" href={href('command',mode)}>rafii<span>Founder Control</span></Link><nav className="desktop-nav" aria-label="Founder navigation">{links}</nav><details className="fc-mobile-nav"><summary>Menu · {section==='command'?'Home':title[0]}</summary><nav aria-label="Mobile founder navigation">{links}</nav></details><div className="sidebar-footer"><span className="small muted">Private founder workspace</span><span className="small muted">Verified second factor required</span></div></aside>
 <main id="main" className="workspace" tabIndex={-1}><header className="topbar"><div className="mode-switch" aria-label="Workspace mode"><Link href={href(section,'live')} aria-current={mode==='live'?'page':undefined}>Live</Link><Link href={href(section,'demo')} aria-current={mode==='demo'?'page':undefined}>Demo</Link></div><div className="row"><span className={'badge '+(mode==='demo'?'demo-badge':'live-badge')}>{mode==='demo'?'Sample data':'Live · '+(session.data?.environment||'Checking')}</span><button className="quiet" onClick={logout} disabled={busy||!session.data}>Sign out</button></div></header>
 {mode==='demo'&&<div className="demo-banner"><div><strong>Demo workspace</strong><p>Fictional customers. Actions are simulated, isolated and resettable.</p></div><button className="quiet" onClick={()=>mutate('reset','all')} disabled={busy||!data}>Reset Demo</button></div>}
 <div className="heading"><p className="eyebrow">{mode==='demo'?'Explore Rafii':'Founder Control'}</p><h1>{title[0]}</h1><p>{title[1]}</p></div>
 {notice&&<p role="status" className="success">{notice}</p>}{actionError&&!selected&&<p role="alert" className="error">{actionError}</p>}
 {(session.error||result.error)&&<section className="error" role="alert"><h2>Workspace could not be loaded</h2><p>{(session.error||result.error)?.message}</p><p>Live records are unavailable until this connection succeeds.</p><button onClick={()=>session.error?session.refetch():result.refetch()}>Retry connection</button></section>}
 {!data&&!session.error&&!result.error&&<div className="loading" role="status">{session.data?'Loading workspace records…':'Verifying your founder session…'}</div>}
 {data&&<>
 {section==='command'&&<><section className="welcome"><div><span className="badge live-badge">{mode==='demo'?'Demo is ready to explore':'Database connected'}</span><h2>{billingReviews||data.summary.openRequests?'A few things need your attention.':'Your workspace is up to date.'}</h2><p>{mode==='demo'?'Follow a customer through their workspace, payment and support request.':'Customer and workspace records are connected. Review outstanding requests and billing status below.'}</p><Link className="primary-action" href={href('customers',mode)}>Explore customers <span>→</span></Link></div><div className="welcome-note"><span className="eyebrow">Next step</span><h3>{billingReviews?'Review payment attention':data.summary.openRequests?'Review customer requests':'Review recent usage'}</h3><p>{billingReviews?`${billingReviews} workspace${billingReviews===1?'':'s'} needs a billing review.`:data.summary.openRequests?`${data.summary.openRequests} request${data.summary.openRequests===1?'':'s'} is waiting.`:'See what customers are doing in Product.'}</p><Link href={href(billingReviews?'billing':data.summary.openRequests?'support':'product',mode)}>Open {billingReviews?'billing':data.summary.openRequests?'support':'product'} →</Link></div></section>
 <div className="grid metric-grid">{[['Customers',data.summary.customers,'customers'],['Workspaces',data.summary.workspaces,'workspaces'],['Active subscriptions',data.summary.activeSubscriptions,'billing']].map(([text,value,to])=><Link className="card metric-link" key={String(text)} href={href(String(to),mode)}><span>{text}</span><strong>{value}</strong><span className="small muted">{mode==='demo'?'Sample':'Canonical total'} · View records →</span></Link>)}</div>
 <div className="home-columns"><section className="panel"><div className="panel-heading"><h2>Needs attention</h2><Link href={href('support',mode)}>View support →</Link></div>{needs.slice(0,5).map(w=><Link className="attention-row" key={w.id} href={href('workspaces',mode,w.id)}><span><strong>{label(w)}</strong><small>Review billing status</small></span><span className="badge">{state(w.status)}</span></Link>)}{data.tickets.filter(t=>['open','requested'].includes(String(t.status))).slice(0,3).map(t=><div className="attention-row" key={t.id}><span><strong>{label(t)}</strong><small>{workspaceName(t.workspaceId)}</small></span><Link href={href('support',mode)}>Review →</Link></div>)}{!billingReviews&&!data.summary.openRequests&&<p className="empty">No outstanding requests or past-due subscriptions.</p>}</section><section className="panel"><h2>Recent activity</h2>{data.activity.slice(0,5).map(r=><div className="activity-row" key={r.id}><span>{state(r.label)}</span><small>{when(r.at)}</small></div>)}{!data.activity.length&&<p className="empty">No Founder Control actions have been recorded.</p>}<Link href={href('product',mode)}>Review usage →</Link></section></div>
 <p className="small muted">{mode==='demo'?'Sample prices and dates are fictional.':`Records refreshed ${new Date(result.data!.asOf).toLocaleString()}. Revenue metrics require separately approved definitions.`}</p></>}
 {['customers','workspaces','billing','support','product'].includes(section)&&<>
 {section==='billing'&&<div className="tabs" role="group" aria-label="Billing view">{['subscriptions','payments','usage'].map(t=><button className="quiet" key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setSearch('');setSettledSearch('');setFilter('all');setPage(1);}}>{t==='subscriptions'?'Subscriptions':t==='payments'?'Payments':'Credit & usage activity'}</button>)}</div>}
 {section==='billing'&&tab==='payments'&&data.paymentState==='not_configured'&&<div className="connection-note"><h2>Payment receipts are not connected</h2><p>The canonical purchase schema is missing. This is different from zero payments.</p><Link href={href('settings',mode)}>Review Connections →</Link></div>}
 {section==='support'&&mode==='live'&&<p className="connection-note">Showing canonical data-request metadata. Customer conversations and outbound replies require approved support access.</p>}
 {section==='billing'&&tab==='usage'&&mode==='live'&&<p className="connection-note">Showing canonical usage-ledger entries. These are not a credit balance; reserves, releases and settlements remain separate. Credit-policy qualification is still required.</p>}
 <section className="panel records">{record&&<p><Link href={href(section,mode)}>View all {section} →</Link></p>}<div className="toolbar"><label>Search {section==='billing'?tab:section}<input type="search" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Search names or record IDs"/></label>{!['product'].includes(section)&&<label>Status<select aria-label="Status" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">All statuses</option>{(list?.statuses||[]).map(s=><option key={s} value={s}>{state(s)}</option>)}</select></label>}<span className="small muted">{list?`${collection.length} of ${list.total} records`:'Loading records…'}</span></div>
 {listing.error&&<div className="error" role="alert"><h2>Records could not be loaded</h2><p>{listing.error.message}</p><button onClick={()=>listing.refetch()}>Retry search</button></div>}{listReady&&!list&&!listing.error&&<p role="status">Searching records…</p>}
 {list&&<><div className="table-scroll" role="region" tabIndex={0} aria-label={title[0]+' records'}><table><caption className="sr-only">{title[0]} · {mode==='demo'?'fictional sample data':'canonical metadata'}</caption><thead><tr><th scope="col">{section==='customers'?'Customer':section==='workspaces'?'Workspace':section==='support'?'Request':section==='product'||tab==='usage'?'Activity':'Workspace'}</th><th scope="col">{section==='customers'?'Workspaces':section==='workspaces'?'Plan':section==='support'?'Workspace':section==='product'||tab==='usage'?'Usage':'Amount'}</th><th scope="col">{section==='product'||tab==='usage'?'Cost quality':'Status'}</th><th scope="col">Details</th></tr></thead><tbody>{collection.map(r=><tr key={r.id}><td><strong>{section==='billing'?workspaceName(r.workspaceId):label(r)}</strong><small className="record-id">{r.id}</small></td><td>{section==='customers'?((r.workspaceIds as string[])||[]).map(id=><Link className="inline-link" key={id} href={href('workspaces',mode,id)}>{workspaceName(id)}</Link>):section==='workspaces'?String(r.plan||'No subscription'):section==='support'?workspaceName(r.workspaceId):section==='product'||tab==='usage'?`${r.quantity} ${r.unit} · ${workspaceName(r.workspaceId)}`:money(r.amountMinor,r.currency)}</td><td><span className="badge">{state(r.status||r.costState)}</span></td><td><button className="quiet" onClick={()=>open(r)} aria-label={'Open '+label(r)}>Open →</button></td></tr>)}</tbody></table></div>{!collection.length&&<div className="empty"><h3>{search||filter!=='all'?'No matching records':'No records yet'}</h3><p>{search||filter!=='all'?'Try a different search or status.':'This connected view returned no records.'}</p>{(search||filter!=='all')&&<button className="quiet" onClick={()=>{setSearch('');setSettledSearch('');setFilter('all');setPage(1);}}>Clear filters</button>}</div>}<div className="pagination" aria-label="Record pages"><button className="quiet" disabled={page===1||listing.isFetching} onClick={()=>setPage(p=>p-1)}>Previous page</button><span className="small muted">Page {page} of {Math.max(1,Math.ceil(list.total/list.pageSize))}</span><button className="quiet" disabled={page*list.pageSize>=list.total||listing.isFetching} onClick={()=>setPage(p=>p+1)}>Next page</button></div></>}</section></>}
 {section==='settings'&&<section className="panel"><h2>Connection readiness</h2>{data.connections.map(c=><div className="connection-row" key={c.id}><div><h3>{c.label}{c.required?' · Required':''}</h3><p>{c.detail}</p></div><span className="badge">{state(c.state)}</span></div>)}<div className="connection-row"><div><h3>Founder identity · Required</h3><p>Your session passed founder authorization and second-factor verification.</p></div><span className="badge live-badge">Verified</span></div><p className="small muted">Secrets and operator enrollment use the existing secure configuration process. No integrations are enabled by visiting this page.</p><Link href="/control/audit">View access policies and audit →</Link></section>}
 {section==='advanced'&&<section className="panel"><h2>Evidence & operations</h2><p>These tools query Live engineering evidence. Demo business actions remain isolated.</p><div className="advanced-links">{[['evidence','Delivery overview'],['engineering','GitHub checks & receipts'],['founder','Founder investigation'],['audit','Access & audit'],['infrastructure','Infrastructure definitions']].map(([id,text])=><Link key={id} href={'/control/'+id}>{text} →</Link>)}</div></section>}
 </>}
 <dialog ref={dialog} className="detail-dialog" onClose={()=>{setSelected(null);setActionError('');pending.current=null;}}><div className="panel-heading"><h2>{selected?label(selected):'Record details'}</h2><button className="quiet" onClick={()=>dialog.current?.close()} aria-label="Close details">Close</button></div>{selected&&<><p className="small muted">{mode==='demo'?'Demo · Fictional record':'Live · Canonical metadata'} · {selected.id}</p><dl>{Object.entries(selected).filter(([k,v])=>!['id','renameAllowed','workspaceIds'].includes(k)&&v!==null&&typeof v!=='object').map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())}</dt><dd>{state(v)}</dd></div>)}</dl>{!!selected.workspaceId&&<Link className="primary-action" href={href('workspaces',mode,String(selected.workspaceId))}>Open workspace →</Link>}
 {section==='workspaces'&&!!selected.renameAllowed&&<form onSubmit={e=>{e.preventDefault();void mutate('rename_workspace',selected.id,name);}}><label htmlFor="workspace-name">Workspace name<input id="workspace-name" value={name} maxLength={80} required onChange={e=>setName(e.target.value)}/></label><p className="small muted">{mode==='demo'?'Changes only this sample workspace.':'Approved test workspace only. This changes the name in Rafii; restore its original name after verification.'}</p><button type="submit" disabled={busy}>{busy?'Saving…':pending.current?'Retry save':'Save name'}</button></form>}
 {mode==='demo'&&section==='support'&&<button onClick={()=>mutate(selected.status==='completed'?'reopen_ticket':'resolve_ticket',selected.id)} disabled={busy}>{selected.status==='completed'?'Reopen sample request':'Resolve sample request'}</button>}
 {mode==='demo'&&section==='billing'&&tab==='payments'&&selected.status==='pending'&&<button onClick={()=>mutate('simulate_payment',selected.id)} disabled={busy}>Simulate successful payment</button>}
 {actionError&&<p role="alert" className="error">{actionError}</p>}</>}</dialog>
 </main></div>;
}
