/**
 * Content Library artwork metadata (DNA v8 §14.4 asset contract): every taxonomy item has one large
 * semantic illustration (8:5) and one compact glyph (1:1), both original deterministic SVGs from the
 * prototype. `content_hash` is the SHA-256 of the file bytes, which `artwork-markup.ts` embeds unchanged
 * and `web/public/rafii/library/` mirrors. The legacy fallback is for explicitly legacy or missing ids
 * only, never a default for a current item (prompt §6).
 *
 * GENERATED by `web/src/lib/content-library/port.mjs`; do not edit by hand.
 *   Source archive: docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip
 *   Archive SHA-256: 285f85ffeb9f04cb9f5d70b29eaab237ccb5d7db336f932d3ad83c9e767bb2fa
 *   Inputs: rafii-prototype-v9/src/taxonomy-data.json (version 1.0.0),
 *           rafii-prototype-v9/src/library-data.json (version 7.0.0, reviewed_at 2026-09-22)
 */
import { COMPACT_ARTWORK, LARGE_ARTWORK, LEGACY_FALLBACK_ARTWORK } from './artwork-markup';

export type ArtworkSize = 'large' | 'compact';

export interface ArtworkMeta {
  thumbnail_id: string;
  thumbnail_kind: 'svg';
  /** Public URL of the byte-identical copy under `web/public`. */
  thumbnail_asset_path: string;
  /** Path inside the source archive. */
  source_path: string;
  alt_text: string;
  aspect_ratio: string;
  visual_concept: string;
  source_type: string;
  content_hash: string;
  version: string;
}

export interface ItemArtwork {
  large: ArtworkMeta;
  compact: ArtworkMeta;
}

export const ARTWORK: Record<string, ItemArtwork> = {
  status_update: {
    large: {
      thumbnail_id: 'rafii-status_update-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/status_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/status_update.svg',
      alt_text: 'Editorial illustration: status update. Share a quick update on what is happening.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: status update. Share a quick update on what is happening.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bef8980b41048dc40f379f4965ac8591255f7545811bb2897e814dc35c498482',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-status_update-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/status_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/status_update.svg',
      alt_text: 'Status update: Share a quick update on what is happening.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled status update pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:70a4e747dcdcb7bb6172271d0110b5fcbc120c7dbc387e19569009bfe37e4d7e',
      version: '7.0.0'
    }
  },
  announcement: {
    large: {
      thumbnail_id: 'rafii-announcement-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/announcement.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/announcement.svg',
      alt_text: 'Editorial illustration: announcement. Put an important message front and centre.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: announcement. Put an important message front and centre.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:9076b40d045b2feae95b23600303130d7642cdad6198f1c3cd90f674787e5726',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-announcement-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/announcement.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/announcement.svg',
      alt_text: 'Announcement: Put an important message front and centre.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled announcement pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:82799867958b9550730a9cc4740f8183222805ce5a7059be6dd7a090597950ab',
      version: '7.0.0'
    }
  },
  news_curation: {
    large: {
      thumbnail_id: 'rafii-news_curation-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/news_curation.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/news_curation.svg',
      alt_text: 'Editorial illustration: news curation. Bring relevant stories and sources together.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: news curation. Bring relevant stories and sources together.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:8cda4c56a07893279a567d87281022f496b25fdb84f38235c1bceb5949b4a190',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-news_curation-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/news_curation.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/news_curation.svg',
      alt_text: 'News curation: Bring relevant stories and sources together.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled news curation pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:24b9ae62d6f00bab8154a80a5016e2024b57598828134e0f91b4c32974e78cf0',
      version: '7.0.0'
    }
  },
  opinion_commentary: {
    large: {
      thumbnail_id: 'rafii-opinion_commentary-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/opinion_commentary.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/opinion_commentary.svg',
      alt_text: 'Editorial illustration: opinion & commentary. Share a perspective and invite another.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: opinion & commentary. Share a perspective and invite another.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:f1c82f31ad401ab21fb1b67d352d42f3cc375759fd8fa3bb106fc6ac5799ae16',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-opinion_commentary-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/opinion_commentary.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/opinion_commentary.svg',
      alt_text: 'Opinion & commentary: Share a perspective and invite another.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled opinion & commentary pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:5307d7664e96dd265a5db733c7202e4f903f3172528d2aa3816903e80352ab2d',
      version: '7.0.0'
    }
  },
  quote: {
    large: {
      thumbnail_id: 'rafii-quote-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/quote.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/quote.svg',
      alt_text: 'Editorial illustration: quote. Give a memorable thought room to resonate.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: quote. Give a memorable thought room to resonate.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a2e0d8c046432f34334134c8eb29a810cfe647042e39240a3d8d830fbf660b22',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-quote-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/quote.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/quote.svg',
      alt_text: 'Quote: Give a memorable thought room to resonate.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled quote pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:7d5225766f8373d9166d4619a4ed9150feea7b58e96fe8d299057b4af7b78ccf',
      version: '7.0.0'
    }
  },
  question_prompt: {
    large: {
      thumbnail_id: 'rafii-question_prompt-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/question_prompt.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/question_prompt.svg',
      alt_text: 'Editorial illustration: question prompt. Start a conversation with an open question.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: question prompt. Start a conversation with an open question.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:e84f6c9c91f4501a37de1792b91c269d21f47b9b2fc2e4b1ef91f44b8b15afcf',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-question_prompt-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/question_prompt.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/question_prompt.svg',
      alt_text: 'Question prompt: Start a conversation with an open question.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled question prompt pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:d1f654f8832df43d531044f9a12ac0e144f59e077dd844b630ada76a1332ecf7',
      version: '7.0.0'
    }
  },
  poll_quiz: {
    large: {
      thumbnail_id: 'rafii-poll_quiz-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/poll_quiz.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/poll_quiz.svg',
      alt_text: 'Editorial illustration: poll or quiz. Invite your audience to choose or explore.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: poll or quiz. Invite your audience to choose or explore.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:f3f0c19615e14d2c0290372f253cdc07b998604e41190ea236c86c9a94d4c4e9',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-poll_quiz-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/poll_quiz.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/poll_quiz.svg',
      alt_text: 'Poll or quiz: Invite your audience to choose or explore.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled poll or quiz pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:6dec3e53972fa63501acb0f3319f34ba8a349f9e4b09cd6207f645390ed0351a',
      version: '7.0.0'
    }
  },
  how_to: {
    large: {
      thumbnail_id: 'rafii-how_to-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/how_to.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/how_to.svg',
      alt_text: 'Editorial illustration: how-to. Turn a process into clear, practical steps.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: how-to. Turn a process into clear, practical steps.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:4d706d69a705cff9c5e52b93e8efb8f474a63c82744673da95bbe6a6610338f0',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-how_to-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/how_to.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/how_to.svg',
      alt_text: 'How-to: Turn a process into clear, practical steps.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled how-to pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:95db2bfc593a7aa1503d9a6c1e49bf3fffe184bcc99d1a5c1b6d52d3ab0dfc5d',
      version: '7.0.0'
    }
  },
  educational_explainer: {
    large: {
      thumbnail_id: 'rafii-educational_explainer-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/educational_explainer.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/educational_explainer.svg',
      alt_text: 'Editorial illustration: educational explainer. Make a complex idea easier to understand.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: educational explainer. Make a complex idea easier to understand.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:2683d1fc245337f119146ff08103625d3f6a728ab1fc3ae871b44193e9f5ef15',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-educational_explainer-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/educational_explainer.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/educational_explainer.svg',
      alt_text: 'Educational explainer: Make a complex idea easier to understand.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled educational explainer pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bd9b960dd67592a9e6edfeb305a48c8ca418f6d1339c61bf02cfda8b798f0e9e',
      version: '7.0.0'
    }
  },
  list_checklist: {
    large: {
      thumbnail_id: 'rafii-list_checklist-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/list_checklist.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/list_checklist.svg',
      alt_text: 'Editorial illustration: list & checklist. Organise useful advice into actionable items.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: list & checklist. Organise useful advice into actionable items.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:42fe2395c98de93adea9ccb05dd5d6539779b55cbc0cd291224f5a2defce2600',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-list_checklist-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/list_checklist.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/list_checklist.svg',
      alt_text: 'List & checklist: Organise useful advice into actionable items.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled list & checklist pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:1a4de2a52b21f0b3ab034e734951cbf5706094a2279868ff47d2aeef9a447456',
      version: '7.0.0'
    }
  },
  review_comparison: {
    large: {
      thumbnail_id: 'rafii-review_comparison-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/review_comparison.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/review_comparison.svg',
      alt_text: 'Editorial illustration: review & comparison. Examine the differences that matter.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: review & comparison. Examine the differences that matter.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:18984339256cde99fc95aaeb1db17faabed7fbfcbb72c567abeca368f467904a',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-review_comparison-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/review_comparison.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/review_comparison.svg',
      alt_text: 'Review & comparison: Examine the differences that matter.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled review & comparison pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:38516e77ea13fb983db7097d51910ccb27a2040fa9934d575a1ceb943b518cd7',
      version: '7.0.0'
    }
  },
  resource_roundup: {
    large: {
      thumbnail_id: 'rafii-resource_roundup-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/resource_roundup.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/resource_roundup.svg',
      alt_text: 'Editorial illustration: resource roundup. Curate useful tools, books and references.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: resource roundup. Curate useful tools, books and references.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bd8fd2817853f675aa1e2949f7221e1a4205dc74a43010ba2adfd281b4d2fb54',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-resource_roundup-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/resource_roundup.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/resource_roundup.svg',
      alt_text: 'Resource roundup: Curate useful tools, books and references.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled resource roundup pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:816db83975e9f8836633c6e9dd352356f6256424c252e1e23071563b232b4b49',
      version: '7.0.0'
    }
  },
  product_service_showcase: {
    large: {
      thumbnail_id: 'rafii-product_service_showcase-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/product_service_showcase.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/product_service_showcase.svg',
      alt_text: 'Editorial illustration: product & service showcase. Show what you offer and who it helps.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: product & service showcase. Show what you offer and who it helps.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:e86b7813beecaca653d3f4ed5ef393168117c0f16ae37061b89d4a70e3af4423',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-product_service_showcase-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/product_service_showcase.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/product_service_showcase.svg',
      alt_text: 'Product & service showcase: Show what you offer and who it helps.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled product & service showcase pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:1956ff3a1ef6eeb9da035dd2c97534c73a024629f895a1645fb30a0aedd1d960',
      version: '7.0.0'
    }
  },
  product_update: {
    large: {
      thumbnail_id: 'rafii-product_update-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/product_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/product_update.svg',
      alt_text: 'Editorial illustration: product update. Explain what changed and why it matters.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: product update. Explain what changed and why it matters.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a91b43fbd3df0d933104765af15e83053ed9dd232fb65688be98abfe3eee361c',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-product_update-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/product_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/product_update.svg',
      alt_text: 'Product update: Explain what changed and why it matters.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled product update pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:d9bf123ba5e7b67e04678b33968abbb70dcf737cb31e3a491a22fd1b671d5436',
      version: '7.0.0'
    }
  },
  launch_release: {
    large: {
      thumbnail_id: 'rafii-launch_release-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/launch_release.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/launch_release.svg',
      alt_text: 'Editorial illustration: launch & release. Introduce something new to the world.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: launch & release. Introduce something new to the world.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:d4ca83d7eb2827de4b1b8067c88939b557059c9f4507f9acfcc50ca390b1deea',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-launch_release-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/launch_release.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/launch_release.svg',
      alt_text: 'Launch & release: Introduce something new to the world.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled launch & release pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:b4080c235fd25dbc40894a93989b2ea1012e4cfa0b191a09e2d3ec4521eb2a57',
      version: '7.0.0'
    }
  },
  promotion_offer: {
    large: {
      thumbnail_id: 'rafii-promotion_offer-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/promotion_offer.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/promotion_offer.svg',
      alt_text: 'Editorial illustration: promotion & offer. Communicate an offer and its clear benefit.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: promotion & offer. Communicate an offer and its clear benefit.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:87a33da499cfae89795781eb151a805fd3181a63d1264ef24298826015aa4a01',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-promotion_offer-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/promotion_offer.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/promotion_offer.svg',
      alt_text: 'Promotion & offer: Communicate an offer and its clear benefit.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled promotion & offer pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:b979b9019e07dc101fe5d95b64bea93837f7f95941a3da53531912529e9d192c',
      version: '7.0.0'
    }
  },
  event_live: {
    large: {
      thumbnail_id: 'rafii-event_live-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/event_live.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/event_live.svg',
      alt_text: 'Editorial illustration: event & live coverage. Invite people in and share the occasion.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: event & live coverage. Invite people in and share the occasion.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:eb6f9ea4019d927ac5e2de0b73cd83b72ea01eda8ab3008de9d7da3bada28c8e',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-event_live-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/event_live.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/event_live.svg',
      alt_text: 'Event & live coverage: Invite people in and share the occasion.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled event & live coverage pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:08f01e6c131515c14dc336fb33102b932624618c51bc4a873614182d2effe0e4',
      version: '7.0.0'
    }
  },
  behind_the_scenes: {
    large: {
      thumbnail_id: 'rafii-behind_the_scenes-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/behind_the_scenes.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/behind_the_scenes.svg',
      alt_text: 'Editorial illustration: behind the scenes. Show the process behind the finished work.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: behind the scenes. Show the process behind the finished work.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:89691bbf229cc1db1e52fff2e8c4c54b931c878898fac5fbbee3bdd6fbe982ab',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-behind_the_scenes-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/behind_the_scenes.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/behind_the_scenes.svg',
      alt_text: 'Behind the scenes: Show the process behind the finished work.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled behind the scenes pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:171c81fea2743e8d77c61ce349b89ee087784c769172412b34ce558227ed85a0',
      version: '7.0.0'
    }
  },
  personal_lifestyle: {
    large: {
      thumbnail_id: 'rafii-personal_lifestyle-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/personal_lifestyle.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/personal_lifestyle.svg',
      alt_text: 'Editorial illustration: personal & lifestyle. Share a thoughtful glimpse of daily life.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: personal & lifestyle. Share a thoughtful glimpse of daily life.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:459f7364d5595043331a56b7af0032edf4807a70b67464549692154a2fad6d73',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-personal_lifestyle-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/personal_lifestyle.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/personal_lifestyle.svg',
      alt_text: 'Personal & lifestyle: Share a thoughtful glimpse of daily life.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled personal & lifestyle pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:e509ada67774edd31a4e333cec6f1753b7d766c47c018d4f428c1518fd9b93ee',
      version: '7.0.0'
    }
  },
  milestone: {
    large: {
      thumbnail_id: 'rafii-milestone-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/milestone.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/milestone.svg',
      alt_text: 'Editorial illustration: milestone. Mark a meaningful step along the way.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: milestone. Mark a meaningful step along the way.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:548669d3e256ea3102902ed8630dba8f73a9d8c66701f6d6b454efcbc191bab0',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-milestone-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/milestone.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/milestone.svg',
      alt_text: 'Milestone: Mark a meaningful step along the way.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled milestone pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:eedce3817f291abd6ce3ebd5d8bc2bdef02471d36b34dfc3c15ad60b5bbddc29',
      version: '7.0.0'
    }
  },
  ugc_testimonial: {
    large: {
      thumbnail_id: 'rafii-ugc_testimonial-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/ugc_testimonial.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/ugc_testimonial.svg',
      alt_text: 'Editorial illustration: ugc & testimonial. Share an authentic community experience.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: ugc & testimonial. Share an authentic community experience.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a34cd4a7c23fcc5cfc4d0f32106d2bcf881695855c353db4a02ebb30d4b2bab5',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-ugc_testimonial-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/ugc_testimonial.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/ugc_testimonial.svg',
      alt_text: 'UGC & testimonial: Share an authentic community experience.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled ugc & testimonial pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:cba9f86a9b02a7ac0035fc4a9cbfaa431945ee3378927e1beddad856a3b4a14e',
      version: '7.0.0'
    }
  },
  case_study: {
    large: {
      thumbnail_id: 'rafii-case_study-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/case_study.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/case_study.svg',
      alt_text: 'Editorial illustration: case study. Connect a real challenge, action and result.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: case study. Connect a real challenge, action and result.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bf0957c1965186869602b8d414f8153a1bd8af3ad0808ffc981f4995a595e701',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-case_study-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/case_study.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/case_study.svg',
      alt_text: 'Case study: Connect a real challenge, action and result.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled case study pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a68ef939ab5d34871547d826f446c02bae33b9d0c498a6ed8ebdb4f0c1233f47',
      version: '7.0.0'
    }
  },
  qa_faq: {
    large: {
      thumbnail_id: 'rafii-qa_faq-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/qa_faq.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/qa_faq.svg',
      alt_text: 'Editorial illustration: q&a / faq. Answer the questions people keep asking.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: q&a / faq. Answer the questions people keep asking.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:fe45389e1e958f3416128a9d4cb003ab66c6cc910956977fc8e6156adc23dd22',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-qa_faq-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/qa_faq.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/qa_faq.svg',
      alt_text: 'Q&A / FAQ: Answer the questions people keep asking.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled q&a / faq pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:39c2375426753dfad71a2d2a8bf1dcda7eac915bc1cbf42ce781c31d6268e52e',
      version: '7.0.0'
    }
  },
  community_announcement: {
    large: {
      thumbnail_id: 'rafii-community_announcement-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/community_announcement.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/community_announcement.svg',
      alt_text: 'Editorial illustration: community announcement. Keep your group informed and included.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: community announcement. Keep your group informed and included.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:2d7f56a7552bae8adb81503f5f3a64e84326700a6c17e792b796aadbf1ed178b',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-community_announcement-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/community_announcement.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/community_announcement.svg',
      alt_text: 'Community announcement: Keep your group informed and included.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled community announcement pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:10a0e8d621dfe727b95ccb7ced74045a3c885db42c55d2688f3d62648ef7fc52',
      version: '7.0.0'
    }
  },
  cause_advocacy: {
    large: {
      thumbnail_id: 'rafii-cause_advocacy-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/cause_advocacy.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/cause_advocacy.svg',
      alt_text: 'Editorial illustration: cause & advocacy. Explain a cause with context and supporting facts.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: cause & advocacy. Explain a cause with context and supporting facts.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:1f62e03c798f266313c79d6ab3b6e7d92e341bd0ccdff4972d450c8bbbb5b8ce',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-cause_advocacy-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/cause_advocacy.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/cause_advocacy.svg',
      alt_text: 'Cause & advocacy: Explain a cause with context and supporting facts.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled cause & advocacy pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:733deefbad2b1398016eaf22aafed2e8eda2a84a46ba081040e3d6e71fc0b5a3',
      version: '7.0.0'
    }
  },
  contest_challenge: {
    large: {
      thumbnail_id: 'rafii-contest_challenge-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/contest_challenge.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/contest_challenge.svg',
      alt_text: 'Editorial illustration: contest & challenge. Set out a challenge and how to take part.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: contest & challenge. Set out a challenge and how to take part.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bfc6e042a55b3a31ea08fa854e3e4b6c90e91c0d2622777e56dbee2f91defa0a',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-contest_challenge-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/contest_challenge.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/contest_challenge.svg',
      alt_text: 'Contest & challenge: Set out a challenge and how to take part.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled contest & challenge pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:71c1f5dbf52a6868b605715d8572a16db18454c37a5bdb3c556e307a61165b2e',
      version: '7.0.0'
    }
  },
  job_recruitment: {
    large: {
      thumbnail_id: 'rafii-job_recruitment-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/job_recruitment.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/job_recruitment.svg',
      alt_text: 'Editorial illustration: job & recruitment. Describe a role and invite applications.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: job & recruitment. Describe a role and invite applications.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:3835932686bdc988c6de596629771794355a1293c56417703b1a4d2f619b6be1',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-job_recruitment-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/job_recruitment.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/job_recruitment.svg',
      alt_text: 'Job & recruitment: Describe a role and invite applications.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled job & recruitment pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:687a0c442bfe4d0c3bffb438db719564ba8c10561e1263e490fbc5a1f9a5586b',
      version: '7.0.0'
    }
  },
  article_blog_newsletter: {
    large: {
      thumbnail_id: 'rafii-article_blog_newsletter-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/article_blog_newsletter.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/article_blog_newsletter.svg',
      alt_text: 'Editorial illustration: article, blog & newsletter. Develop an idea with editorial depth.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: article, blog & newsletter. Develop an idea with editorial depth.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:82bef5604b4f7df6154b6af0b8e3b0f032bee6fdc36851c842a63eb432430eaf',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-article_blog_newsletter-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/article_blog_newsletter.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/article_blog_newsletter.svg',
      alt_text: 'Article, blog & newsletter: Develop an idea with editorial depth.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled article, blog & newsletter pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:554c5ec84a6c4c15999766a17842fb3e0eb8fe95e9e8259742d855851b676800',
      version: '7.0.0'
    }
  },
  recap_followup: {
    large: {
      thumbnail_id: 'rafii-recap_followup-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/recap_followup.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/recap_followup.svg',
      alt_text: 'Editorial illustration: recap & follow-up. Revisit key moments and what comes next.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: recap & follow-up. Revisit key moments and what comes next.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:80b68bc0001308285c5d64972b7aa2db997f0fb510a3cd289233c1741a818310',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-recap_followup-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/recap_followup.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/recap_followup.svg',
      alt_text: 'Recap & follow-up: Revisit key moments and what comes next.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled recap & follow-up pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:b307c018716e04f9787a256087d822cd177734ca5ea144a2452ce78713a4c024',
      version: '7.0.0'
    }
  },
  reaction_reply: {
    large: {
      thumbnail_id: 'rafii-reaction_reply-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/reaction_reply.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/reaction_reply.svg',
      alt_text: 'Editorial illustration: reaction & reply. Respond thoughtfully to another contribution.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: reaction & reply. Respond thoughtfully to another contribution.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:c934bcee8e2d0a852c6dd851b444626ab645a7ac598a503cb5232e067782d823',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-reaction_reply-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/reaction_reply.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/reaction_reply.svg',
      alt_text: 'Reaction & reply: Respond thoughtfully to another contribution.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled reaction & reply pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:f72a03b7e94eedda18416f9fec7e6987b2a26993ddca707aacddadfe5041349a',
      version: '7.0.0'
    }
  },
  live_ama: {
    large: {
      thumbnail_id: 'rafii-live_ama-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/live_ama.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/live_ama.svg',
      alt_text: 'Editorial illustration: live ama. Invite questions for a live conversation.',
      aspect_ratio: '8:5',
      visual_concept: 'Editorial illustration: live ama. Invite questions for a live conversation.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a86de8a4d0d60fcce8e72cf296c0acc145f64dd36532ff3ed7d80b0a102d5ab0',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-live_ama-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/live_ama.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/live_ama.svg',
      alt_text: 'Live AMA: Invite questions for a live conversation.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled live ama pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:2c7934af22bb8b1665f7a7d1274db6d6f694d700595d23f24367490e9115d6b9',
      version: '7.0.0'
    }
  },
  text: {
    large: {
      thumbnail_id: 'rafii-text-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/text.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/text.svg',
      alt_text: 'Presentation illustration: text. A concise post with words at its centre.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: text. A concise post with words at its centre.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:8d7f2a8357146e0aba75ab3ebda699df09c87751e18d6928a798e577024a9a57',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-text-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/text.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/text.svg',
      alt_text: 'Text: A concise post with words at its centre.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled text pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a3b8f671e4569f2b12deda0cee1c628e834e5941d942c35c29b467e5399d6bb7',
      version: '7.0.0'
    }
  },
  long_text: {
    large: {
      thumbnail_id: 'rafii-long_text-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/long_text.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/long_text.svg',
      alt_text: 'Presentation illustration: long text. A longer post with distinct sections.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: long text. A longer post with distinct sections.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:653e439c408e634bc2d6af7a0b800a6666522dc4dc85b5a64ef2c5efeefa47bd',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-long_text-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/long_text.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/long_text.svg',
      alt_text: 'Long text: A longer post with distinct sections.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled long text pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:d95b0a941de9b3abc0af0884abaaa23337ca57da013c147dc09103f86e8fe6ce',
      version: '7.0.0'
    }
  },
  thread: {
    large: {
      thumbnail_id: 'rafii-thread-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/thread.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/thread.svg',
      alt_text: 'Presentation illustration: thread. A connected sequence of short posts.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: thread. A connected sequence of short posts.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:b5199ed8117435f6d76a8a56db9939a2db9b68f8cd8d1b7bbd9447143f3951c9',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-thread-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/thread.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/thread.svg',
      alt_text: 'Thread: A connected sequence of short posts.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled thread pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:db7fab548544668cb4673597c1124cd47bb3ecc645a8e91c382f798ab143f455',
      version: '7.0.0'
    }
  },
  image_caption: {
    large: {
      thumbnail_id: 'rafii-image_caption-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/image_caption.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/image_caption.svg',
      alt_text: 'Presentation illustration: image + caption. Pair a visual with its written context.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: image + caption. Pair a visual with its written context.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:ebdf524d0a29484c98e8f6658e7a6a9579686752967efa125c102f5aad739b49',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-image_caption-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/image_caption.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/image_caption.svg',
      alt_text: 'Image + caption: Pair a visual with its written context.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled image + caption pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:aa67d4eed54e18a34b9c5c13ec87434cfd2eeeea221b072ae187eb7583ab1eb4',
      version: '7.0.0'
    }
  },
  quote_card: {
    large: {
      thumbnail_id: 'rafii-quote_card-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/quote_card.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/quote_card.svg',
      alt_text: 'Presentation illustration: quote card. Set a quotation in an expressive graphic.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: quote card. Set a quotation in an expressive graphic.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:b9b8bc0252094c259c9fa884b367e1e7e2e887dd277e863f3115ce06c5644ac5',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-quote_card-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/quote_card.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/quote_card.svg',
      alt_text: 'Quote card: Set a quotation in an expressive graphic.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled quote card pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:2a6315f4c97ce56453e21e36007d92b5c17b37b8c85a46007c681773ce617e3e',
      version: '7.0.0'
    }
  },
  carousel: {
    large: {
      thumbnail_id: 'rafii-carousel-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/carousel.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/carousel.svg',
      alt_text: 'Presentation illustration: carousel. Tell a story across a sequence of slides.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: carousel. Tell a story across a sequence of slides.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:76178b6e1bf592fabf5a1d3cadfcf5bf01a4ffacb8c2bef74f00fd1b5f08e049',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-carousel-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/carousel.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/carousel.svg',
      alt_text: 'Carousel: Tell a story across a sequence of slides.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled carousel pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a721322e20c3caaf1dda2ee71a32d3b00c8096f46e5898bf4d61bf514d7978d5',
      version: '7.0.0'
    }
  },
  link_preview: {
    large: {
      thumbnail_id: 'rafii-link_preview-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/link_preview.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/link_preview.svg',
      alt_text: 'Presentation illustration: link preview. Introduce a destination with a summary.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: link preview. Introduce a destination with a summary.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:270c4c541e9074087a3e58ee050d081206a4a8bc2e3c8536215c8dedb2d7fded',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-link_preview-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/link_preview.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/link_preview.svg',
      alt_text: 'Link preview: Introduce a destination with a summary.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled link preview pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:5ab9132ee60fb5267a1c09086a9c73834def8f2c2ca5a5589d707ce822916998',
      version: '7.0.0'
    }
  },
  native_article: {
    large: {
      thumbnail_id: 'rafii-native_article-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/native_article.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/native_article.svg',
      alt_text: 'Presentation illustration: native article. A long-form editorial reading experience.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: native article. A long-form editorial reading experience.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:4baa0c4ef6ac03b15bca3edbd21448591c401e729aeb06f810f09d76b10a8fd7',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-native_article-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/native_article.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/native_article.svg',
      alt_text: 'Native article: A long-form editorial reading experience.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled native article pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:93eecac2fd1486ad53cc9906a0523fa588e3dd1eb5eb4ba347d0e6dc7adc8a1f',
      version: '7.0.0'
    }
  },
  document: {
    large: {
      thumbnail_id: 'rafii-document-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/document.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/document.svg',
      alt_text: 'Presentation illustration: document. Present a multi-page document or PDF.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: document. Present a multi-page document or PDF.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:7fecacc5e33cb61671b6221936c180a8ac8ef134b045baedc400a275021438a1',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-document-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/document.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/document.svg',
      alt_text: 'Document: Present a multi-page document or PDF.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled document pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:357f597f22f686ef64fca164fd826fc6dc4cf9100191e260ff38e2c34a57bf68',
      version: '7.0.0'
    }
  },
  short_vertical_video: {
    large: {
      thumbnail_id: 'rafii-short_vertical_video-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/short_vertical_video.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/short_vertical_video.svg',
      alt_text: 'Presentation illustration: short vertical video. Plan a short, portrait-oriented video.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: short vertical video. Plan a short, portrait-oriented video.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:2689d2e7701e08a7153a0413fb884b6b199cac8c31f24031d79cc93ca73f95dd',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-short_vertical_video-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/short_vertical_video.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/short_vertical_video.svg',
      alt_text: 'Short vertical video: Plan a short, portrait-oriented video.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled short vertical video pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:307a0cc4663a7a0fa9aea26985d121bec0d0c791031766269fe66008ff0b47b1',
      version: '7.0.0'
    }
  },
  long_video: {
    large: {
      thumbnail_id: 'rafii-long_video-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/long_video.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/long_video.svg',
      alt_text: 'Presentation illustration: long video. Plan a longer, widescreen video.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: long video. Plan a longer, widescreen video.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:0e26a25e6a0f470a002fa6d7a5a69a9d34a51c0da7babe6fee2f8d25f95998ba',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-long_video-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/long_video.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/long_video.svg',
      alt_text: 'Long video: Plan a longer, widescreen video.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled long video pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:c54f309824ad239830263aaac31bc3a3edd8b8133809bf9c02ecc2a7a712fed9',
      version: '7.0.0'
    }
  },
  livestream: {
    large: {
      thumbnail_id: 'rafii-livestream-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/livestream.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/livestream.svg',
      alt_text: 'Presentation illustration: livestream. Plan a live broadcast and its context.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: livestream. Plan a live broadcast and its context.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:db8628c0632975a6b2d4996111c63fa4bd734263095dc720bb0bcfa8ad4560d2',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-livestream-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/livestream.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/livestream.svg',
      alt_text: 'Livestream: Plan a live broadcast and its context.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled livestream pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:e350be533686a8e30e8622860d1da4bed5d97589bdfd22cf2f8378372f3e06a2',
      version: '7.0.0'
    }
  },
  story: {
    large: {
      thumbnail_id: 'rafii-story-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/story.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/story.svg',
      alt_text: 'Presentation illustration: story. Compose a short vertical story sequence.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: story. Compose a short vertical story sequence.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:af2a4b79baef17b0dd9c7c8ce4a5777dbdd0e19e04d18805ac47883bb8cfe75f',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-story-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/story.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/story.svg',
      alt_text: 'Story: Compose a short vertical story sequence.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled story pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:383e96cd6458ceca07c98b247f82a4c40140474ee298dca38fec45fa3734bc28',
      version: '7.0.0'
    }
  },
  poll: {
    large: {
      thumbnail_id: 'rafii-poll-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/poll.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/poll.svg',
      alt_text: 'Presentation illustration: poll. Present a question with selectable answers.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: poll. Present a question with selectable answers.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:75ff9e317099b082df14a275eb2124880e118f08f7e05447fa3911f850adfc03',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-poll-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/poll.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/poll.svg',
      alt_text: 'Poll: Present a question with selectable answers.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled poll pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:74b49de828dd776b44c4f5af650374fe6575859c1d8a4f2605e69caf78f21db3',
      version: '7.0.0'
    }
  },
  quiz: {
    large: {
      thumbnail_id: 'rafii-quiz-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/quiz.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/quiz.svg',
      alt_text: 'Presentation illustration: quiz. Pair a question with answer choices.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: quiz. Pair a question with answer choices.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:01b2dbbb8c1ab3b6c017b9ec15f0b09d89df1630c86dc724b0922f741c0cc7ce',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-quiz-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/quiz.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/quiz.svg',
      alt_text: 'Quiz: Pair a question with answer choices.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled quiz pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:d911c3f1b9a6783018d21f5088535ce27a13cb98142aa590a7be963eec1aafc5',
      version: '7.0.0'
    }
  },
  audio: {
    large: {
      thumbnail_id: 'rafii-audio-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/audio.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/audio.svg',
      alt_text: 'Presentation illustration: audio. Plan an audio clip or listening experience.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: audio. Plan an audio clip or listening experience.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:55049deae17ab95fc495b605b41402d073faa1898c4f2f1b303c1d8a1dfa14b5',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-audio-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/audio.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/audio.svg',
      alt_text: 'Audio: Plan an audio clip or listening experience.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled audio pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:ed93d03af89b464f3257e4c7b973bf261f8a995e197a256f4f7bc4059c10c9de',
      version: '7.0.0'
    }
  },
  broadcast_message: {
    large: {
      thumbnail_id: 'rafii-broadcast_message-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/broadcast_message.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/broadcast_message.svg',
      alt_text: 'Presentation illustration: broadcast message. Prepare a message for a channel audience.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: broadcast message. Prepare a message for a channel audience.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:e478c107aaa13d3653d6e0bf239e29c5125aba5fefd12e95f66f663a4de2602b',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-broadcast_message-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/broadcast_message.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/broadcast_message.svg',
      alt_text: 'Broadcast message: Prepare a message for a channel audience.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled broadcast message pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:3fb49c3e3987dccc0baffd9181696c9e1e4e1877868f539a6ed45cbebd84b162',
      version: '7.0.0'
    }
  },
  community_message: {
    large: {
      thumbnail_id: 'rafii-community_message-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/community_message.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/community_message.svg',
      alt_text: 'Presentation illustration: community message. Prepare a message for a group or community.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: community message. Prepare a message for a group or community.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:62c9821ff1c230bc2387aef07ad6c768342648301d74a26ff641a945a21b6174',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-community_message-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/community_message.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/community_message.svg',
      alt_text: 'Community message: Prepare a message for a group or community.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled community message pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:bee4c880f506a67f94ccfb4bbd55bf1a3c3f3388edbf38fae7969d1ed6d28c04',
      version: '7.0.0'
    }
  },
  product_catalog: {
    large: {
      thumbnail_id: 'rafii-product_catalog-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/product_catalog.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/product_catalog.svg',
      alt_text: 'Presentation illustration: product catalogue. Organise products into a browsable collection.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: product catalogue. Organise products into a browsable collection.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:f5ea6dd21d928d1a63217f1b85fa473c48844b4e0e94b89267399de28f29116d',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-product_catalog-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/product_catalog.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/product_catalog.svg',
      alt_text: 'Product catalogue: Organise products into a browsable collection.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled product catalogue pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:71d5394feb111a76366f36ae11d19b11d66a33d7445401d3596fc12201155f65',
      version: '7.0.0'
    }
  },
  local_business_update: {
    large: {
      thumbnail_id: 'rafii-local_business_update-v1',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/thumbnails/local_business_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/thumbnails/local_business_update.svg',
      alt_text: 'Presentation illustration: local business update. Share local hours, news, an event or an offer.',
      aspect_ratio: '8:5',
      visual_concept: 'Presentation illustration: local business update. Share local hours, news, an event or an offer.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:6b4e26f9092170d377dac297bae5037afa76c8c7782c3bc9364d9dc78e64eb58',
      version: '1.0.0'
    },
    compact: {
      thumbnail_id: 'rafii-glyph-local_business_update-v7',
      thumbnail_kind: 'svg',
      thumbnail_asset_path: '/rafii/library/glyphs/local_business_update.svg',
      source_path: 'rafii-prototype-v9/src/assets/glyphs/local_business_update.svg',
      alt_text: 'Local business update: Share local hours, news, an event or an offer.',
      aspect_ratio: '1:1',
      visual_concept: 'Distilled local business update pictogram with a separate animated accent.',
      source_type: 'original_deterministic_svg',
      content_hash: 'sha256:a31ef58fe2d3163404896d6cc85d2d50ca58bdfa00b97c5beb04e37da698cc61',
      version: '7.0.0'
    }
  }
};

export const LEGACY_FALLBACK: ArtworkMeta = {
  thumbnail_id: 'rafii-legacy-fallback-v1',
  thumbnail_kind: 'svg',
  thumbnail_asset_path: '/rafii/library/thumbnails/legacy-fallback.svg',
  source_path: 'rafii-prototype-v9/src/assets/thumbnails/legacy-fallback.svg',
  alt_text: 'Legacy item: choose a current content type.',
  aspect_ratio: '8:5',
  visual_concept: 'Neutral paper card marking an item the current taxonomy no longer carries.',
  source_type: 'original_deterministic_svg',
  content_hash: 'sha256:2fd0230274e14eb3ee8b9b67e481c8a889b129f6322f4a603e98edff5b0b1ded',
  version: '1.0.0'
};

/** Metadata for one item's artwork, or undefined for an id the taxonomy does not carry. */
export function artworkFor(id: string): ItemArtwork | undefined {
  return ARTWORK[id];
}

/** The SVG source for an asset. Unknown ids get the legacy fallback at large size and nothing at compact size. */
export function artworkMarkup(id: string, size: ArtworkSize): string | null {
  if (size === 'compact') return COMPACT_ARTWORK[id] ?? null;
  return LARGE_ARTWORK[id] ?? LEGACY_FALLBACK_ARTWORK;
}
