/**
 * Content Library (Rafii v9, Stream B): 31 editorial types and 20 native formats with their artwork,
 * pairings, evidence and the execution registry that maps each choice onto what the workspace runtime
 * can draft. Data modules are generated by `port.mjs` from the approved prototype archive.
 */
export * from './taxonomy';
export * from './artwork';
export * from './registry';
export * from './select';
export { prepareArtwork, namespaceIds, ART_MOTIF_CLASS, ART_ACCENT_CLASS } from './svg';
export type { PrepareOptions } from './svg';
