#!/usr/bin/env node
/**
 * Ports the Content Library out of the approved Rafii v9 prototype archive.
 *
 *   node web/src/lib/content-library/port.mjs
 *
 * Reads `docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip` (never the repository copy of
 * anything), verifies every asset hash the prototype recorded, and writes:
 *
 *   web/src/lib/content-library/taxonomy.ts        the 51 items, categories, platforms, evidence, pairings
 *   web/src/lib/content-library/artwork-markup.ts  the 51 + 51 (+1 legacy) SVG sources, byte-identical strings
 *   web/src/lib/content-library/artwork.ts         asset metadata (DNA v8 §14.4) bound to the markup
 *   web/public/rafii/library/thumbnails/*.svg      byte-identical copies of the large illustrations
 *   web/public/rafii/library/glyphs/*.svg          byte-identical copies of the compact glyphs
 *   web/public/rafii/library/PROVENANCE.md         archive hash + per-file hashes
 *
 * The generated files carry a build note; edit this script, not them. `taxonomy.test.cjs` re-checks the
 * hashes and the split, so a drift between archive, copies and modules fails the tests.
 */
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../../..');
const archive = join(repo, 'docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip');
const archiveRel = 'docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip';
const publicDir = join(repo, 'web/public/rafii/library');

const sha256 = (bytes) => 'sha256:' + createHash('sha256').update(bytes).digest('hex');
const archiveSha = sha256(readFileSync(archive));

const work = mkdtempSync(join(tmpdir(), 'rafii-library-'));
execFileSync('unzip', ['-o', '-q', archive, '-d', work]);
const src = join(work, 'rafii-prototype-v9/src');
const read = (rel) => readFileSync(join(src, rel));

const taxonomy = JSON.parse(read('taxonomy-data.json'));
const library = JSON.parse(read('library-data.json'));

/* ---- verify the prototype's own contract before porting anything ---- */
if (taxonomy.items.length !== 51) throw new Error(`expected 51 items, found ${taxonomy.items.length}`);
const files = [];
for (const item of taxonomy.items) {
  const large = read(item.thumbnail_asset_path);
  if (sha256(large) !== item.content_hash) throw new Error(`large hash drift: ${item.id}`);
  const compact = library.items[item.id]?.compact_thumbnail;
  if (!compact) throw new Error(`missing compact thumbnail: ${item.id}`);
  const glyph = read(compact.thumbnail_asset_path);
  if (sha256(glyph) !== compact.content_hash) throw new Error(`compact hash drift: ${item.id}`);
  files.push({ id: item.id, kind: 'thumbnails', bytes: large, hash: item.content_hash, source: item.thumbnail_asset_path });
  files.push({ id: item.id, kind: 'glyphs', bytes: glyph, hash: compact.content_hash, source: compact.thumbnail_asset_path });
}
const legacyBytes = read('assets/thumbnails/legacy-fallback.svg');
files.push({ id: 'legacy-fallback', kind: 'thumbnails', bytes: legacyBytes, hash: sha256(legacyBytes), source: 'assets/thumbnails/legacy-fallback.svg' });

/* ---- TypeScript emitter: single quotes, unquoted identifier keys, two-space indent ---- */
const ident = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
function ts(value, depth = 0) {
  const pad = '  '.repeat(depth + 1);
  const end = '  '.repeat(depth);
  if (value === null) return 'null';
  if (typeof value === 'string') return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const inline = value.every((v) => typeof v === 'string' || typeof v === 'number');
    if (inline) return `[${value.map((v) => ts(v, depth)).join(', ')}]`;
    return `[\n${value.map((v) => pad + ts(v, depth + 1)).join(',\n')}\n${end}]`;
  }
  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  return `{\n${entries.map(([k, v]) => `${pad}${ident.test(k) ? k : ts(k)}: ${ts(v, depth + 1)}`).join(',\n')}\n${end}}`;
}

const note = (what) => `/**
 * ${what}
 *
 * GENERATED by \`web/src/lib/content-library/port.mjs\`; do not edit by hand.
 *   Source archive: ${archiveRel}
 *   Archive SHA-256: ${archiveSha.slice(7)}
 *   Inputs: rafii-prototype-v9/src/taxonomy-data.json (version ${taxonomy.version}),
 *           rafii-prototype-v9/src/library-data.json (version ${library.version}, reviewed_at ${library.reviewed_at})
 */`;

/* ---- taxonomy.ts ---- */
const items = taxonomy.items.map((item) => {
  const extra = library.items[item.id];
  return {
    id: item.id,
    title: item.title,
    description: item.description,
    family: item.family,
    dimension: item.dimension,
    category: extra.category,
    tags: extra.tags,
    platforms: extra.platforms,
    pairings: extra.pairings.map((p) => p.id),
    platform_support: item.platform_support
  };
});
const editorialCount = items.filter((i) => i.dimension === 'editorial').length;
const nativeCount = items.length - editorialCount;

const taxonomyTs = `${note(`Content Library taxonomy: ${editorialCount} editorial types and ${nativeCount} native formats (Rafii DNA v8 §3.4, §13; prompt §6).
 *
 * Ported losslessly: every field of both prototype files is kept. Item records merge \`taxonomy-data.json\`
 * (title, description, family, dimension, platform_support) with \`library-data.json\` (category, tags,
 * suggested app fit, pairings); artwork fields live in \`artwork.ts\`. Pairings are referenced by id and
 * resolved through \`PAIRINGS\`; evidence records keep their source, period, population and limits so
 * the UI can show them instead of a generic "popular" badge (DNA §22.3). Counts come from this data,
 * never from copied numbers (DNA §22.4).`)}

export type Dimension = 'editorial' | 'native';

export interface LibraryCategory {
  id: string;
  label: string;
  description: string;
}

export interface LibraryPlatform {
  id: string;
  label: string;
}

/** A dated external finding. \`kind\` separates usage signals from engagement signals (DNA §22.3). */
export interface EvidenceRecord {
  id: string;
  label: string;
  kind: string;
  publisher: string;
  date: string;
  url: string;
  finding: string;
  sample: string;
  limit: string;
}

/** Editorial intent → presentation format → suggested app fit. A design suggestion, never a measured ranking. */
export interface Pairing {
  id: string;
  editorial: string;
  native: string;
  platforms: string[];
  why: string;
  evidence: string[];
  kind: 'fit_suggestion';
  surface_note: string;
}

export interface TaxonomyItem {
  id: string;
  title: string;
  description: string;
  family: string;
  dimension: Dimension;
  /** Category id within \`CATEGORIES[dimension]\`. */
  category: string;
  tags: string[];
  /** Suggested app fit (platform ids from \`PLATFORMS\`); empty means a specialist surface. */
  platforms: string[];
  /** Pairing ids, resolved through \`PAIRINGS\`. */
  pairings: string[];
  /** The prototype verified no platform capability; publishing support is decided elsewhere. */
  platform_support: string;
}

/** Where this data came from. The research snapshot date is shown with the evidence, never as live analytics. */
export const TAXONOMY_SOURCE = ${ts({
  archive: archiveRel,
  archiveSha256: archiveSha.slice(7),
  taxonomyVersion: taxonomy.version,
  libraryVersion: library.version,
  reviewedAt: library.reviewed_at
})} as const;

export const CATEGORIES: Record<Dimension, LibraryCategory[]> = ${ts(library.categories)};

export const PLATFORMS: LibraryPlatform[] = ${ts(library.platforms)};

export const EVIDENCE: Record<string, EvidenceRecord> = ${ts(Object.fromEntries(Object.entries(library.evidence).map(([id, e]) => [id, { id, ...e }])))};

export const PAIRINGS: Pairing[] = ${ts(library.pairings)};

export const TAXONOMY: TaxonomyItem[] = ${ts(items)};

export const TAXONOMY_BY_ID: Record<string, TaxonomyItem> = Object.fromEntries(TAXONOMY.map((item) => [item.id, item]));
export const PAIRINGS_BY_ID: Record<string, Pairing> = Object.fromEntries(PAIRINGS.map((pairing) => [pairing.id, pairing]));

export const EDITORIAL_TYPES = TAXONOMY.filter((item) => item.dimension === 'editorial');
export const NATIVE_FORMATS = TAXONOMY.filter((item) => item.dimension === 'native');

export function taxonomyItem(id: string | null | undefined): TaxonomyItem | undefined {
  return id ? TAXONOMY_BY_ID[id] : undefined;
}

export function categoryInfo(dimension: Dimension, id: string): LibraryCategory | undefined {
  return CATEGORIES[dimension].find((category) => category.id === id);
}

export function platformInfo(id: string): LibraryPlatform | undefined {
  return PLATFORMS.find((platform) => platform.id === id);
}
`;

/* ---- artwork-markup.ts ---- */
const largeMarkup = {};
const compactMarkup = {};
for (const file of files) {
  if (file.id === 'legacy-fallback') continue;
  (file.kind === 'thumbnails' ? largeMarkup : compactMarkup)[file.id] = file.bytes.toString('utf8');
}
const markupTs = `${note(`SVG sources for the Content Library artwork: 51 large 8:5 illustrations, 51 compact 1:1 glyphs and the
 * legacy fallback. Each string is the archive file byte for byte (the hashes in \`artwork.ts\` are computed
 * over exactly this text), so ids are namespaced at render time by \`SemanticIllustration\`, never here.`)}

export const LARGE_ARTWORK: Record<string, string> = ${ts(largeMarkup)};

export const COMPACT_ARTWORK: Record<string, string> = ${ts(compactMarkup)};

export const LEGACY_FALLBACK_ARTWORK = ${ts(legacyBytes.toString('utf8'))};
`;

/* ---- artwork.ts ---- */
const meta = {};
for (const item of taxonomy.items) {
  const compact = library.items[item.id].compact_thumbnail;
  meta[item.id] = {
    large: {
      thumbnail_id: item.thumbnail_id,
      thumbnail_kind: item.thumbnail_kind,
      thumbnail_asset_path: `/rafii/library/thumbnails/${item.id}.svg`,
      source_path: `rafii-prototype-v9/src/${item.thumbnail_asset_path}`,
      alt_text: item.alt_text,
      aspect_ratio: item.aspect_ratio,
      visual_concept: item.visual_concept,
      source_type: item.source_type,
      content_hash: item.content_hash,
      version: item.version
    },
    compact: {
      thumbnail_id: compact.thumbnail_id,
      thumbnail_kind: compact.thumbnail_kind,
      thumbnail_asset_path: `/rafii/library/glyphs/${item.id}.svg`,
      source_path: `rafii-prototype-v9/src/${compact.thumbnail_asset_path}`,
      alt_text: compact.alt_text,
      aspect_ratio: compact.aspect_ratio,
      visual_concept: compact.visual_concept,
      source_type: compact.source_type,
      content_hash: compact.content_hash,
      version: compact.version
    }
  };
}
const legacyTitle = /<title>([^<]*)<\/title>/.exec(legacyBytes.toString('utf8'))?.[1] ?? 'Legacy item';
const artworkTs = `${note(`Content Library artwork metadata (DNA v8 §14.4 asset contract): every taxonomy item has one large
 * semantic illustration (8:5) and one compact glyph (1:1), both original deterministic SVGs from the
 * prototype. \`content_hash\` is the SHA-256 of the file bytes, which \`artwork-markup.ts\` embeds unchanged
 * and \`web/public/rafii/library/\` mirrors. The legacy fallback is for explicitly legacy or missing ids
 * only, never a default for a current item (prompt §6).`)}
import { COMPACT_ARTWORK, LARGE_ARTWORK, LEGACY_FALLBACK_ARTWORK } from './artwork-markup';

export type ArtworkSize = 'large' | 'compact';

export interface ArtworkMeta {
  thumbnail_id: string;
  thumbnail_kind: 'svg';
  /** Public URL of the byte-identical copy under \`web/public\`. */
  thumbnail_asset_path: string;
  /** Path inside the source archive. */
  source_path: string;
  alt_text: string;
  aspect_ratio: string;
  visual_concept: string;
  source_type: string;
  content_hash: string;
  version: string;
}

export interface ItemArtwork {
  large: ArtworkMeta;
  compact: ArtworkMeta;
}

export const ARTWORK: Record<string, ItemArtwork> = ${ts(meta)};

export const LEGACY_FALLBACK: ArtworkMeta = ${ts({
  thumbnail_id: 'rafii-legacy-fallback-v1',
  thumbnail_kind: 'svg',
  thumbnail_asset_path: '/rafii/library/thumbnails/legacy-fallback.svg',
  source_path: 'rafii-prototype-v9/src/assets/thumbnails/legacy-fallback.svg',
  alt_text: legacyTitle,
  aspect_ratio: '8:5',
  visual_concept: 'Neutral paper card marking an item the current taxonomy no longer carries.',
  source_type: 'original_deterministic_svg',
  content_hash: sha256(legacyBytes),
  version: '1.0.0'
})};

/** Metadata for one item's artwork, or undefined for an id the taxonomy does not carry. */
export function artworkFor(id: string): ItemArtwork | undefined {
  return ARTWORK[id];
}

/** The SVG source for an asset. Unknown ids get the legacy fallback at large size and nothing at compact size. */
export function artworkMarkup(id: string, size: ArtworkSize): string | null {
  if (size === 'compact') return COMPACT_ARTWORK[id] ?? null;
  return LARGE_ARTWORK[id] ?? LEGACY_FALLBACK_ARTWORK;
}
`;

/* ---- write modules ---- */
writeFileSync(join(here, 'taxonomy.ts'), taxonomyTs);
writeFileSync(join(here, 'artwork-markup.ts'), markupTs);
writeFileSync(join(here, 'artwork.ts'), artworkTs);

/* ---- byte-identical public copies + provenance ---- */
mkdirSync(join(publicDir, 'thumbnails'), { recursive: true });
mkdirSync(join(publicDir, 'glyphs'), { recursive: true });
for (const file of files) writeFileSync(join(publicDir, file.kind, `${file.id}.svg`), file.bytes);

const rows = files.map((file) => `| \`${file.kind}/${file.id}.svg\` | \`${file.source}\` | \`${file.hash.slice(7)}\` |`).join('\n');
const provenance = `# Content Library artwork: provenance

Source archive: \`${archiveRel}\` (SHA-256 \`${archiveSha.slice(7)}\`), the approved Rafii v9 prototype.
Inside it: \`rafii-prototype-v9/src/assets/thumbnails/*.svg\` (large 8:5 illustrations) and
\`rafii-prototype-v9/src/assets/glyphs/*.svg\` (compact 1:1 glyphs). Metadata: \`taxonomy-data.json\`
(version ${taxonomy.version}) and \`library-data.json\` (version ${library.version}, reviewed ${library.reviewed_at}).

Every file here is byte for byte the archive file; the hash column is the SHA-256 the prototype recorded as
\`content_hash\`, re-computed at port time. The prototype describes the art as \`original_deterministic_svg\`
(drawn for the prototype, no stock imagery, external URLs or fonts). Rendering namespaces the internal SVG ids
(\`paper\`, \`shadow\`) per instance and adds motion classes at render time (\`SemanticIllustration\`); the files
stay untouched. \`legacy-fallback.svg\` is for explicitly legacy or missing ids only.

Regenerate with \`node web/src/lib/content-library/port.mjs\`.

| File | Archive path | SHA-256 |
|---|---|---|
${rows}
`;
writeFileSync(join(publicDir, 'PROVENANCE.md'), provenance);
rmSync(work, { recursive: true, force: true });
console.warn(`Ported ${taxonomy.items.length} items (${editorialCount} editorial, ${nativeCount} native), ${files.length} assets.`);
