/**
 * Content Library taxonomy: 31 editorial types and 20 native formats (Rafii DNA v8 §3.4, §13; prompt §6).
 *
 * Ported losslessly: every field of both prototype files is kept. Item records merge `taxonomy-data.json`
 * (title, description, family, dimension, platform_support) with `library-data.json` (category, tags,
 * suggested app fit, pairings); artwork fields live in `artwork.ts`. Pairings are referenced by id and
 * resolved through `PAIRINGS`; evidence records keep their source, period, population and limits so
 * the UI can show them instead of a generic "popular" badge (DNA §22.3). Counts come from this data,
 * never from copied numbers (DNA §22.4).
 *
 * GENERATED by `web/src/lib/content-library/port.mjs`; do not edit by hand.
 *   Source archive: docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip
 *   Archive SHA-256: 285f85ffeb9f04cb9f5d70b29eaab237ccb5d7db336f932d3ad83c9e767bb2fa
 *   Inputs: rafii-prototype-v9/src/taxonomy-data.json (version 1.0.0),
 *           rafii-prototype-v9/src/library-data.json (version 7.0.0, reviewed_at 2026-09-22)
 */

export type Dimension = 'editorial' | 'native';

export interface LibraryCategory {
  id: string;
  label: string;
  description: string;
}

export interface LibraryPlatform {
  id: string;
  label: string;
}

/** A dated external finding. `kind` separates usage signals from engagement signals (DNA §22.3). */
export interface EvidenceRecord {
  id: string;
  label: string;
  kind: string;
  publisher: string;
  date: string;
  url: string;
  finding: string;
  sample: string;
  limit: string;
}

/** Editorial intent → presentation format → suggested app fit. A design suggestion, never a measured ranking. */
export interface Pairing {
  id: string;
  editorial: string;
  native: string;
  platforms: string[];
  why: string;
  evidence: string[];
  kind: 'fit_suggestion';
  surface_note: string;
}

export interface TaxonomyItem {
  id: string;
  title: string;
  description: string;
  family: string;
  dimension: Dimension;
  /** Category id within `CATEGORIES[dimension]`. */
  category: string;
  tags: string[];
  /** Suggested app fit (platform ids from `PLATFORMS`); empty means a specialist surface. */
  platforms: string[];
  /** Pairing ids, resolved through `PAIRINGS`. */
  pairings: string[];
  /** The prototype verified no platform capability; publishing support is decided elsewhere. */
  platform_support: string;
}

/** Where this data came from. The research snapshot date is shown with the evidence, never as live analytics. */
export const TAXONOMY_SOURCE = {
  archive: 'docs/design/reference/rafii-v9/rafii-prototype-v9-source.zip',
  archiveSha256: '285f85ffeb9f04cb9f5d70b29eaab237ccb5d7db336f932d3ad83c9e767bb2fa',
  taxonomyVersion: '1.0.0',
  libraryVersion: '7.0.0',
  reviewedAt: '2026-09-22'
} as const;

export const CATEGORIES: Record<Dimension, LibraryCategory[]> = {
  editorial: [
    {
      id: 'everyday',
      label: 'Everyday',
      description: 'Small updates & real life'
    },
    {
      id: 'news',
      label: 'News & events',
      description: 'What is happening'
    },
    {
      id: 'education',
      label: 'Teach & explain',
      description: 'Make something useful'
    },
    {
      id: 'conversation',
      label: 'Conversations',
      description: 'Invite a response'
    },
    {
      id: 'showcase',
      label: 'Showcase & proof',
      description: 'Show what makes it work'
    },
    {
      id: 'growth',
      label: 'Products & offers',
      description: 'What is new or available'
    },
    {
      id: 'community',
      label: 'Community',
      description: 'Bring people together'
    }
  ],
  native: [
    {
      id: 'reading',
      label: 'Text & reading',
      description: 'Words with room to breathe'
    },
    {
      id: 'visual',
      label: 'Visual',
      description: 'Pictures that tell the story'
    },
    {
      id: 'video',
      label: 'Video & live',
      description: 'Moving stories'
    },
    {
      id: 'interactive',
      label: 'Interactive',
      description: 'Participation, not just viewing'
    },
    {
      id: 'audio',
      label: 'Audio',
      description: 'Something to listen to'
    },
    {
      id: 'community',
      label: 'Community',
      description: 'For a shared space'
    },
    {
      id: 'business',
      label: 'Business',
      description: 'Services, products & places'
    }
  ]
};

export const PLATFORMS: LibraryPlatform[] = [
  {
    id: 'instagram',
    label: 'Instagram'
  },
  {
    id: 'linkedin',
    label: 'LinkedIn'
  },
  {
    id: 'threads',
    label: 'Threads'
  },
  {
    id: 'x',
    label: 'X'
  },
  {
    id: 'facebook',
    label: 'Facebook'
  },
  {
    id: 'red',
    label: 'Xiaohongshu'
  }
];

export const EVIDENCE: Record<string, EvidenceRecord> = {
  'ig-saves': {
    id: 'ig-saves',
    label: 'Save-focused format',
    kind: 'Engagement signal',
    publisher: 'Metricool',
    date: '2026-06-16',
    url: 'https://metricool.com/press-release-instagram-study-2026/',
    finding: 'Carousels generated nine times more saves than single-image posts in the study.',
    sample: '24,364,803 Instagram posts; 375,118 accounts; Jan–Feb 2025 vs Jan–Feb 2026.',
    limit: 'Averages in this sample, not a popularity rank or proof that a specific editorial topic works.'
  },
  'ig-usage': {
    id: 'ig-usage',
    label: 'Usage ≠ engagement',
    kind: 'Usage signal',
    publisher: 'Metricool',
    date: '2026-06',
    url: 'https://metricool.com/instagram-carousel-multiple-captions/',
    finding: 'Carousels were used 37% less often than single-image posts in Metricool’s 2026 Instagram analysis.',
    sample: '2026 Instagram study; Jan–Feb 2025 vs Jan–Feb 2026.',
    limit: 'Relative usage in the sample, not the most-used editorial type and not live trend data.'
  },
  'li-docs': {
    id: 'li-docs',
    label: 'Document engagement',
    kind: 'Engagement signal',
    publisher: 'Buffer',
    date: '2026-03-19',
    url: 'https://buffer.com/resources/data-best-content-format-social-media/',
    finding: 'LinkedIn document carousels recorded a 21.77% median engagement rate in this dataset.',
    sample: 'Buffer-published posts; underlying engagement report data through Dec 3, 2025.',
    limit: 'LinkedIn documents, not Instagram image carousels. Engagement is platform-defined; no cross-platform ranking.'
  },
  'li-usage': {
    id: 'li-usage',
    label: 'What gets posted',
    kind: 'Usage signal',
    publisher: 'Metricool',
    date: '2026-04-14',
    url: 'https://metricool.com/press-release-linkedin-study-2026/',
    finding: 'Images and video made up nearly 75% of Company Page posts; video was the most-used format among Personal Profiles in this sample.',
    sample: '673,658 posts; 63,108 LinkedIn accounts; Jan–Feb 2025 vs Jan–Feb 2026.',
    limit: 'Company Pages and Personal Profiles differ. This measures format use, not which editorial topic is most popular.'
  },
  'ig-reach': {
    id: 'ig-reach',
    label: 'Discovery vs depth',
    kind: 'Engagement signal',
    publisher: 'Buffer',
    date: '2026-03-05',
    url: 'https://buffer.com/resources/state-of-social-media-engagement-2026/',
    finding: 'The Instagram reach study found Reels reached 36% more people than carousels.',
    sample: 'Separate Instagram analysis: 4M+ Buffer posts, Jan 2022–Oct 2024.',
    limit: 'Older reach data, not a current algorithm guarantee. It does not measure editorial topic popularity.'
  },
  'x-text': {
    id: 'x-text',
    label: 'Text engagement',
    kind: 'Engagement signal',
    publisher: 'Buffer',
    date: '2026-03-19',
    url: 'https://buffer.com/resources/data-best-content-format-social-media/',
    finding: 'X text posts had 3.56% median engagement, compared with 3.40% for images.',
    sample: 'Buffer-published posts; 2026 format report, underlying data through Dec 3, 2025.',
    limit: 'Format-level, not a ranking of opinions, questions or other editorial types.'
  },
  'threads-visual': {
    id: 'threads-visual',
    label: 'Try a visual',
    kind: 'Engagement signal',
    publisher: 'Buffer',
    date: '2026-03-19',
    url: 'https://buffer.com/resources/data-best-content-format-social-media/',
    finding: 'Threads video had 5.55% median engagement, compared with 2.79% for text in the dataset.',
    sample: 'Buffer-published posts; underlying data through Dec 3, 2025.',
    limit: 'Not proof that every visual performs better; editorial pairing is a separate design suggestion.'
  },
  'fb-mix': {
    id: 'fb-mix',
    label: 'A close format race',
    kind: 'Engagement signal',
    publisher: 'Buffer',
    date: '2026-03-19',
    url: 'https://buffer.com/resources/data-best-content-format-social-media/',
    finding: 'Facebook image, video and text median engagement rates were within one percentage point of each other.',
    sample: 'Buffer-published posts; underlying data through Dec 3, 2025.',
    limit: 'No decisive universal winner. Fit the format to the idea, then test your own audience.'
  }
};

export const PAIRINGS: Pairing[] = [
  {
    id: 'status_update-text',
    editorial: 'status_update',
    native: 'text',
    platforms: ['threads', 'x', 'facebook'],
    why: 'A short note that invites an easy reply.',
    evidence: ['x-text', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'status_update-image_caption',
    editorial: 'status_update',
    native: 'image_caption',
    platforms: ['instagram', 'linkedin'],
    why: 'Add a picture when the update is visual.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'announcement-image_caption',
    editorial: 'announcement',
    native: 'image_caption',
    platforms: ['instagram', 'facebook', 'linkedin'],
    why: 'Lead with a clear message, then the details.',
    evidence: ['li-usage', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'announcement-text',
    editorial: 'announcement',
    native: 'text',
    platforms: ['x', 'threads'],
    why: 'Keep the essential news in one short update.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'news_curation-link_preview',
    editorial: 'news_curation',
    native: 'link_preview',
    platforms: ['linkedin', 'facebook'],
    why: 'Keep the original source attached.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'news_curation-thread',
    editorial: 'news_curation',
    native: 'thread',
    platforms: ['x', 'threads'],
    why: 'Give each source its own piece of context.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'opinion_commentary-text',
    editorial: 'opinion_commentary',
    native: 'text',
    platforms: ['threads', 'x', 'linkedin'],
    why: 'Make one clear point, then invite another view.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'opinion_commentary-long_text',
    editorial: 'opinion_commentary',
    native: 'long_text',
    platforms: ['linkedin', 'facebook'],
    why: 'Use more space when context matters.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'quote-quote_card',
    editorial: 'quote',
    native: 'quote_card',
    platforms: ['instagram', 'facebook'],
    why: 'Turn a properly attributed quote into a visual.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'quote-text',
    editorial: 'quote',
    native: 'text',
    platforms: ['threads', 'x'],
    why: 'Let the words stand on their own.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'question_prompt-text',
    editorial: 'question_prompt',
    native: 'text',
    platforms: ['threads', 'x', 'linkedin'],
    why: 'Ask one specific, answerable question.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'question_prompt-image_caption',
    editorial: 'question_prompt',
    native: 'image_caption',
    platforms: ['instagram', 'facebook'],
    why: 'Use the visual to set up the question.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'poll_quiz-poll',
    editorial: 'poll_quiz',
    native: 'poll',
    platforms: ['linkedin', 'x'],
    why: 'A participation-first plan; check account capabilities.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'poll_quiz-quiz',
    editorial: 'poll_quiz',
    native: 'quiz',
    platforms: ['instagram'],
    why: 'Plan a Story-based quiz, not a feed quiz.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'how_to-carousel',
    editorial: 'how_to',
    native: 'carousel',
    platforms: ['instagram', 'red'],
    why: 'Give each practical step a separate frame.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'how_to-document',
    editorial: 'how_to',
    native: 'document',
    platforms: ['linkedin'],
    why: 'Package the steps in a swipeable document.',
    evidence: ['li-docs'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'educational_explainer-carousel',
    editorial: 'educational_explainer',
    native: 'carousel',
    platforms: ['instagram', 'red'],
    why: 'Break a concept into a few visual steps.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'educational_explainer-document',
    editorial: 'educational_explainer',
    native: 'document',
    platforms: ['linkedin'],
    why: 'Use a document for diagrams and deeper explanation.',
    evidence: ['li-docs'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'list_checklist-carousel',
    editorial: 'list_checklist',
    native: 'carousel',
    platforms: ['instagram', 'red'],
    why: 'One useful checklist item per slide.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'list_checklist-document',
    editorial: 'list_checklist',
    native: 'document',
    platforms: ['linkedin'],
    why: 'An easy-to-return-to reference document.',
    evidence: ['li-docs'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'review_comparison-carousel',
    editorial: 'review_comparison',
    native: 'carousel',
    platforms: ['instagram', 'red'],
    why: 'Compare the same criteria side by side.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'review_comparison-long_text',
    editorial: 'review_comparison',
    native: 'long_text',
    platforms: ['linkedin'],
    why: 'State your criteria, evidence and limitations.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'resource_roundup-document',
    editorial: 'resource_roundup',
    native: 'document',
    platforms: ['linkedin'],
    why: 'Collect resources in one organised reference.',
    evidence: ['li-docs'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'resource_roundup-thread',
    editorial: 'resource_roundup',
    native: 'thread',
    platforms: ['x', 'threads'],
    why: 'One resource and one reason per entry.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'product_service_showcase-short_vertical_video',
    editorial: 'product_service_showcase',
    native: 'short_vertical_video',
    platforms: ['instagram', 'facebook'],
    why: 'Show the product or service in use.',
    evidence: ['ig-reach', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'product_service_showcase-image_caption',
    editorial: 'product_service_showcase',
    native: 'image_caption',
    platforms: ['red', 'linkedin'],
    why: 'Let the visual and a concrete benefit work together.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'product_update-image_caption',
    editorial: 'product_update',
    native: 'image_caption',
    platforms: ['linkedin', 'x'],
    why: 'Show what changed, not just that it changed.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'product_update-short_vertical_video',
    editorial: 'product_update',
    native: 'short_vertical_video',
    platforms: ['instagram'],
    why: 'Demonstrate the updated flow.',
    evidence: ['ig-reach'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'launch_release-short_vertical_video',
    editorial: 'launch_release',
    native: 'short_vertical_video',
    platforms: ['instagram', 'facebook'],
    why: 'Make the new thing understandable at a glance.',
    evidence: ['ig-reach', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'launch_release-image_caption',
    editorial: 'launch_release',
    native: 'image_caption',
    platforms: ['linkedin', 'x'],
    why: 'Lead with the release and who it helps.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'promotion_offer-image_caption',
    editorial: 'promotion_offer',
    native: 'image_caption',
    platforms: ['instagram', 'facebook'],
    why: 'Show the offer and its terms without clutter.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'promotion_offer-story',
    editorial: 'promotion_offer',
    native: 'story',
    platforms: ['instagram', 'facebook'],
    why: 'A time-specific offer for your existing audience.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'event_live-image_caption',
    editorial: 'event_live',
    native: 'image_caption',
    platforms: ['facebook', 'linkedin'],
    why: 'Lead with what, when and where.',
    evidence: ['li-usage', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'event_live-story',
    editorial: 'event_live',
    native: 'story',
    platforms: ['instagram'],
    why: 'Share short event moments; this is not a live stream.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'behind_the_scenes-short_vertical_video',
    editorial: 'behind_the_scenes',
    native: 'short_vertical_video',
    platforms: ['instagram', 'facebook'],
    why: 'Show a small piece of the real process.',
    evidence: ['ig-reach', 'fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'behind_the_scenes-image_caption',
    editorial: 'behind_the_scenes',
    native: 'image_caption',
    platforms: ['red', 'threads'],
    why: 'Pair a work-in-progress image with the story behind it.',
    evidence: ['threads-visual'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'personal_lifestyle-image_caption',
    editorial: 'personal_lifestyle',
    native: 'image_caption',
    platforms: ['instagram', 'red'],
    why: 'A daily moment with personal context.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'personal_lifestyle-text',
    editorial: 'personal_lifestyle',
    native: 'text',
    platforms: ['threads'],
    why: 'A small, conversational reflection.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'milestone-image_caption',
    editorial: 'milestone',
    native: 'image_caption',
    platforms: ['linkedin', 'instagram'],
    why: 'Share the milestone and what made it possible.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'milestone-text',
    editorial: 'milestone',
    native: 'text',
    platforms: ['threads', 'x'],
    why: 'A small celebration and a word of thanks.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'ugc_testimonial-quote_card',
    editorial: 'ugc_testimonial',
    native: 'quote_card',
    platforms: ['instagram', 'linkedin'],
    why: 'Use a genuine quote with permission and attribution.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'ugc_testimonial-image_caption',
    editorial: 'ugc_testimonial',
    native: 'image_caption',
    platforms: ['facebook', 'red'],
    why: 'Let real customer evidence stay identifiable.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'case_study-document',
    editorial: 'case_study',
    native: 'document',
    platforms: ['linkedin'],
    why: 'Explain the problem, method, evidence and result.',
    evidence: ['li-docs'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'case_study-carousel',
    editorial: 'case_study',
    native: 'carousel',
    platforms: ['instagram'],
    why: 'Turn the evidence into a short visual narrative.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'qa_faq-carousel',
    editorial: 'qa_faq',
    native: 'carousel',
    platforms: ['instagram'],
    why: 'Answer one question per slide.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'qa_faq-long_text',
    editorial: 'qa_faq',
    native: 'long_text',
    platforms: ['linkedin', 'facebook'],
    why: 'Collect clear answers with necessary context.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'community_announcement-community_message',
    editorial: 'community_announcement',
    native: 'community_message',
    platforms: ['facebook'],
    why: 'A notice for a specific group; surface access varies.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'community_announcement-text',
    editorial: 'community_announcement',
    native: 'text',
    platforms: ['threads'],
    why: 'Make it clear who the message is for.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'cause_advocacy-image_caption',
    editorial: 'cause_advocacy',
    native: 'image_caption',
    platforms: ['instagram', 'facebook'],
    why: 'Explain the cause with context and reliable sources.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'cause_advocacy-long_text',
    editorial: 'cause_advocacy',
    native: 'long_text',
    platforms: ['linkedin'],
    why: 'Keep facts, opinion and calls to action distinct.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'contest_challenge-image_caption',
    editorial: 'contest_challenge',
    native: 'image_caption',
    platforms: ['instagram', 'facebook'],
    why: 'Make steps and eligibility clear; review contest rules.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'contest_challenge-short_vertical_video',
    editorial: 'contest_challenge',
    native: 'short_vertical_video',
    platforms: ['red'],
    why: 'Demonstrate the challenge; check platform rules.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'job_recruitment-image_caption',
    editorial: 'job_recruitment',
    native: 'image_caption',
    platforms: ['linkedin'],
    why: 'Show the role, expectations and application route.',
    evidence: ['li-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'job_recruitment-link_preview',
    editorial: 'job_recruitment',
    native: 'link_preview',
    platforms: ['facebook'],
    why: 'Link to the complete role description.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'article_blog_newsletter-native_article',
    editorial: 'article_blog_newsletter',
    native: 'native_article',
    platforms: ['linkedin'],
    why: 'A reading-first plan; account and surface access vary.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'article_blog_newsletter-link_preview',
    editorial: 'article_blog_newsletter',
    native: 'link_preview',
    platforms: ['facebook', 'x'],
    why: 'Introduce a longer piece with its source link.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'recap_followup-carousel',
    editorial: 'recap_followup',
    native: 'carousel',
    platforms: ['instagram', 'red'],
    why: 'Sequence the moments with a clear beginning and end.',
    evidence: ['ig-saves', 'ig-usage'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'recap_followup-thread',
    editorial: 'recap_followup',
    native: 'thread',
    platforms: ['x', 'threads'],
    why: 'Connect the key takeaways.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'reaction_reply-text',
    editorial: 'reaction_reply',
    native: 'text',
    platforms: ['threads', 'x'],
    why: 'Respond to the actual context, not just a headline.',
    evidence: ['x-text'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'reaction_reply-image_caption',
    editorial: 'reaction_reply',
    native: 'image_caption',
    platforms: ['facebook'],
    why: 'Add a relevant image when it clarifies the response.',
    evidence: ['fb-mix'],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'live_ama-livestream',
    editorial: 'live_ama',
    native: 'livestream',
    platforms: ['instagram', 'facebook'],
    why: 'Plan questions and moderation; eligibility is unverified.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'live_ama-thread',
    editorial: 'live_ama',
    native: 'thread',
    platforms: ['threads', 'x'],
    why: 'A text-based Q&A alternative, not a live broadcast.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Planning fit only. Account, app surface and publishing/API support are not verified.'
  },
  {
    id: 'educational_explainer-long_video',
    editorial: 'educational_explainer',
    native: 'long_video',
    platforms: ['linkedin', 'facebook'],
    why: 'A longer filmed explanation; limits are not verified.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Specialist or conditional surface. Check availability before use.'
  },
  {
    id: 'opinion_commentary-audio',
    editorial: 'opinion_commentary',
    native: 'audio',
    platforms: [],
    why: 'An audio plan. No direct match among the six demo apps is verified.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Specialist or conditional surface. Check availability before use.'
  },
  {
    id: 'community_announcement-broadcast_message',
    editorial: 'community_announcement',
    native: 'broadcast_message',
    platforms: ['instagram'],
    why: 'Plan for an eligible broadcast surface, not a regular feed post.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Specialist or conditional surface. Check availability before use.'
  },
  {
    id: 'product_service_showcase-product_catalog',
    editorial: 'product_service_showcase',
    native: 'product_catalog',
    platforms: ['facebook', 'instagram'],
    why: 'Commerce-enabled surface only; availability is not verified.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Specialist or conditional surface. Check availability before use.'
  },
  {
    id: 'event_live-local_business_update',
    editorial: 'event_live',
    native: 'local_business_update',
    platforms: ['facebook'],
    why: 'A local update plan. Adapt to an available Page surface.',
    evidence: [],
    kind: 'fit_suggestion',
    surface_note: 'Specialist or conditional surface. Check availability before use.'
  }
];

export const TAXONOMY: TaxonomyItem[] = [
  {
    id: 'status_update',
    title: 'Status update',
    description: 'Share a quick update on what is happening.',
    family: 'Everyday',
    dimension: 'editorial',
    category: 'everyday',
    tags: ['editorial', 'everyday'],
    platforms: ['facebook', 'instagram', 'linkedin', 'threads', 'x'],
    pairings: ['status_update-text', 'status_update-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'announcement',
    title: 'Announcement',
    description: 'Put an important message front and centre.',
    family: 'News',
    dimension: 'editorial',
    category: 'news',
    tags: ['editorial', 'news'],
    platforms: ['facebook', 'instagram', 'linkedin', 'threads', 'x'],
    pairings: ['announcement-image_caption', 'announcement-text'],
    platform_support: 'unverified'
  },
  {
    id: 'news_curation',
    title: 'News curation',
    description: 'Bring relevant stories and sources together.',
    family: 'News',
    dimension: 'editorial',
    category: 'news',
    tags: ['editorial', 'news'],
    platforms: ['facebook', 'linkedin', 'threads', 'x'],
    pairings: ['news_curation-link_preview', 'news_curation-thread'],
    platform_support: 'unverified'
  },
  {
    id: 'opinion_commentary',
    title: 'Opinion & commentary',
    description: 'Share a perspective and invite another.',
    family: 'Conversation',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['facebook', 'linkedin', 'threads', 'x'],
    pairings: ['opinion_commentary-text', 'opinion_commentary-long_text', 'opinion_commentary-audio'],
    platform_support: 'unverified'
  },
  {
    id: 'quote',
    title: 'Quote',
    description: 'Give a memorable thought room to resonate.',
    family: 'Conversation',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['facebook', 'instagram', 'threads', 'x'],
    pairings: ['quote-quote_card', 'quote-text'],
    platform_support: 'unverified'
  },
  {
    id: 'question_prompt',
    title: 'Question prompt',
    description: 'Start a conversation with an open question.',
    family: 'Conversation',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['facebook', 'instagram', 'linkedin', 'threads', 'x'],
    pairings: ['question_prompt-text', 'question_prompt-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'poll_quiz',
    title: 'Poll or quiz',
    description: 'Invite your audience to choose or explore.',
    family: 'Conversation',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['instagram', 'linkedin', 'x'],
    pairings: ['poll_quiz-poll', 'poll_quiz-quiz'],
    platform_support: 'unverified'
  },
  {
    id: 'how_to',
    title: 'How-to',
    description: 'Turn a process into clear, practical steps.',
    family: 'Education',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['instagram', 'linkedin', 'red'],
    pairings: ['how_to-carousel', 'how_to-document'],
    platform_support: 'unverified'
  },
  {
    id: 'educational_explainer',
    title: 'Educational explainer',
    description: 'Make a complex idea easier to understand.',
    family: 'Education',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['facebook', 'instagram', 'linkedin', 'red'],
    pairings: ['educational_explainer-carousel', 'educational_explainer-document', 'educational_explainer-long_video'],
    platform_support: 'unverified'
  },
  {
    id: 'list_checklist',
    title: 'List & checklist',
    description: 'Organise useful advice into actionable items.',
    family: 'Education',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['instagram', 'linkedin', 'red'],
    pairings: ['list_checklist-carousel', 'list_checklist-document'],
    platform_support: 'unverified'
  },
  {
    id: 'review_comparison',
    title: 'Review & comparison',
    description: 'Examine the differences that matter.',
    family: 'Education',
    dimension: 'editorial',
    category: 'showcase',
    tags: ['editorial', 'showcase'],
    platforms: ['instagram', 'linkedin', 'red'],
    pairings: ['review_comparison-carousel', 'review_comparison-long_text'],
    platform_support: 'unverified'
  },
  {
    id: 'resource_roundup',
    title: 'Resource roundup',
    description: 'Curate useful tools, books and references.',
    family: 'Education',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['linkedin', 'threads', 'x'],
    pairings: ['resource_roundup-document', 'resource_roundup-thread'],
    platform_support: 'unverified'
  },
  {
    id: 'product_service_showcase',
    title: 'Product & service showcase',
    description: 'Show what you offer and who it helps.',
    family: 'Business',
    dimension: 'editorial',
    category: 'showcase',
    tags: ['editorial', 'showcase'],
    platforms: ['facebook', 'instagram', 'linkedin', 'red'],
    pairings: ['product_service_showcase-short_vertical_video', 'product_service_showcase-image_caption', 'product_service_showcase-product_catalog'],
    platform_support: 'unverified'
  },
  {
    id: 'product_update',
    title: 'Product update',
    description: 'Explain what changed and why it matters.',
    family: 'Business',
    dimension: 'editorial',
    category: 'growth',
    tags: ['editorial', 'growth'],
    platforms: ['instagram', 'linkedin', 'x'],
    pairings: ['product_update-image_caption', 'product_update-short_vertical_video'],
    platform_support: 'unverified'
  },
  {
    id: 'launch_release',
    title: 'Launch & release',
    description: 'Introduce something new to the world.',
    family: 'Business',
    dimension: 'editorial',
    category: 'growth',
    tags: ['editorial', 'growth'],
    platforms: ['facebook', 'instagram', 'linkedin', 'x'],
    pairings: ['launch_release-short_vertical_video', 'launch_release-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'promotion_offer',
    title: 'Promotion & offer',
    description: 'Communicate an offer and its clear benefit.',
    family: 'Business',
    dimension: 'editorial',
    category: 'growth',
    tags: ['editorial', 'growth'],
    platforms: ['facebook', 'instagram'],
    pairings: ['promotion_offer-image_caption', 'promotion_offer-story'],
    platform_support: 'unverified'
  },
  {
    id: 'event_live',
    title: 'Event & live coverage',
    description: 'Invite people in and share the occasion.',
    family: 'Community',
    dimension: 'editorial',
    category: 'news',
    tags: ['editorial', 'news'],
    platforms: ['facebook', 'instagram', 'linkedin'],
    pairings: ['event_live-image_caption', 'event_live-story', 'event_live-local_business_update'],
    platform_support: 'unverified'
  },
  {
    id: 'behind_the_scenes',
    title: 'Behind the scenes',
    description: 'Show the process behind the finished work.',
    family: 'Story',
    dimension: 'editorial',
    category: 'everyday',
    tags: ['editorial', 'everyday'],
    platforms: ['facebook', 'instagram', 'red', 'threads'],
    pairings: ['behind_the_scenes-short_vertical_video', 'behind_the_scenes-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'personal_lifestyle',
    title: 'Personal & lifestyle',
    description: 'Share a thoughtful glimpse of daily life.',
    family: 'Story',
    dimension: 'editorial',
    category: 'everyday',
    tags: ['editorial', 'everyday'],
    platforms: ['instagram', 'red', 'threads'],
    pairings: ['personal_lifestyle-image_caption', 'personal_lifestyle-text'],
    platform_support: 'unverified'
  },
  {
    id: 'milestone',
    title: 'Milestone',
    description: 'Mark a meaningful step along the way.',
    family: 'Story',
    dimension: 'editorial',
    category: 'everyday',
    tags: ['editorial', 'everyday'],
    platforms: ['instagram', 'linkedin', 'threads', 'x'],
    pairings: ['milestone-image_caption', 'milestone-text'],
    platform_support: 'unverified'
  },
  {
    id: 'ugc_testimonial',
    title: 'UGC & testimonial',
    description: 'Share an authentic community experience.',
    family: 'Evidence',
    dimension: 'editorial',
    category: 'showcase',
    tags: ['editorial', 'showcase'],
    platforms: ['facebook', 'instagram', 'linkedin', 'red'],
    pairings: ['ugc_testimonial-quote_card', 'ugc_testimonial-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'case_study',
    title: 'Case study',
    description: 'Connect a real challenge, action and result.',
    family: 'Evidence',
    dimension: 'editorial',
    category: 'showcase',
    tags: ['editorial', 'showcase'],
    platforms: ['instagram', 'linkedin'],
    pairings: ['case_study-document', 'case_study-carousel'],
    platform_support: 'unverified'
  },
  {
    id: 'qa_faq',
    title: 'Q&A / FAQ',
    description: 'Answer the questions people keep asking.',
    family: 'Education',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['facebook', 'instagram', 'linkedin'],
    pairings: ['qa_faq-carousel', 'qa_faq-long_text'],
    platform_support: 'unverified'
  },
  {
    id: 'community_announcement',
    title: 'Community announcement',
    description: 'Keep your group informed and included.',
    family: 'Community',
    dimension: 'editorial',
    category: 'community',
    tags: ['editorial', 'community'],
    platforms: ['facebook', 'instagram', 'threads'],
    pairings: ['community_announcement-community_message', 'community_announcement-text', 'community_announcement-broadcast_message'],
    platform_support: 'unverified'
  },
  {
    id: 'cause_advocacy',
    title: 'Cause & advocacy',
    description: 'Explain a cause with context and supporting facts.',
    family: 'Community',
    dimension: 'editorial',
    category: 'community',
    tags: ['editorial', 'community'],
    platforms: ['facebook', 'instagram', 'linkedin'],
    pairings: ['cause_advocacy-image_caption', 'cause_advocacy-long_text'],
    platform_support: 'unverified'
  },
  {
    id: 'contest_challenge',
    title: 'Contest & challenge',
    description: 'Set out a challenge and how to take part.',
    family: 'Community',
    dimension: 'editorial',
    category: 'community',
    tags: ['editorial', 'community'],
    platforms: ['facebook', 'instagram', 'red'],
    pairings: ['contest_challenge-image_caption', 'contest_challenge-short_vertical_video'],
    platform_support: 'unverified'
  },
  {
    id: 'job_recruitment',
    title: 'Job & recruitment',
    description: 'Describe a role and invite applications.',
    family: 'Business',
    dimension: 'editorial',
    category: 'community',
    tags: ['editorial', 'community'],
    platforms: ['facebook', 'linkedin'],
    pairings: ['job_recruitment-image_caption', 'job_recruitment-link_preview'],
    platform_support: 'unverified'
  },
  {
    id: 'article_blog_newsletter',
    title: 'Article, blog & newsletter',
    description: 'Develop an idea with editorial depth.',
    family: 'Story',
    dimension: 'editorial',
    category: 'education',
    tags: ['editorial', 'education'],
    platforms: ['facebook', 'linkedin', 'x'],
    pairings: ['article_blog_newsletter-native_article', 'article_blog_newsletter-link_preview'],
    platform_support: 'unverified'
  },
  {
    id: 'recap_followup',
    title: 'Recap & follow-up',
    description: 'Revisit key moments and what comes next.',
    family: 'Story',
    dimension: 'editorial',
    category: 'everyday',
    tags: ['editorial', 'everyday'],
    platforms: ['instagram', 'red', 'threads', 'x'],
    pairings: ['recap_followup-carousel', 'recap_followup-thread'],
    platform_support: 'unverified'
  },
  {
    id: 'reaction_reply',
    title: 'Reaction & reply',
    description: 'Respond thoughtfully to another contribution.',
    family: 'Conversation',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['facebook', 'threads', 'x'],
    pairings: ['reaction_reply-text', 'reaction_reply-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'live_ama',
    title: 'Live AMA',
    description: 'Invite questions for a live conversation.',
    family: 'Community',
    dimension: 'editorial',
    category: 'conversation',
    tags: ['editorial', 'conversation'],
    platforms: ['facebook', 'instagram', 'threads', 'x'],
    pairings: ['live_ama-livestream', 'live_ama-thread'],
    platform_support: 'unverified'
  },
  {
    id: 'text',
    title: 'Text',
    description: 'A concise post with words at its centre.',
    family: 'Written',
    dimension: 'native',
    category: 'reading',
    tags: ['format', 'reading'],
    platforms: ['facebook', 'linkedin', 'threads', 'x'],
    pairings: ['status_update-text', 'announcement-text', 'opinion_commentary-text', 'quote-text', 'question_prompt-text', 'personal_lifestyle-text', 'milestone-text', 'community_announcement-text', 'reaction_reply-text'],
    platform_support: 'unverified'
  },
  {
    id: 'long_text',
    title: 'Long text',
    description: 'A longer post with distinct sections.',
    family: 'Written',
    dimension: 'native',
    category: 'reading',
    tags: ['format', 'reading'],
    platforms: ['facebook', 'linkedin'],
    pairings: ['opinion_commentary-long_text', 'review_comparison-long_text', 'qa_faq-long_text', 'cause_advocacy-long_text'],
    platform_support: 'unverified'
  },
  {
    id: 'thread',
    title: 'Thread',
    description: 'A connected sequence of short posts.',
    family: 'Written',
    dimension: 'native',
    category: 'reading',
    tags: ['format', 'reading'],
    platforms: ['threads', 'x'],
    pairings: ['news_curation-thread', 'resource_roundup-thread', 'recap_followup-thread', 'live_ama-thread'],
    platform_support: 'unverified'
  },
  {
    id: 'image_caption',
    title: 'Image + caption',
    description: 'Pair a visual with its written context.',
    family: 'Visual',
    dimension: 'native',
    category: 'visual',
    tags: ['format', 'visual'],
    platforms: ['facebook', 'instagram', 'linkedin', 'red', 'threads', 'x'],
    pairings: ['status_update-image_caption', 'announcement-image_caption', 'question_prompt-image_caption', 'product_service_showcase-image_caption', 'product_update-image_caption', 'launch_release-image_caption', 'promotion_offer-image_caption', 'event_live-image_caption', 'behind_the_scenes-image_caption', 'personal_lifestyle-image_caption', 'milestone-image_caption', 'ugc_testimonial-image_caption', 'cause_advocacy-image_caption', 'contest_challenge-image_caption', 'job_recruitment-image_caption', 'reaction_reply-image_caption'],
    platform_support: 'unverified'
  },
  {
    id: 'quote_card',
    title: 'Quote card',
    description: 'Set a quotation in an expressive graphic.',
    family: 'Visual',
    dimension: 'native',
    category: 'visual',
    tags: ['format', 'visual'],
    platforms: ['facebook', 'instagram', 'linkedin'],
    pairings: ['quote-quote_card', 'ugc_testimonial-quote_card'],
    platform_support: 'unverified'
  },
  {
    id: 'carousel',
    title: 'Carousel',
    description: 'Tell a story across a sequence of slides.',
    family: 'Visual',
    dimension: 'native',
    category: 'visual',
    tags: ['format', 'visual'],
    platforms: ['instagram', 'red'],
    pairings: ['how_to-carousel', 'educational_explainer-carousel', 'list_checklist-carousel', 'review_comparison-carousel', 'case_study-carousel', 'qa_faq-carousel', 'recap_followup-carousel'],
    platform_support: 'unverified'
  },
  {
    id: 'link_preview',
    title: 'Link preview',
    description: 'Introduce a destination with a summary.',
    family: 'Written',
    dimension: 'native',
    category: 'visual',
    tags: ['format', 'visual'],
    platforms: ['facebook', 'linkedin', 'x'],
    pairings: ['news_curation-link_preview', 'job_recruitment-link_preview', 'article_blog_newsletter-link_preview'],
    platform_support: 'unverified'
  },
  {
    id: 'native_article',
    title: 'Native article',
    description: 'A long-form editorial reading experience.',
    family: 'Written',
    dimension: 'native',
    category: 'reading',
    tags: ['format', 'reading'],
    platforms: ['linkedin'],
    pairings: ['article_blog_newsletter-native_article'],
    platform_support: 'unverified'
  },
  {
    id: 'document',
    title: 'Document',
    description: 'Present a multi-page document or PDF.',
    family: 'Written',
    dimension: 'native',
    category: 'reading',
    tags: ['format', 'reading'],
    platforms: ['linkedin'],
    pairings: ['how_to-document', 'educational_explainer-document', 'list_checklist-document', 'resource_roundup-document', 'case_study-document'],
    platform_support: 'unverified'
  },
  {
    id: 'short_vertical_video',
    title: 'Short vertical video',
    description: 'Plan a short, portrait-oriented video.',
    family: 'Video',
    dimension: 'native',
    category: 'video',
    tags: ['format', 'video'],
    platforms: ['facebook', 'instagram', 'red'],
    pairings: ['product_service_showcase-short_vertical_video', 'product_update-short_vertical_video', 'launch_release-short_vertical_video', 'behind_the_scenes-short_vertical_video', 'contest_challenge-short_vertical_video'],
    platform_support: 'unverified'
  },
  {
    id: 'long_video',
    title: 'Long video',
    description: 'Plan a longer, widescreen video.',
    family: 'Video',
    dimension: 'native',
    category: 'video',
    tags: ['format', 'video'],
    platforms: ['facebook', 'linkedin'],
    pairings: ['educational_explainer-long_video'],
    platform_support: 'unverified'
  },
  {
    id: 'livestream',
    title: 'Livestream',
    description: 'Plan a live broadcast and its context.',
    family: 'Video',
    dimension: 'native',
    category: 'video',
    tags: ['format', 'video'],
    platforms: ['facebook', 'instagram'],
    pairings: ['live_ama-livestream'],
    platform_support: 'unverified'
  },
  {
    id: 'story',
    title: 'Story',
    description: 'Compose a short vertical story sequence.',
    family: 'Visual',
    dimension: 'native',
    category: 'visual',
    tags: ['format', 'visual'],
    platforms: ['facebook', 'instagram'],
    pairings: ['promotion_offer-story', 'event_live-story'],
    platform_support: 'unverified'
  },
  {
    id: 'poll',
    title: 'Poll',
    description: 'Present a question with selectable answers.',
    family: 'Interactive',
    dimension: 'native',
    category: 'interactive',
    tags: ['format', 'interactive'],
    platforms: ['linkedin', 'x'],
    pairings: ['poll_quiz-poll'],
    platform_support: 'unverified'
  },
  {
    id: 'quiz',
    title: 'Quiz',
    description: 'Pair a question with answer choices.',
    family: 'Interactive',
    dimension: 'native',
    category: 'interactive',
    tags: ['format', 'interactive'],
    platforms: ['instagram'],
    pairings: ['poll_quiz-quiz'],
    platform_support: 'unverified'
  },
  {
    id: 'audio',
    title: 'Audio',
    description: 'Plan an audio clip or listening experience.',
    family: 'Audio',
    dimension: 'native',
    category: 'audio',
    tags: ['format', 'audio'],
    platforms: [],
    pairings: ['opinion_commentary-audio'],
    platform_support: 'unverified'
  },
  {
    id: 'broadcast_message',
    title: 'Broadcast message',
    description: 'Prepare a message for a channel audience.',
    family: 'Messaging',
    dimension: 'native',
    category: 'community',
    tags: ['format', 'community'],
    platforms: ['instagram'],
    pairings: ['community_announcement-broadcast_message'],
    platform_support: 'unverified'
  },
  {
    id: 'community_message',
    title: 'Community message',
    description: 'Prepare a message for a group or community.',
    family: 'Messaging',
    dimension: 'native',
    category: 'community',
    tags: ['format', 'community'],
    platforms: ['facebook'],
    pairings: ['community_announcement-community_message'],
    platform_support: 'unverified'
  },
  {
    id: 'product_catalog',
    title: 'Product catalogue',
    description: 'Organise products into a browsable collection.',
    family: 'Commerce',
    dimension: 'native',
    category: 'business',
    tags: ['format', 'business'],
    platforms: ['facebook', 'instagram'],
    pairings: ['product_service_showcase-product_catalog'],
    platform_support: 'unverified'
  },
  {
    id: 'local_business_update',
    title: 'Local business update',
    description: 'Share local hours, news, an event or an offer.',
    family: 'Commerce',
    dimension: 'native',
    category: 'business',
    tags: ['format', 'business'],
    platforms: ['facebook'],
    pairings: ['event_live-local_business_update'],
    platform_support: 'unverified'
  }
];

export const TAXONOMY_BY_ID: Record<string, TaxonomyItem> = Object.fromEntries(TAXONOMY.map((item) => [item.id, item]));
export const PAIRINGS_BY_ID: Record<string, Pairing> = Object.fromEntries(PAIRINGS.map((pairing) => [pairing.id, pairing]));

export const EDITORIAL_TYPES = TAXONOMY.filter((item) => item.dimension === 'editorial');
export const NATIVE_FORMATS = TAXONOMY.filter((item) => item.dimension === 'native');

export function taxonomyItem(id: string | null | undefined): TaxonomyItem | undefined {
  return id ? TAXONOMY_BY_ID[id] : undefined;
}

export function categoryInfo(dimension: Dimension, id: string): LibraryCategory | undefined {
  return CATEGORIES[dimension].find((category) => category.id === id);
}

export function platformInfo(id: string): LibraryPlatform | undefined {
  return PLATFORMS.find((platform) => platform.id === id);
}
