from typing import Protocol

from ..contracts import CallReceipt, ProviderEvent


class TelephonyProvider(Protocol):
    name: str
    real: bool
    configured: bool

    def create_outbound_call(self, *, number: str, call_id: str, max_seconds: int) -> CallReceipt: ...
    def reconcile(self, *, number: str, call_id: str, call_ref: str | None, requested_at: float) -> CallReceipt: ...
    def end_call(self, call_ref: str) -> bool: ...
    def verify_webhook(self, url: str, parameters: dict, signature: str) -> bool: ...
    def normalize_event(self, parameters: dict) -> ProviderEvent: ...
    def start_verification(self, number: str) -> str: ...
    def check_verification(self, number: str, code: str) -> bool: ...


class TelephonyMediaTransport(Protocol):
    """Provider framing stays at the adapter boundary. None means the caller disconnected."""
    async def receive_audio(self) -> str | None: ...
    async def send_audio(self, audio: str) -> None: ...
    async def interrupt(self) -> None: ...
