import {useEffect,useRef,useState,type ReactNode} from 'react';
import {download} from './api';
import {deliveryApi,handoffLabel,heartbeatLabel,isHttpsPermalink,isManualManifest,packageEligible,localAssetPath,type DeliveryState,type HandoffJob,type HandoffReview,type PrepareHandoff} from './deliveryApi';
import type {Channel,Draft} from './types';

const failure=(cause:unknown)=>cause instanceof Error?cause.message:'The local handoff request could not be completed.';
const localTime=(value:string)=>value.replace('T',' ');
function Field({label,hint,children}:{label:string;hint?:string;children:ReactNode}){return <label className="field">{label}{children}{hint&&<span className="hint">{hint}</span>}</label>;}
function DeliveryDialog({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){
  const ref=useRef<HTMLDialogElement>(null),heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{const dialog=ref.current!,previous=document.activeElement as HTMLElement|null;dialog.showModal();return()=>{dialog.close();previous?.focus();};},[]);
  useEffect(()=>{heading.current?.focus();},[title]);
  return <dialog className="delivery-dialog" ref={ref} aria-labelledby="delivery-dialog-title" onCancel={event=>{event.preventDefault();onClose();}}><div className="dialog-head"><h2 ref={heading} tabIndex={-1} id="delivery-dialog-title">{title}</h2><button type="button" className="icon-button" aria-label="Close handoff dialog" onClick={onClose}>×</button></div>{children}</dialog>;
}

type ReviewProps={review:HandoffReview;draft:Draft|undefined;channels:Channel[];existingJob?:HandoffJob;onClose:()=>void;onQueued:(job:HandoffJob)=>void};
function FrozenReviewDialog({review,draft,channels,existingJob,onClose,onQueued}:ReviewProps){
  const [confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const manifest=review.manifest,stale=!draft||draft.archived||draft.revision!==review.draftRevision,manual=isManualManifest(manifest);
  const channel=channels.find(item=>item.id===manifest.channel);
  async function queue(){if(!confirmed||stale||!manual||existingJob)return;setBusy(true);setError('');try{const {job}=await deliveryApi.approve(review);onQueued(job);}catch(cause){setError(failure(cause));}finally{setBusy(false);}}
  return <DeliveryDialog title="Review the local handoff" onClose={onClose}>
    <div className="callout"><strong>This queues a local handoff task, not a post.</strong> The account and destination below are unverified labels. No platform login, upload, publication or remote schedule is authorized.</div>
    <div className="handoff-review-title"><p className="eyebrow">FROZEN DRAFT · REVISION {review.draftRevision}</p><h3>{manifest.title||'Untitled draft'}</h3></div>
    <dl className="delivery-facts"><div><dt>Channel</dt><dd>{channel?.name||manifest.channel}</dd></div><div><dt>Native format</dt><dd>{manifest.nativeFormat}</dd></div><div><dt>Language</dt><dd>{manifest.language}</dd></div><div><dt>Account label</dt><dd>{manifest.accountLabel}<small>Unverified</small></dd></div><div><dt>Destination label</dt><dd>{manifest.destinationLabel}<small>Unverified</small></dd></div><div><dt>Intended audience</dt><dd>{manifest.audience}</dd></div><div><dt>Method</dt><dd>Assisted handoff · human action required</dd></div><div><dt>Derivatives</dt><dd>None · separate drafts/reviews are required</dd></div></dl>
    <Field label="Exact frozen copy" hint="Check every claim, name and platform-specific detail. This text has not been independently fact-verified."><textarea readOnly value={manifest.copy} rows={8}/></Field>
    <section className="handoff-assets"><h3>Ordered assets · {manifest.assets.length}</h3>{manifest.assets.length?<ol>{manifest.assets.map((asset,index)=><li key={asset.id}><img src={localAssetPath(asset.id)} alt={asset.alt||`Attachment ${index+1}: ${asset.name}`} loading="lazy"/><div><strong>{index+1}. {asset.name}</strong><p>Alt text: {asset.alt||'Not supplied'}</p><small>{asset.mime} · {asset.size.toLocaleString()} bytes</small><a className="button asset-download" href={localAssetPath(asset.id)} download={asset.name}>Download original image</a><p className="hint">Local source asset only; this download is not a valid handoff receipt or publication.</p><details><summary>Immutable asset hash</summary><code>{asset.sha256}</code></details></div></li>)}</ol>:<p className="hint">No media attached to this frozen review.</p>}</section>
    <section className="handoff-template"><h3>Frozen template</h3>{manifest.template?<><p>{manifest.template.name} · v{manifest.template.version} · {manifest.template.origin}</p><details className="agent-meta"><summary>Template text and hash</summary><p>{manifest.template.hash}</p><pre>{manifest.template.body}</pre></details></>:<p className="hint">No content template selected.</p>}<p className="hint">Visual reference: {manifest.visualRef.theme||'None'}{manifest.visualRef.layouts.length?` · ${manifest.visualRef.layouts.join(', ')}`:''}. Reference selection does not render or upload media.</p></section>
    <section className="handoff-timing"><p className="eyebrow">EXACT HANDOFF WINDOW</p><dl className="delivery-facts"><div><dt>Local due time</dt><dd>{localTime(manifest.scheduledLocal)}<small>{manifest.timezone}</small></dd></div><div><dt>UTC due time</dt><dd>{manifest.scheduledUtc}</dd></div><div><dt>UTC deadline</dt><dd>{manifest.deadlineUtc}</dd></div><div><dt>Handoff window</dt><dd>{manifest.windowMinutes} minutes</dd></div><div><dt>Repeated-hour choice</dt><dd>{manifest.fold===null?'Not applicable / unique local time':manifest.fold===0?'First occurrence (fold 0)':'Second occurrence (fold 1)'}</dd></div></dl><p className="hint">The local worker must be resumed and this computer awake. An overdue task becomes Needs review; it will not silently catch up or publish.</p></section>
    <details className="agent-meta"><summary>Source and supplied angle</summary><h4>Source</h4><pre>{manifest.source}</pre><h4>Angle</h4><pre>{manifest.angle}</pre></details>
    <details className="agent-meta"><summary>Exact manifest and hash</summary><p>{review.manifestHash}</p><pre>{JSON.stringify(manifest,null,2)}</pre></details>
    {!manual&&<p className="agent-error" role="alert">This review is not a recognized manual-only handoff. The UI will not approve an unknown route or authority scope.</p>}
    {stale&&<p className="agent-warning">The draft was changed, archived or is no longer loaded. Prepare a fresh review; this snapshot cannot be approved.</p>}
    {existingJob&&<p className="callout">A local task already exists for this review: {handoffLabel(existingJob.state)}. No duplicate task will be created.</p>}
    {error&&<p className="agent-error" role="alert">{error}</p>}
    {!existingJob&&<label className="check-label agent-consent"><input type="checkbox" checked={confirmed} disabled={busy||stale||!manual} onChange={event=>setConfirmed(event.target.checked)}/><span>I reviewed this exact copy, destination labels, media and time. Queue a local handoff only; do not publish or schedule anything on a platform.</span></label>}
    <div className="dialog-actions"><button type="button" className="button" onClick={onClose}>Keep review for later</button>{!existingJob&&<button type="button" className="button primary" disabled={busy||!confirmed||stale||!manual} onClick={()=>void queue()}>{busy?'Recording local task…':'Queue local handoff'}</button>}</div>
  </DeliveryDialog>;
}

export function DeliveryComposer({draft,channels,onClose,onQueued}:{draft:Draft;channels:Channel[];onClose:()=>void;onQueued:(job:HandoffJob)=>void}){
  const initial:PrepareHandoff={draftId:draft.id,expectedRevision:draft.revision,channel:draft.channels.length===1?draft.channels[0]:'',accountLabel:'',destinationLabel:'',audience:'',scheduledLocal:draft.plannedAt||'',timezone:draft.timezone,fold:null,windowMinutes:60,deliveryMethod:'assisted_handoff',derivatives:'none'};
  const initialRef=useRef(JSON.stringify(initial));
  const [form,setForm]=useState(initial),[review,setReview]=useState<HandoffReview|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const changed=JSON.stringify(form)!==initialRef.current;
  useEffect(()=>{const handler=(event:BeforeUnloadEvent)=>{if(changed&&!review){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',handler);return()=>window.removeEventListener('beforeunload',handler);},[changed,review]);
  function close(){if(!review&&changed&&!window.confirm('Discard the unsaved handoff setup? Your saved draft is unchanged.'))return;onClose();}
  async function prepare(){setError('');if(!form.channel||!draft.copies[form.channel]?.trim()){setError('Choose a channel with saved native copy. Close this setup and edit the draft if copy is missing.');return;}setBusy(true);try{const value=await deliveryApi.prepare(form);setReview(value.review);}catch(cause){setError(failure(cause));}finally{setBusy(false);}}
  if(review)return <FrozenReviewDialog review={review} draft={draft} channels={channels} onClose={close} onQueued={onQueued}/>;
  return <DeliveryDialog title="Prepare a local handoff" onClose={close}><form onSubmit={event=>{event.preventDefault();void prepare();}}><fieldset disabled={busy}>
    <div className="callout">Prepare one frozen destination from <strong>{draft.title||'Untitled draft'}</strong>, v{draft.revision}. This step does not approve a task or connect any account.</div>
    {draft.archived&&<p className="agent-warning">Restore this archived draft first.</p>}
    <Field label="Channel" hint="Exactly one channel per review. Only channels already selected in this saved draft are available."><select required value={form.channel} onChange={event=>setForm({...form,channel:event.target.value})}><option value="">Choose a channel</option>{draft.channels.map(id=><option key={id} value={id}>{channels.find(item=>item.id===id)?.name||id}</option>)}</select></Field>
    <Field label="Saved native format"><input readOnly value={draft.formats[form.channel]||''} placeholder="Select a channel first"/></Field>
    <div className="field-row"><Field label="Account label · unverified" hint="A personal label only; not an authenticated account."><input required maxLength={200} value={form.accountLabel} onChange={event=>setForm({...form,accountLabel:event.target.value})} placeholder="Which account will you use manually?"/></Field><Field label="Destination label · unverified" hint="The profile, page, board or other exact destination."><input required maxLength={200} value={form.destinationLabel} onChange={event=>setForm({...form,destinationLabel:event.target.value})} placeholder="Name the intended destination"/></Field></div>
    <Field label="Intended audience"><input required maxLength={200} value={form.audience} onChange={event=>setForm({...form,audience:event.target.value})} placeholder="Public, unlisted, a named community…"/></Field>
    <div className="field-row"><Field label="Handoff date & local time"><input required type="datetime-local" value={form.scheduledLocal} onInput={event=>setForm({...form,scheduledLocal:event.currentTarget.value})} onChange={event=>setForm({...form,scheduledLocal:event.target.value})}/></Field><Field label="IANA timezone" hint="For example Asia/Hong_Kong or America/New_York."><input required value={form.timezone} onChange={event=>setForm({...form,timezone:event.target.value})}/></Field></div>
    <div className="field-row"><Field label="Repeated-hour occurrence" hint="If daylight saving repeats this local time, explicitly choose the first or second occurrence. Nonexistent times are rejected."><select value={form.fold===null?'':String(form.fold)} onChange={event=>setForm({...form,fold:event.target.value===''?null:Number(event.target.value) as 0|1})}><option value="">Not chosen / unique time</option><option value="0">First occurrence · fold 0</option><option value="1">Second occurrence · fold 1</option></select></Field><Field label="Handoff window · minutes" hint="If the worker misses this deadline, renewed review is required."><input required type="number" min={1} max={1440} value={form.windowMinutes} onChange={event=>setForm({...form,windowMinutes:Number(event.target.value)})}/></Field></div>
    <div className="delivery-scope"><p><strong>Delivery method:</strong> Assisted handoff only.</p><p><strong>Derivatives:</strong> None. Stories, Reels, Shorts and other derivatives require their own draft and review.</p><p>No automatic publication, platform scheduling or account authentication is available in this flow.</p></div>
    {error&&<p className="agent-error" role="alert">{error}</p>}
    <div className="dialog-actions"><button type="button" className="button" onClick={close}>Cancel setup</button><button type="submit" className="button primary" disabled={draft.archived||busy}>{busy?'Freezing local review…':'Prepare exact review'}</button></div>
  </fieldset></form></DeliveryDialog>;
}

export default function DeliveryView({drafts,channels,onPrepare,onOpenDraft}:{drafts:Draft[];channels:Channel[];onPrepare:(draft:Draft)=>void;onOpenDraft:(draft:Draft)=>void}){
  const [data,setData]=useState<DeliveryState|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[selectedDraft,setSelectedDraft]=useState(''),[review,setReview]=useState<HandoffReview|null>(null);
  const [reportJob,setReportJob]=useState<HandoffJob|null>(null),[permalink,setPermalink]=useState(''),[reportError,setReportError]=useState(''),[cancelJob,setCancelJob]=useState<HandoffJob|null>(null);
  const [loadedAt,setLoadedAt]=useState<string|null>(null),[autoPaused,setAutoPaused]=useState(false);
  const alive=useRef(true),readSequence=useRef(0);
  const states=['queued_local','human_action_needed','needs_review','user_reported','cancelled'] as const;
  async function refresh(explicit=false){const sequence=++readSequence.current;if(explicit)setLoading(true);try{const value=await deliveryApi.state();if(!alive.current||sequence!==readSequence.current)return;setData(value);setLoadedAt(new Date().toISOString());setError('');}catch(cause){if(alive.current&&sequence===readSequence.current)setError(failure(cause));}finally{if(alive.current&&sequence===readSequence.current)setLoading(false);}}
  useEffect(()=>{alive.current=true;void refresh(true);let ticks=0;const timer=window.setInterval(()=>{if(document.visibilityState!=='visible')return;if(++ticks>45){window.clearInterval(timer);setAutoPaused(true);return;}void refresh();},4000);return()=>{alive.current=false;readSequence.current++;window.clearInterval(timer);};},[]);
  function rememberJob(job:HandoffJob){readSequence.current++;setData(current=>current?{...current,jobs:[job,...current.jobs.filter(item=>item.id!==job.id)]}:current);}
  async function control(){if(!data)return;setBusy(true);setError('');try{const {worker}=await deliveryApi.control(!data.worker.paused);if(!alive.current)return;readSequence.current++;setData(current=>current?{...current,worker}:current);setNotice(worker.paused?'Local handoff processing paused. No platform content was changed.':'Local handoff processing resumed. Only local tasks may become due; nothing will publish.');}catch(cause){if(alive.current)setError(failure(cause));}finally{if(alive.current)setBusy(false);}}
  async function packageDownload(job:HandoffJob){setBusy(true);setError('');try{await download(deliveryApi.packagePath(job.id),'studio-local-handoff.md');if(alive.current)setNotice('Immutable local handoff package downloaded. No content was uploaded or published.');}catch(cause){if(alive.current)setError(failure(cause));}finally{if(alive.current)setBusy(false);}}
  async function cancel(){if(!cancelJob)return;setBusy(true);setError('');try{const {job}=await deliveryApi.cancel(cancelJob.id);rememberJob(job);setCancelJob(null);setNotice('Local task cancelled. This cannot recall anything already posted manually.');}catch(cause){setError(failure(cause));}finally{setBusy(false);}}
  async function report(){if(!reportJob)return;setReportError('');if(!isHttpsPermalink(permalink.trim())){setReportError('Use a valid HTTPS permalink with no embedded login credentials. The URL will not be opened or fetched.');return;}setBusy(true);try{const {job}=await deliveryApi.report(reportJob.id,permalink.trim());rememberJob(job);setReportJob(null);setNotice('Permalink recorded as user-reported and unverified. Studio did not check or publish it.');}catch(cause){setReportError(failure(cause));}finally{setBusy(false);}}
  const eligibleDrafts=drafts.filter(draft=>!draft.archived),jobs=(data?.jobs||[]).filter(job=>(filter==='all'||job.state===filter)&&`${job.title} ${job.channel}`.toLowerCase().includes(search.toLowerCase()));
  const unqueued=data?.reviews.filter(item=>!data.jobs.some(job=>job.reviewId===item.id))||[];
  return <section className="delivery-workspace" aria-label="Local delivery queue">
    <div className="callout"><strong>A handoff desk, not an automatic publisher.</strong> Prepare an exact review, queue a local task, then post manually when it becomes due. Reported links remain unverified.</div>
    <div className="delivery-toolbar"><button className="button" disabled={loading} onClick={()=>void refresh(true)}>{loading?'Refreshing…':'Refresh queue'}</button><p className="hint" role="status">{loadedAt?`Read from local database at ${new Date(loadedAt).toLocaleTimeString()}`:'Loading local delivery records…'}{autoPaused?' · Auto-refresh paused':''}</p></div>
    {error&&<p className="agent-error" role="alert">{error}</p>}{notice&&<p className="delivery-notice" role="status">{notice}</p>}
    {data&&<section className="worker-card" aria-label="Local handoff worker"><div><p className="eyebrow">LOCAL WORKER</p><h2>{data.worker.paused?'Handoff processing is paused.':'Handoff processing is resumed.'}</h2><p>{heartbeatLabel(data.worker.heartbeatAt)}</p><p className="hint">Heartbeat is the last observed evidence, not a promise of current liveness. Generation {data.worker.generation}. This computer must remain awake.</p></div><button className="button" disabled={busy} onClick={()=>void control()}>{data.worker.paused?'Resume local handoff worker':'Pause handoff worker'}</button></section>}
    <section className="handoff-create"><div><p className="eyebrow">FROM A SAVED DRAFT</p><h2>Give the next post a handoff.</h2></div><div className="handoff-create-controls"><Field label="Choose a saved draft"><select value={selectedDraft} onChange={event=>setSelectedDraft(event.target.value)}><option value="">Select a draft</option>{eligibleDrafts.map(draft=><option key={draft.id} value={draft.id}>{draft.title||'Untitled draft'} · v{draft.revision}</option>)}</select></Field><button className="button primary" disabled={!selectedDraft} onClick={()=>{const draft=drafts.find(item=>item.id===selectedDraft);if(draft)onPrepare(draft);}}>Prepare handoff</button></div>{!eligibleDrafts.length&&<p className="hint">Create and save a draft with native copy before preparing a handoff.</p>}</section>
    {unqueued.length>0&&<details className="pending-reviews"><summary>{unqueued.length} frozen review{unqueued.length===1?'':'s'} awaiting your decision</summary>{unqueued.map(item=><div className="pending-review" key={item.id}><div><strong>{item.manifest.title||'Untitled draft'}</strong><p>{channels.find(channel=>channel.id===item.manifest.channel)?.name||item.manifest.channel} · draft v{item.draftRevision} · unapproved</p></div><button className="button" onClick={()=>setReview(item)}>Review local handoff</button></div>)}</details>}
    <div className="toolbar delivery-filters"><Field label="Find a handoff"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Title or channel"/></Field><Field label="Task state"><select value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">All local tasks</option>{states.map(state=><option key={state} value={state}>{handoffLabel(state)}</option>)}</select></Field><p className="muted" role="status">{data?`${jobs.length} task${jobs.length===1?'':'s'}`:'Task count unknown'}</p></div>
    {!data&&<div className="quiet-box" role="status">{loading?'Reading the local delivery ledger…':'Delivery records are unavailable. No queue or worker state is inferred; use Refresh queue to retry.'}</div>}
    {data&&!jobs.length&&<div className="empty"><span className="empty-mark" aria-hidden="true">↗</span><h2>{filter==='all'&&!search?'Your handoff queue is clear.':'No matching handoffs.'}</h2><p>{filter==='all'&&!search?'Draft calendar plans stay separate. A task appears here only after you review and explicitly queue a local handoff.':'Try another state or search term.'}</p></div>}
    <div className="delivery-jobs">{jobs.map(job=>{const frozen=data?.reviews.find(item=>item.id===job.reviewId),sourceDraft=drafts.find(item=>item.id===job.draftId);return <article className={`delivery-job state-${job.state}`} key={job.id}><div className="delivery-job-head"><div><p className="eyebrow">{channels.find(channel=>channel.id===job.channel)?.name||job.channel}</p><h2>{job.title||'Untitled draft'}</h2></div><span className="handoff-state">{handoffLabel(job.state)}</span></div><div className="delivery-job-time"><p><strong>{localTime(job.scheduledLocal)}</strong> · {job.timezone}</p><p>UTC due {job.scheduledUtc} · deadline {job.deadlineUtc}</p></div>{job.reason&&<p className="handoff-reason">{job.reason}</p>}{job.state==='queued_local'&&<p className="hint">A local task only. It becomes actionable within its window when the worker runs; no platform schedule exists.</p>}{job.state==='needs_review'&&<p className="hint">No automatic catch-up. Inspect the reason, edit if needed and prepare a fresh review.</p>}{job.state==='human_action_needed'&&<p className="hint">Download the package and use your chosen platform manually. Studio does not post it for you.</p>}{job.state==='cancelled'&&<p className="hint">The local task is cancelled. This cannot recall content you already posted yourself.</p>}{job.permalink&&<div className="reported-link"><strong>User-reported permalink · unverified</strong><code>{job.permalink}</code><p>Stored as text only. Not opened, fetched or independently verified.</p></div>}<div className="delivery-job-actions">{frozen&&<button className="button" onClick={()=>setReview(frozen)}>View frozen review</button>}{packageEligible(job)&&<><button className="button primary" disabled={busy} onClick={()=>void packageDownload(job)}>Download handoff package</button><button className="button" disabled={busy} onClick={()=>{setReportJob(job);setPermalink(job.permalink||'');setReportError('');}}>Record manual-post link</button></>}{sourceDraft&&<button className="button" onClick={()=>onOpenDraft(sourceDraft)}>Open draft</button>}{job.state!=='cancelled'&&<button className="button" disabled={busy} onClick={()=>{setCancelJob(job);setError('');}}>Cancel local task</button>}</div><details className="agent-meta"><summary>Local task record</summary><p>Task: {job.id}</p><p>Review: {job.reviewId}</p><p>Verification: {job.verificationState}</p><p>Last updated: {job.updatedAt}</p></details></article>;})}</div>
    {review&&<FrozenReviewDialog review={review} draft={drafts.find(item=>item.id===review.draftId)} channels={channels} existingJob={data?.jobs.find(item=>item.reviewId===review.id)} onClose={()=>setReview(null)} onQueued={job=>{rememberJob(job);setReview(null);setNotice('Queued locally. This receipt authorizes a handoff task only, not publication.');}}/>}
    {cancelJob&&<DeliveryDialog title="Cancel this local task?" onClose={()=>setCancelJob(null)}><h3>{cancelJob.title}</h3><p className="callout">{packageEligible(cancelJob)?'A handoff may already have been used. Cancelling here cannot recall, delete or undo content you posted manually.':'This cancels the local task and retains its review and audit record. It does not change any platform content.'}</p><p className="hint">Exact task: {cancelJob.id}</p>{error&&<p className="agent-error" role="alert">{error}</p>}<div className="dialog-actions"><button className="button" onClick={()=>setCancelJob(null)}>Keep task</button><button className="button primary" disabled={busy} onClick={()=>void cancel()}>{busy?'Cancelling…':'Cancel local task'}</button></div></DeliveryDialog>}
    {reportJob&&<DeliveryDialog title="Record your manual-post link" onClose={()=>{if(permalink!==(reportJob.permalink||'')&&!window.confirm('Discard this unsaved link?'))return;setReportJob(null);}}><form onSubmit={event=>{event.preventDefault();void report();}}><div className="callout">Your report is stored as <strong>user-reported · unverified</strong>. Studio will not visit the URL, authenticate an account or claim that publication was independently confirmed.</div><h3>{reportJob.title}</h3><Field label="HTTPS permalink" hint="Paste the exact post link. Do not include passwords, tokens or login credentials."><input required type="url" value={permalink} onChange={event=>setPermalink(event.target.value)} placeholder="https://…"/></Field>{reportError&&<p className="agent-error" role="alert">{reportError}</p>}<div className="dialog-actions"><button type="button" className="button" onClick={()=>setReportJob(null)}>Cancel report</button><button type="submit" className="button primary" disabled={busy}>{busy?'Recording report…':'Save unverified report'}</button></div></form></DeliveryDialog>}
  </section>;
}
