import {useEffect,useState} from 'react';
import {connectionsApi,type InstagramConnection as State,type InstagramPostResult} from './connectionsApi';
async function sha256(value:string){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function receipt(imageUrl:string,caption:string,altText:string){const manifest={account:'@jamesaucreates',destination:'main_profile_feed',nativeFormat:'instagram.feed_image',mediaType:'IMAGE',imageUrl,caption,altText,visibility:'public',scheduledAt:null,derivatives:[]};const approvalReceiptHash=await sha256(JSON.stringify(manifest,Object.keys(manifest).sort()));return {approvalReceiptHash,idempotencyKey:await sha256('instagram.publish\0'+approvalReceiptHash)};}
export default function InstagramConnection(){
 const [connection,setConnection]=useState<State|null>(null),[consent,setConsent]=useState(false),[publishConsent,setPublishConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[imageUrl,setImageUrl]=useState(''),[caption,setCaption]=useState(''),[altText,setAltText]=useState(''),[result,setResult]=useState<InstagramPostResult|null>(null);
 async function refresh(){try{setConnection((await connectionsApi.status()).instagram);setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Connection status unavailable.');}}
 useEffect(()=>{void refresh();},[]);
 async function verify(){setBusy(true);setError('');try{setConnection(await connectionsApi.verifyInstagram());}catch(cause){setError(cause instanceof Error?cause.message:'Connection verification unavailable.');}finally{setBusy(false);}}
 async function testRoute(){setBusy(true);setError('');try{setConnection(await connectionsApi.testInstagramRoute());}catch(cause){setError(cause instanceof Error?cause.message:'Instagram publishing route test failed.');}finally{setBusy(false);}}
 async function connect(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{window.location.assign(await connectionsApi.prepareInstagram('jamesaucreates'));}catch(cause){setError(cause instanceof Error?cause.message:'Instagram sign-in could not start.');setBusy(false);}}
 async function publish(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setResult(null);try{const hashes=await receipt(imageUrl,caption,altText);setResult(await connectionsApi.publishInstagramImage({imageUrl,caption,altText,...hashes,publicationConsent:true}));setPublishConsent(false);}catch(cause){setError(cause instanceof Error?cause.message:'Instagram could not return verified publication evidence.');}finally{setBusy(false);}}
 return <section className="setup-panel" aria-label="Instagram publishing connection"><h3>Instagram publishing</h3>
  <p>Studio connects <strong>@jamesaucreates</strong> with <code>instagram_business_basic</code> and <code>instagram_business_content_publish</code>. Messages, comments, insights and ads remain unavailable.</p>
  {error&&<p role="alert" className="error-banner">{error}</p>}
  {connection?.verifiedAt?<div className="callout"><strong>{connection.publishReady?'Publish-ready':connection.state==='connected_identity'?'Identity connected':'Verification required'}: @{connection.username}</strong><p>{connection.accountType} · professional user ID {connection.userId}</p><p>{connection.publishReady?'Identity and current publishing quota passed the official API route test.':'Run the read-only route test to verify identity and current publishing quota.'}</p><small>Identity verified {connection.verifiedAt}{connection.routeTestedAt?' · Route tested '+connection.routeTestedAt:''} · Access expires {connection.expiresAt}</small></div>:<>
   <p className="muted">{connection?.available?'Connection state: '+connection.state.replaceAll('_',' '):'Meta credentials and a working HTTPS callback are required.'}</p>
   {connection?.state==='configuration_required'&&<p>Apple Keychain: <code>James Au Studio Instagram OAuth</code> / <code>client-id</code> and <code>client-secret</code>. Meta callback must match the private tunnel file.</p>}
   <form onSubmit={connect}><fieldset className="setup-fields" disabled={busy||!connection?.available}><label className="check-field"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Connect @jamesaucreates for professional identity verification and approval-gated image publishing. Keep OAuth tokens encrypted on this Mac.</label><button type="submit" className="button primary" disabled={!consent}>{busy?'Preparing…':'Continue to Instagram'}</button></fieldset></form></>}
  {connection?.state==='connected_identity'&&!connection.publishReady&&<button type="button" className="button primary" onClick={()=>void testRoute()} disabled={busy}>{busy?'Testing…':'Run publishing route test'}</button>}
  {connection?.publishReady&&<form onSubmit={publish}><fieldset className="setup-fields" disabled={busy}>
   <label className="field">Public HTTPS image URL<input required type="url" pattern="https://.*" value={imageUrl} onChange={e=>{setImageUrl(e.target.value);setPublishConsent(false);setResult(null);}}/></label>
   <label className="field">Exact caption<textarea value={caption} maxLength={2200} rows={5} onChange={e=>{setCaption(e.target.value);setPublishConsent(false);setResult(null);}}/></label>
   <label className="field">Image alt text<input required maxLength={1000} value={altText} onChange={e=>{setAltText(e.target.value);setPublishConsent(false);setResult(null);}}/></label>
   <small>@jamesaucreates · Main feed · Public · Immediate · One image · No derivatives</small>
   <label className="check-field"><input type="checkbox" checked={publishConsent} onChange={e=>setPublishConsent(e.target.checked)}/> Publish this exact image and caption now to the public @jamesaucreates Instagram profile.</label>
   <button type="submit" className="button primary" disabled={!publishConsent||!imageUrl.startsWith('https://')||!altText.trim()}>{busy?'Publishing and verifying…':'Publish exact Instagram post'}</button>
  </fieldset></form>}
  {result&&<div className="callout"><strong>Verified published Instagram post</strong><p><a href={result.url} target="_blank" rel="noreferrer">Open on Instagram</a></p><small>Media ID {result.mediaId} · Verified {result.verifiedAt}</small></div>}
  <button type="button" className="button" onClick={()=>void (connection?.verifiedAt?verify():refresh())} disabled={busy}>{busy?'Checking…':'Check connection'}</button>
 </section>;
}
