import {useEffect,useState} from 'react';
import {connectionsApi,type LinkedInConnection as State,type LinkedInScheduledJob} from './connectionsApi';

export default function LinkedInConnection(){
 const [connection,setConnection]=useState<State|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[published,setPublished]=useState<{url:string}|null>(null);
 const [scheduleText,setScheduleText]=useState(''),[scheduleAt,setScheduleAt]=useState(''),[preview,setPreview]=useState<{manifest:{text:string;scheduledAt:string};approvalReceiptHash:string}|null>(null),[scheduleApproval,setScheduleApproval]=useState(false),[scheduled,setScheduled]=useState<string|null>(null),[jobs,setJobs]=useState<LinkedInScheduledJob[]>([]);
 const email='jamesaucreates@gmail.com';
 async function refresh(){try{const next=await connectionsApi.linkedinStatus();setConnection(next);if(next.state==='connected_identity')setJobs((await connectionsApi.linkedinScheduled()).jobs);else setJobs([]);setError('');}catch(cause){setError(cause instanceof Error?cause.message:'LinkedIn status unavailable.');}}
 useEffect(()=>{void refresh();},[]);
 async function connect(event:React.SubmitEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{window.location.assign(await connectionsApi.prepareLinkedIn(email));}catch(cause){setError(cause instanceof Error?cause.message:'LinkedIn sign-in could not start.');setBusy(false);}}
 async function verify(){setBusy(true);setError('');try{setConnection(await connectionsApi.verifyLinkedIn());}catch(cause){setError(cause instanceof Error?cause.message:'LinkedIn verification unavailable.');}finally{setBusy(false);}}
 async function publishApprovedTest(){setBusy(true);setError('');try{setPublished(await connectionsApi.publishLinkedInTest());}catch(cause){setError(cause instanceof Error?cause.message:'The approved LinkedIn route test is unresolved.');}finally{setBusy(false);}}
 async function previewSchedule(){setBusy(true);setError('');try{setPreview(await connectionsApi.previewLinkedInSchedule(scheduleText,scheduleAt?new Date(scheduleAt).toISOString():''));setScheduleApproval(false);}catch(cause){setError(cause instanceof Error?cause.message:'Use post text and a future time at least one minute from now.');}finally{setBusy(false);}}
 async function schedule(){if(!preview)return;setBusy(true);setError('');try{const result=await connectionsApi.scheduleLinkedInText({text:preview.manifest.text,scheduledAt:preview.manifest.scheduledAt,approvalReceiptHash:preview.approvalReceiptHash,idempotencyKey:crypto.randomUUID(),publicationConsent:true});setScheduled(result.scheduledAt);setPreview(null);setScheduleApproval(false);setScheduleText('');setScheduleAt('');await refresh();}catch(cause){setError(cause instanceof Error?cause.message:'The scheduled LinkedIn delivery was not accepted.');}finally{setBusy(false);}}
 return <section className="setup-panel" aria-label="LinkedIn account connection"><h3>Connect your LinkedIn identity</h3>
  <p>Studio requests verified profile and email identity plus member post access. Tokens stay in the private local broker. Every post and scheduled delivery requires its own exact approval.</p>
  {error&&<p role="alert" className="error-banner">{error}</p>}
  {connection?.state==='connected_identity'?<div className="callout"><strong>LinkedIn identity connected: {connection.name}</strong><p>{connection.email} · {connection.profileUrl}</p><p>Approved route test: “Testing the LinkedIn connection for James Au Studio. This post was reviewed and sent through my local approval workflow.”</p>{published?<p><a href={published.url} target="_blank" rel="noreferrer">Open verified LinkedIn post</a></p>:<button type="button" className="button primary" disabled={busy} onClick={()=>void publishApprovedTest()}>{busy?'Publishing approved test…':'Publish approved route test'}</button>}<small>Verified {connection.verifiedAt} · token expires {connection.expiresAt}</small>
   {connection.schedulingAvailable&&<div className="setup-fields"><h4>Schedule an approved LinkedIn post</h4><p>Studio keeps this encrypted local queue while it is running. It submits once at the due time; every delivery remains unresolved until a separate LinkedIn read confirms it.</p>{scheduled?<p className="callout">Scheduled for {new Date(scheduled).toLocaleString()}. Studio must remain running.</p>:<><label className="field">Exact post text<textarea value={scheduleText} maxLength={3000} onChange={event=>{setScheduleText(event.target.value);setPreview(null);setScheduleApproval(false);}}/></label><label className="field">Local scheduled time<input type="datetime-local" value={scheduleAt} onChange={event=>{setScheduleAt(event.target.value);setPreview(null);setScheduleApproval(false);}}/></label><button type="button" className="button" disabled={busy||!scheduleText.trim()||!scheduleAt} onClick={()=>void previewSchedule()}>Review scheduled post</button>{preview&&<div className="callout"><p><strong>James Au’s LinkedIn profile · public · {new Date(preview.manifest.scheduledAt).toLocaleString()}</strong></p><p>{preview.manifest.text}</p><p><small>Approval hash: <code>{preview.approvalReceiptHash}</code></small></p><label className="check-field"><input type="checkbox" checked={scheduleApproval} onChange={event=>setScheduleApproval(event.target.checked)}/> I approve this exact text, account, public destination, and scheduled time.</label><button type="button" className="button primary" disabled={busy||!scheduleApproval} onClick={()=>void schedule()}>{busy?'Scheduling…':'Schedule this LinkedIn post'}</button></div>}</>}</div>}
   {jobs.length>0&&<div className="setup-fields"><h4>LinkedIn delivery queue</h4>{jobs.map(job=><div className="callout" key={job.idempotencyKey}><p><strong>{job.state.replaceAll('_',' ')} · {new Date(job.scheduledAt).toLocaleString()}</strong></p><p>{job.text}</p>{job.url&&<p><a href={job.url} target="_blank" rel="noreferrer">Open LinkedIn delivery</a></p>}{job.state==='delivery_unverified'&&<p>LinkedIn accepted the delivery, but Studio still needs an independent post read before it records success.</p>}{job.state==='unresolved'&&<p>Studio could not establish the delivery outcome. Do not retry until it is reconciled.</p>}</div>)}</div>}
  </div>:<>
   <p className="muted">{connection?.available?`Connection state: ${connection.state.replaceAll('_',' ')}`:'LinkedIn OAuth credentials are required in Keychain, then Studio must restart.'}</p>
   <form onSubmit={connect}><fieldset className="setup-fields" disabled={busy||!connection?.available}>
    <label className="field">Expected LinkedIn email<input readOnly value={email}/></label>
    <label className="check-field"><input type="checkbox" checked={consent} onChange={event=>setConsent(event.target.checked)}/> Connect the James Au LinkedIn profile using <code>openid profile email w_member_social</code>. Store tokens privately on this Mac.</label>
    <button type="submit" className="button primary" disabled={!consent||!connection?.available}>{busy?'Opening LinkedIn…':'Continue to LinkedIn'}</button>
   </fieldset></form>
  </>}
  <button type="button" className="button" onClick={()=>void (connection?.state==='connected_identity'?verify():refresh())} disabled={busy}>{busy?'Checking…':'Check connection'}</button>
 </section>;
}
