'use client';
import { useGenUiLocale } from '@/features/agent/generative-ui/core/locale';

const labels: Record<string, [string, string]> = {
  'Rafii suggests writing preferences from what you say and how you edit. You decide.': ['Rafii 從你的指示與修改提出寫作偏好，由你決定是否採用。', 'Rafii 从你的指示与修改提出写作偏好，由你决定是否采用。'],
  'Rafii suggests writing preferences from what you say and how you edit. An owner decides.': ['Rafii 從你的指示與修改提出寫作偏好，由工作區擁有者決定。', 'Rafii 从你的指示与修改提出写作偏好，由工作区所有者决定。'],
  'Counting rules process edits in the workspace. Cloud analysis requires this permission and source consent, including Claude CLI.': ['統計規則在工作區處理修改。雲端分析需要此權限及來源授權，包括 Claude CLI。', '统计规则在工作区处理修改。云端分析需要此权限及来源授权，包括 Claude CLI。'],
  'in your drafts': ['項可用偏好', '项可用偏好'], 'approvals': ['次批准', '次批准'], 'edited on average': ['平均修改', '平均修改'], 'untouched': ['未修改', '未修改'], 'small sample': ['樣本較少', '样本较少'],
  'Learned preferences': ['已學習的偏好', '已学习的偏好'],
  'Learning off': ['已停用學習', '已停用学习'],
  'Learn': ['學習', '学习'], 'Allow': ['允許', '允许'], 'On': ['已開啟', '已开启'], 'Off': ['已關閉', '已关闭'],
  'Owners only': ['僅擁有者', '仅所有者'], 'Unavailable': ['暫時無法取得', '暂时无法获取'],
  'Learn with a cloud model': ['使用雲端模型學習', '使用云端模型学习'],
  'A cloud model may read redacted edits.': ['雲端模型可讀取經遮蔽的修改內容。', '云端模型可读取经遮蔽的修改内容。'],
  'Needs Cloud model access on first.': ['請先允許雲端模型存取。', '请先允许云端模型访问。'],
  'About learning with a cloud model': ['關於雲端模型學習', '关于云端模型学习'],
  'Learn from teammates’ edits': ['從團隊成員的修改學習', '从团队成员的修改学习'],
  'Count every member’s edits as evidence, not only owners’.': ['將所有成員的修改納入參考，不限於擁有者。', '将所有成员的修改纳入参考，不限于所有者。'],
  'Count teammates’ edits as evidence': ['將團隊修改納入參考', '将团队修改纳入参考'],
  'Learn from what I say and how I edit': ['從我的指示與修改學習', '从我的指示与修改学习'],
  'Learn from my edits with a cloud model': ['使用雲端模型從我的修改學習', '使用云端模型从我的修改学习'],
  'Loading learned preferences…': ['正在載入偏好…', '正在加载偏好…'],
  'Couldn’t load learned preferences.': ['無法載入偏好。', '无法加载偏好。'],
  'Nothing learned yet': ['尚未學習任何偏好', '尚未学习任何偏好'],
  'Try: “From now on, no hashtags on Instagram.”': ['試試：「以後 Instagram 貼文不要加主題標籤。」', '试试：“以后 Instagram 帖文不要加话题标签。”'],
  'Pause': ['暫停', '暂停'], 'Resume': ['恢復', '恢复'], 'Retire': ['停用', '停用'], 'Retired': ['已停用', '已停用'],
  'Forget every learned preference and the edit history?': ['清除所有已學習的偏好及修改記錄？', '清除所有已学习的偏好及修改记录？'],
  'Keep holding…': ['請繼續按住…', '请继续按住…'], 'Forgetting…': ['正在清除…', '正在清除…'],
  'Hold to forget learned preferences': ['按住以清除已學習的偏好', '按住以清除已学习的偏好'],
  'Hold to forget everything': ['按住以清除全部', '按住以清除全部'], 'Keep': ['保留', '保留'],
  'Forget what you learned…': ['清除已學習的內容…', '清除已学习的内容…'],
  'Learned preferences forgotten': ['已清除學習偏好', '已清除学习偏好'],
  'Couldn’t save. Try again.': ['無法儲存，請重試。', '无法保存，请重试。'],
  'Couldn’t save the setting.': ['無法儲存設定。', '无法保存设置。'],
  'Couldn’t reset. Try again.': ['無法重設，請重試。', '无法重置，请重试。'],
  'Only an owner can decide.': ['只有擁有者可以決定。', '只有所有者可以决定。'],
  'You said so': ['你的指示', '你的指示'], 'You said so in chat.': ['你在對話中提出的指示。', '你在对话中提出的指示。'],
  'From your edits': ['來自你的修改', '来自你的修改'], 'From how posts did': ['來自貼文表現', '来自帖文表现'], 'Remembered earlier': ['之前已記錄', '之前已记录'],
  'Remembered. Applies to new drafts.': ['已記錄，適用於新草稿。', '已记录，适用于新草稿。'],
  'Remembered with your wording. Applies to new drafts.': ['已按你的措辭記錄，適用於新草稿。', '已按你的措辞记录，适用于新草稿。'],
  'Dismissed.': ['已略過。', '已忽略。'], 'Applied to that draft only.': ['僅套用於該草稿。', '仅应用于该草稿。'], 'Expired.': ['已到期。', '已到期。'],
  'Replaces an earlier preference': ['取代先前偏好', '替代先前偏好'], 'Preference wording': ['偏好措辭', '偏好措辞'],
  'One sentence about how you write.': ['用一句話描述寫作偏好。', '用一句话描述写作偏好。'],
  'Save wording': ['儲存措辭', '保存措辞'], 'Cancel': ['取消', '取消'], 'Remember this': ['記住這項偏好', '记住这项偏好'],
  'Edit wording': ['修改措辭', '修改措辞'], 'Only for this post': ['僅限此貼文', '仅限此帖文'], 'Don’t use': ['不採用', '不采用'],
  'Suggestions': ['建議', '建议'], 'Waiting': ['待處理', '待处理'], 'Recent': ['最近', '最近'],
  'Nothing waiting.': ['沒有待處理項目。', '没有待处理项目。'], 'No decisions yet.': ['尚未作出決定。', '尚未作出决定。'],
  'Remembered': ['已記錄', '已记录'], 'Remembered, reworded': ['已修改並記錄', '已修改并记录'], 'Dismissed': ['已略過', '已忽略'], 'Only for that post': ['僅限該貼文', '仅限该帖文'], 'Expired': ['已到期', '已到期'], 'Replaced': ['已取代', '已替代'], 'Undone': ['已撤銷', '已撤销'],
  'All channels': ['所有頻道', '所有频道'], 'all languages': ['所有語言', '所有语言'],
  'Who reads these files': ['誰可讀取這些檔案', '谁可读取这些文件'],
  'Eligible files depend on voice selection, route permissions and prompt limits. An owner controls cloud access.': ['可用檔案取決於語氣選擇、路徑授權及提示上限。雲端存取由擁有者控制。', '可用文件取决于语气选择、路径授权及提示上限。云端访问由所有者控制。'],
  'Cloud model access': ['雲端模型存取', '云端模型访问'], 'Shared': ['已授權', '已授权'], 'Not shared': ['未授權', '未授权'],
  'Couldn’t load this setting.': ['無法載入此設定。', '无法加载此设置。'], 'Only an owner can change this.': ['只有擁有者可以更改。', '只有所有者可以更改。'],
  'Let the cloud model read your memory files': ['允許雲端模型讀取記憶檔案', '允许云端模型读取记忆文件'],
  'Let the cloud model read your memory files?': ['允許雲端模型讀取記憶檔案？', '允许云端模型读取记忆文件？'],
  'Stop sharing memory files with the cloud model?': ['停止向雲端模型分享記憶檔案？', '停止向云端模型分享记忆文件？'],
  'Allow cloud access': ['允許雲端存取', '允许云端访问'], 'Stop sharing': ['停止分享', '停止分享'],
  'Keep it off': ['保持關閉', '保持关闭'], 'Keep sharing': ['繼續分享', '继续分享'],
  'Saving…': ['正在儲存…', '正在保存…'], 'Reload': ['重新載入', '重新加载'],
  'Loading access settings': ['正在載入存取設定', '正在加载访问设置'], 'Couldn’t load access settings.': ['無法載入存取設定。', '无法加载访问设置。'],
  'The sharing choice could not be saved.': ['無法儲存分享設定。', '无法保存分享设置。'],
};
export function useMemoryText() {
  const locale = useGenUiLocale();
  return (value: string) => labels[value]?.[locale.language === 'zh-Hans' ? 1 : 0] && locale.language !== 'en' ? labels[value][locale.language === 'zh-Hans' ? 1 : 0] : value;
}
