"""Export engineering coverage and unqualified live state; never manufacture evidence.

Lightweight/local metadata operation. Run with PYTHONPATH=src, then run validation
through JCB. Provider-account live receipts are not generated by this exporter.
"""
import csv
import json
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'src'))
from postriff_phase2.official_social import CATALOG, IMPLEMENTED, AUDITED_AT, implementation_revision

OUT = Path(__file__).resolve().parents[1] / 'docs/official-social-20261005'
REVIEWS = {
    'openid_connect': 'Enable Sign In with LinkedIn using OpenID Connect; no Community Management permission implied.',
    'share_on_linkedin': 'Enable Share on LinkedIn. Member write is self-service; app product enablement still unverified.',
    'community_management': 'LinkedIn Community Management Development/Standard approval and approval of each restricted permission.',
    'restricted_member_read': 'BLOCKED — LINKEDIN APPROVAL: specifically approved r_member_social.',
    'threads': 'Meta Threads app/use case; Advanced Access/app review for ordinary profiles and feature-specific permissions.',
    'instagram_login': 'Meta Instagram Login professional-account app; Standard for own role accounts versus reviewed Advanced Access for ordinary users.',
    'instagram_messaging': 'Separate intentional messaging enablement and Meta messaging review.',
    'facebook_login_business': 'Facebook Login for Business; reviewed Page discovery permissions/configuration.',
    'pages': 'Meta reviewed Page permissions; business verification/use case and current Page task as applicable.',
    'messenger': 'Separately enabled Page Messenger product/review; never requested by publishing.',
    'x_api': 'Official pay-per-use access, app/scopes, credits and separately approved endpoint cost ceiling.',
    'x_articles': 'Official Article endpoint access, account eligibility, app scopes and approved cost ceiling.',
    'x_enterprise': 'Quote creation requires verified X Enterprise access; self-serve pay-per-use excludes quote_tweet_id.',
    'x_api_dm': 'Separate intentional DM scopes/access; not implemented for ordinary publishing.',
    'youtube_data': 'Google OAuth verification; YouTube API compliance audit/public-upload eligibility separate; feature-specific channel eligibility.',
    'youtube_analytics': 'YouTube Analytics/Reporting APIs enabled; Google OAuth verification; owned channel.',
    'youtube_analytics_monetary': 'Separate intentional monetary scope, OAuth verification and eligible monetized channel.',
    'youtube_memberships': 'Separate creator-membership scope, OAuth verification and eligible channel.',
    'login_kit': 'TikTok Login Kit/scopes/redirect approval.',
    'content_posting': 'TikTok Content Posting Direct Post audit; unaudited public publishing BLOCKED — TIKTOK AUDIT.',
    'content_posting_upload': 'TikTok Upload product/video.upload review; inbox completion requires creator action.',
    'display_api': 'TikTok Display API product/video.list approval.',
    'pinterest_v5': 'Pinterest business eligibility and Trial versus approved Standard access.',
    'pinterest_ads': 'Separate ads:read enablement, ad-account authorization and access approval.',
    'pinterest_commerce': 'Separate commerce enablement/scopes; Standard access and merchant/catalog eligibility.',
    'none': 'Not applicable: no supported authoring contract.',
}

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    revision=implementation_revision();rows=[]
    for provider, features in CATALOG.items():
        for key, feature in features.items():
            implemented=feature.implemented or key in IMPLEMENTED.get(provider, ())
            rows.append({'provider':provider,'capability':key,'officialSupport':feature.support,
                'method':feature.method,'permissionGroup':feature.permission_group,'scopes':list(feature.scopes),
                'scopeAlternatives':[list(s) for s in feature.scope_alternatives],
                'product':feature.product,'accountPrerequisite':feature.account,
                'reviewRequirement':REVIEWS.get(feature.product,'Feature/product approval must be verified.'),
                'reviewState':'NOT_VERIFIED','actualRequestedScopes':[],'actualGrantedScopes':None,'actualGrantObservation':'NOT_OBSERVED_IN_THIS_TASK',
                'implemented':implemented,'liveE2E':'NOT_RUN','liveEvidence':None,
                'eligibility':'NOT_VERIFIED','scheduling':feature.scheduling,'limitation':feature.limitation,
                'source':feature.source,'auditDate':AUDITED_AT,'implementationRevision':revision,
                'productionVerdict':'UNSUPPORTED BY OFFICIAL API' if feature.support=='unsupported' else 'BLOCKED — OFFICIAL AUDIT UNAVAILABLE' if feature.support=='audit_unavailable' else 'BLOCKED — LINKEDIN APPROVAL' if feature.product=='restricted_member_read' else 'BLOCKED — X ENTERPRISE ACCESS' if feature.product=='x_enterprise' else 'NOT PRODUCTION READY — approvals, actual grant, eligibility and live E2E unverified'})
    (OUT/'capability-matrix.json').write_text(json.dumps({'execution':'engineering catalogue export; no live provider execution','scopeObservation':'No OAuth was executed in this task. actualRequestedScopes is empty for new task requests; null actualGrantedScopes means unobserved, not zero scopes for existing production connections.','rows':rows},indent=2)+'\n')
    with (OUT/'capability-matrix.csv').open('w',newline='') as file:
        writer=csv.DictWriter(file,fieldnames=list(rows[0]),lineterminator='\n');writer.writeheader()
        for row in rows: writer.writerow({k:json.dumps(v) if isinstance(v,(list,dict)) else v for k,v in row.items()})
    print(json.dumps({'rows':len(rows),'providers':len(CATALOG),'ready':0,'implementationRevision':revision}))

if __name__=='__main__': main()
