"""Render docs/design/site-agent/verification-matrix.md from the recorded evidence (never by hand).

Inputs: docs/design/site-agent/evidence/scenarios.json (tests/phase2/postgres_site_agent_scenarios.py with
SITE_AGENT_EVIDENCE set), evidence/browser-*/site-agent-browser.json (web/tests/site-agent-browser.cjs --out) and, when
present, evidence/live-writer.json (scripts/site_agent_live_writer.py: a real writer model on a disposable database).

    python scripts/site_agent_matrix.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs/design/site-agent"
EVIDENCE = DOCS / "evidence"
SECTIONS = {"context": "§2 Page and context awareness", "brand": "§3 Brand Brain", "voice": "§4 Learn My Voice", "drafts": "§5 Drafts and content operations",
            "campaign": "§6 Campaign intelligence", "calendar": "§7 Calendar", "scheduling": "§7 Scheduling", "reviews": "§8 Review and approval",
            "publishing": "§9 Publishing state", "search": "§10 Site-wide search", "cross-surface": "§11 Cross-surface actions", "continuity": "§12 Conversation continuity", "inspectability": "§13 Inspectability",
            "attention": "§14 Proactive intelligence", "hallucination": "§15 Hallucination and missing data", "isolation": "§15 Workspace isolation",
            "safety": "§16 Destructive and external actions", "permissions": "§16 Permissions", "truthful": "§17 Truthful outcomes", "compound": "§18 Compound requests",
            "ambiguity": "§19 Adversarial ambiguity"}


def cell(value, limit=None):
    text = " ".join(str(value or "").split())
    if limit and len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text.replace("|", "\\|")


def main():
    data = json.loads((EVIDENCE / "scenarios.json").read_text())
    rows = data["scenarios"]
    counts = {v: sum(r["verdict"] == v for r in rows) for v in ("PASS", "PARTIAL", "FAIL")}
    out = ["# Rafii site agent — verification matrix", "",
           "Generated by `python scripts/site_agent_matrix.py` from `evidence/scenarios.json`, `evidence/browser-*/site-agent-browser.json` and `evidence/live-writer.json`. Do not edit by hand.", "",
           f"Seed clock: {data['seed']['clock']} (Asia/Hong_Kong). Fixtures (written directly, not through a user action): " + "; ".join(data["seed"]["fixtures"]) + ".", "",
           f"**Scenarios: {len(rows)} — {counts['PASS']} PASS, {counts['PARTIAL']} PARTIAL, {counts['FAIL']} FAIL.** "
           "PARTIAL means the check passed but the capability is incomplete for the reason in the notes; a failed check is always FAIL.", "",
           "Execution: local disposable PostgreSQL, the real hosted services, the deterministic preview writer (X06c: a scripted asynchronous writer standing in for the Claude Code CLI route); no live provider, model or social account was called in this table. The live-writer table below used a real model.", "",
           "| ID | Capability | Test prompt | Expected source/tool | Expected result | Actual result (excerpt) | Application state verified | Pass/Fail | Evidence |",
           "|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        ran = ", ".join(f"{tool} ({status})" for tool, status in r.get("tools") or []) or ("writing pipeline" if (r.get("actual") or "").startswith("{") else "—")
        verdict = r["verdict"] + (f" — {cell(r['notes'])}" if r.get("notes") else "")
        out.append(f"| {r['id']} | {cell(SECTIONS.get(r['area'], r['area']))} | {cell(r['prompt'])} | {cell(r.get('source'))} | {cell(r['expected'])} | "
                   f"{cell(r['actual'], 220)} | {cell(r.get('stateVerified'))} | {verdict} | `scenarios.json#{r['id']}`; intent {r.get('intent') or '—'}; ran: {cell(ran, 120)}; {r.get('turnMs', '?')} ms |")
    out += ["", "## Browser QA", ""]
    engines = sorted(p for p in EVIDENCE.glob("browser-*/site-agent-browser.json"))
    results = {p.parent.name.removeprefix("browser-"): {c["name"]: c["ok"] for c in json.loads(p.read_text())["results"]} for p in engines}
    names = list(dict.fromkeys(name for checks in results.values() for name in checks))
    out.append("| Check | " + " | ".join(results) + " |")
    out.append("|---|" + "---|" * len(results))
    for name in names:
        out.append(f"| {cell(name)} | " + " | ".join("PASS" if checks.get(name) else ("FAIL" if name in checks else "—") for checks in results.values()) + " |")
    out += ["", "Viewports: desktop 1440×900, help 1280×860, tablet 834×1112, phone 390×844 (touch, reduced motion). "
            "Screenshots: `evidence/browser-chromium/*.png` (WebKit ran with `--shots=off`: the local WebKit build aborts inside its screenshot call).", ""]
    live_path = EVIDENCE / "live-writer.json"
    if live_path.exists():
        live = json.loads(live_path.read_text())
        checks = live.get("checks") or []
        out += ["## Live writer", "",
                f"Model `{cell(live.get('model'))}` through {cell(live.get('route'))}, on {cell(live.get('workspace'))}, "
                f"{cell(live.get('startedAt'))} → {cell(live.get('finishedAt'))}. Source: `evidence/live-writer.json`.", "",
                "| Check | Verdict | Run | Stored result | Cost reported by the run |", "|---|---|---|---|---|"]
        for c in checks:
            run = c.get("run") or {}
            usage = run.get("usage") or {}
            cost = (f"CLI ${usage['cliCostUsd']:.4f} (PostRiff ledger ${usage.get('costUsd', 0)})" if usage.get("cliCostUsd") is not None
                    else ("—" if not run else f"${usage.get('costUsd')}"))
            stored = c.get("draftId") or c.get("mode") or (f"writer's phrasing accepted {c['modelAccepted']} (per-attempt outcomes in the evidence)" if c.get("modelAccepted") else None) or ", ".join(f"{k}: {v}" for k, v in (c.get("steps") or {}).items()) or (c.get("composedBy") or {}).get("composedBy") or "—"
            out.append(f"| {cell(c['check'])} | {c['verdict']} | {cell(c.get('runId') or '—')} | {cell(stored, 160)} | {cell(cost)} |")
        out.append("")
    (DOCS / "verification-matrix.md").write_text("\n".join(out))
    print(f"wrote {DOCS / 'verification-matrix.md'}: {len(rows)} scenarios, {len(names)} browser checks × {len(results)} engines")


if __name__ == "__main__":
    main()
