"""Synthetic root-registered link fixtures; no provider/network calls."""
from dataclasses import replace
import unittest

from agent_team.evidence_links import (
    DepotRunLink, EvidenceLinkPolicy, VercelDeploymentLinks,
    depot_run_link, github_commit_link, vercel_deployment_link,
)
from agent_team.events import Event


SHA = "a" * 40


class WorkerEvidenceLinkTests(unittest.TestCase):
    def setUp(self):
        # Supplied fixture URL, not a production URL generated by the helper.
        self.depot = DepotRunLink("fixture-org", "fixture-run", "https://depot.dev/fixture-org/fixture-run")
        self.vercel = VercelDeploymentLinks("fixture-deployment.vercel.app", ("/", "/preview"))
        self.policy = EvidenceLinkPolicy("fixture-owner", "fixture-repo", SHA, (self.depot,), (self.vercel,))

    def test_exact_registered_commit_is_event_compatible_without_completion_claim(self):
        payload = github_commit_link(self.policy, owner="fixture-owner", repository="fixture-repo", sha=SHA)
        row = Event("git", "signed-worker-1", "metadata-v1", "2026-10-05T10:00:00Z", "2026-10-05T10:01:00Z",
                    {"kind": "published_worker_metadata", **payload}, project_id="approved-project").cloud()
        self.assertEqual(row["payload"]["sha"], SHA)
        self.assertNotIn("verified", row["payload"])
        for values in ({"owner": "other-owner", "repository": "fixture-repo", "sha": SHA},
                       {"owner": "fixture-owner", "repository": "fixture-repo", "sha": "b" * 40},
                       {"owner": "fixture-owner", "repository": "fixture-repo", "sha": "a" * 64}):
            with self.assertRaises(ValueError):github_commit_link(self.policy, **values)

    def test_depot_requires_exact_org_run_existing_url_and_registered_sha(self):
        result = depot_run_link(self.policy, org_id=self.depot.org_id, run_id=self.depot.run_id,
                                url=self.depot.url + "?token=private#fragment", sha=SHA)
        self.assertEqual(result["url"], self.depot.url)
        for change in ({"org_id": "other-org"}, {"run_id": "other-run"},
                       {"url": "https://depot.dev/fixture-org/other-run"}, {"sha": "b" * 40}):
            values = {"org_id": self.depot.org_id, "run_id": self.depot.run_id, "url": self.depot.url, "sha": SHA, **change}
            with self.assertRaises(ValueError):depot_run_link(self.policy, **values)
        empty = replace(self.policy, depot_runs=())
        with self.assertRaises(ValueError):depot_run_link(empty, org_id=self.depot.org_id, run_id=self.depot.run_id, url=self.depot.url, sha=SHA)

    def test_vercel_has_no_host_wildcard_or_implicit_path_discovery(self):
        url = "https://fixture-deployment.vercel.app/preview?token=private"
        self.assertEqual(vercel_deployment_link(self.policy, url=url, sha=SHA)["url"], url.split("?")[0])
        for rejected in ("https://other-deployment.vercel.app/preview", "https://fixture-deployment.vercel.app/other",
                         "https://fixture-deployment.vercel.app/%70review", "https://fixture-deployment.vercel.app/Users/private/file"):
            with self.assertRaises(ValueError):vercel_deployment_link(self.policy, url=rejected, sha=SHA)
        with self.assertRaises(ValueError):vercel_deployment_link(replace(self.policy, vercel_deployments=()), url=url, sha=SHA)

    def test_policy_registration_is_bounded_public_and_canonical(self):
        bad_policies = [replace(self.policy, github_repository=".."), replace(self.policy, commit_sha="a" * 64),
            replace(self.policy, depot_runs=(self.depot,) * 17), replace(self.policy, depot_runs=(self.depot, self.depot)),
            replace(self.policy, depot_runs=(DepotRunLink("fixture-org", "fixture-run", "https://other.example/fixture-org/fixture-run"),)),
            replace(self.policy, vercel_deployments=(VercelDeploymentLinks("fixture-deployment.vercel.app", ("/secret/value",)),)),
            replace(self.policy, vercel_deployments=(VercelDeploymentLinks("service.local", ("/",)),))]
        for policy in bad_policies:
            with self.assertRaises(ValueError):policy.validate()


if __name__ == "__main__":
    unittest.main()
