/**
 * Glyphs for drawing other apps' chrome inside the phone mockups. They stand in for Instagram's heart,
 * X's repost and so on, so they live here rather than in the app's own icon set.
 */
import {
  IconArrowBackUp,
  IconArrowBigDown,
  IconArrowBigUp,
  IconArrowForwardUp,
  IconArrowLeft,
  IconAward,
  IconBell,
  IconBookmark,
  IconBrandMessenger,
  IconBrandWhatsapp,
  IconBriefcase,
  IconBroadcast,
  IconBuildingStore,
  IconCalendarEvent,
  IconCamera,
  IconCash,
  IconChartBar,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCirclePlus,
  IconClock,
  IconCoin,
  IconCompass,
  IconDisc,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconExternalLink,
  IconEye,
  IconFile,
  IconFileText,
  IconFlame,
  IconGift,
  IconHash,
  IconHeart,
  IconHeartFilled,
  IconHome,
  IconHomeFilled,
  IconInbox,
  IconLayoutGrid,
  IconLink,
  IconLock,
  IconMail,
  IconMapPin,
  IconMenu2,
  IconMessageCircle,
  IconMessageCircle2,
  IconMessages,
  IconMicrophone,
  IconMoodSmile,
  IconMovie,
  IconMusic,
  IconNavigation,
  IconNews,
  IconPaperclip,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPinned,
  IconPlayerPlayFilled,
  IconPlus,
  IconQuote,
  IconRepeat,
  IconRosetteDiscountCheckFilled,
  IconSearch,
  IconSend,
  IconSend2,
  IconSettings,
  IconShare2,
  IconShare3,
  IconShoppingBag,
  IconSparkles,
  IconSpeakerphone,
  IconSquarePlus,
  IconStar,
  IconStarFilled,
  IconSticker,
  IconTag,
  IconThumbDown,
  IconThumbUp,
  IconUser,
  IconUserCircle,
  IconUserPlus,
  IconUsers,
  IconUsersGroup,
  IconVideo,
  IconVolume,
  IconWorld,
  IconX
} from '@tabler/icons-react';

export const AppIcons = {
  award: IconAward,
  back: IconChevronLeft,
  arrowLeft: IconArrowLeft,
  bag: IconShoppingBag,
  bell: IconBell,
  bookmark: IconBookmark,
  briefcase: IconBriefcase,
  broadcast: IconBroadcast,
  calendarEvent: IconCalendarEvent,
  camera: IconCamera,
  cash: IconCash,
  chartBar: IconChartBar,
  check: IconCheck,
  chevronDown: IconChevronDown,
  chevronRight: IconChevronRight,
  circlePlus: IconCirclePlus,
  clock: IconClock,
  close: IconX,
  coin: IconCoin,
  comment: IconMessageCircle,
  commentRound: IconMessageCircle2,
  compass: IconCompass,
  disc: IconDisc,
  dots: IconDots,
  dotsVertical: IconDotsVertical,
  download: IconDownload,
  downvote: IconArrowBigDown,
  externalLink: IconExternalLink,
  eye: IconEye,
  file: IconFile,
  fileText: IconFileText,
  flame: IconFlame,
  forward: IconArrowForwardUp,
  gift: IconGift,
  globe: IconWorld,
  grid: IconLayoutGrid,
  hash: IconHash,
  heart: IconHeart,
  heartFilled: IconHeartFilled,
  home: IconHome,
  homeFilled: IconHomeFilled,
  inbox: IconInbox,
  link: IconLink,
  lock: IconLock,
  mail: IconMail,
  menu: IconMenu2,
  messages: IconMessages,
  messenger: IconBrandMessenger,
  mic: IconMicrophone,
  movie: IconMovie,
  music: IconMusic,
  navigation: IconNavigation,
  news: IconNews,
  paperclip: IconPaperclip,
  pencil: IconPencil,
  phone: IconPhone,
  photo: IconPhoto,
  pin: IconMapPin,
  pinned: IconPinned,
  play: IconPlayerPlayFilled,
  plus: IconPlus,
  quote: IconQuote,
  reply: IconArrowBackUp,
  repeat: IconRepeat,
  search: IconSearch,
  send: IconSend,
  sendAlt: IconSend2,
  settings: IconSettings,
  share: IconShare3,
  shareNodes: IconShare2,
  smile: IconMoodSmile,
  sparkles: IconSparkles,
  speakerphone: IconSpeakerphone,
  squarePlus: IconSquarePlus,
  star: IconStar,
  starFilled: IconStarFilled,
  sticker: IconSticker,
  store: IconBuildingStore,
  tag: IconTag,
  thumbDown: IconThumbDown,
  thumbUp: IconThumbUp,
  upvote: IconArrowBigUp,
  user: IconUser,
  userCircle: IconUserCircle,
  userPlus: IconUserPlus,
  users: IconUsers,
  usersGroup: IconUsersGroup,
  verified: IconRosetteDiscountCheckFilled,
  video: IconVideo,
  volume: IconVolume,
  whatsapp: IconBrandWhatsapp
};
